### ISSUE TITLE
add model and implementation-notes documents

### ISSUE THREAD

**Issue by jbphet** [phetsims/masses-and-springs#104]
We generally create two documents to help with the maintenance of the simulations, model.md and implementation-notes.md.  The audience for the former is people outside of PhET who may need a bit more information about how the simulation functions and what assumptions we made, and the latter is for internal use, and describes the 'big picture design' issues.  See https://docs.google.com/document/d/1og0hxKuOJjDQ1tZXj-y0hH8gnczBdiY9lmJ1JgfLFAw/edit#heading=h.cc7usaimiz55 for information about where these docs should be.

It is generally a good idea to create these documents early in the development process, add notes to them as the implementation progresses, and then turn them into something readable when the simulation is close to publication.

One thing that definitely should go into the implementation-notes document is something about the tricky three-way relationship between the spring constant, the spring thickness, and the spring length, and how that was handled in the code.

**Comment by Denz1994** [comment]
Could you give the model and implementation notes a review @jonathanolson and comment on any suggestions or changes?

**Comment by Denz1994** [comment]
After reviewing with @jonathanolson, there were some typo fixes but overall the documentation is in good shape. I will leave it up to @jonathanolson to update the mathematical expressions as need be after working on #98.
