### ISSUE TITLE
equilibrium position doesn't get updated in some circumstances

### ISSUE THREAD

**Issue by jbphet** [phetsims/masses-and-springs#105]
The equilibrium position in `EquilibriumLineNode` is only updated when visible.  This can lead to it being in an incorrect position if it is made invisible, then something that affects it is changed (such as the spring length when in the 'unequal sizes' mode), then it is made visible again.

This was found during code review, see #36.

**Comment by Denz1994** [comment]
Thanks for the report. I originally did this so the position updates for the reference lines don't need to be called when you can't see the lines in the view. However, you noticed a bug with this approach, so now the positions update regardless of visibility. Assigning to @jbphet for to review and close.

**Comment by jbphet** [comment]
Changes look reasonable, and the symptom seen before is now gone.  Closing.
