### ISSUE TITLE
masses can be lost off screen

### ISSUE THREAD

**Issue by jbphet** [phetsims/masses-and-springs#106]
Masses can be dragged off the screen and dropped, making them inaccessible to the user until a reset is performed.

This was noticed during code review, see #36.

My suggestion would be to replace the `TandemSimpleDragHandler` in `MassNode` with a `MovableDragHandler`.  There are a lot of examples of the usage of this drag handler in the code that you can draw from.

**Comment by Denz1994** [comment]
Bounds added to mass so they can't be dragged off screen. After discussing with @jbphet and @arouinfar, they behavior of the masses being dragged limits the amount of oscillation that can be produced in the sim. This isn't a problem and is within the reasonable bounds of the sims expectations.

 Thanks for the input.

**Comment by Denz1994** [comment]
We changed the bounds of the screenView so there is still a possibility of losing the masses on smaller screens. 

As of now, the TwoSpringView is behaving ideally. We don't lose the masses anymore, but the ruler and timer can still be lost.

**Comment by Denz1994** [comment]
We need to apply the same bounds to the OneSpringView

**Comment by Denz1994** [comment]
This was handled already. Closing.
