### ISSUE TITLE
cursor for the handle for the reference line doesn't behave quite right

### ISSUE THREAD

**Issue by jbphet** [phetsims/masses-and-springs#107]
On the current master, the little knob on the reference line doesn't cause the cursor to change to a hand for all of it.

It probably just needs the following line of code added to the creation of the `LasterPointerNode` in `MovableLineNode`.

```
      cursor: 'pointer'
```

**Comment by Denz1994** [comment]
I made a change to the cursor and it now changes to indicate the movableLineNode is pickable. Thanks for the suggestion. Closing.
