### ISSUE TITLE
Floating panels in for screens

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#108]
Should the panels float outside of the dev bounds? I am working on having the right outermost panels float along with the play button controls, play speed radio group, and the reset button. I will post a dev version to look at soon.

**Comment by Denz1994** [comment]
@arouinfar Do you think that we need floating panels for the sim due to the space constraints on the lab screen? The masses are a bit too large to fit in the space. How do you think we should handle this?

You can see the difference in the spacing in the intro/vector (floating) screens vs. the energy/lab (non-floating) screens.

**Comment by arouinfar** [comment]
@Denz1994 and I chatted a bit about this yesterday afternoon. Floating panels won't address the issue of a crowded Lab screen on iPad, so we'll need to make a few layout tweaks.

- [x] Float panels on all screens (looks less claustrophobic)
- [x] Tools also need to float
- [x] Move mass panel to top of screen to free up space for the masses
- [x] Format mass slider track like Gravity (add min/max ticks marks with values)
- [x] Reduce the amount of padding between the tweakers and mass slider track

**Comment by Denz1994** [comment]
The floating panels have been added to both screens.

**Comment by Denz1994** [comment]
MassValueControlPanel had been moved to the top of the sim screen.

**Comment by Denz1994** [comment]
Added labels to the massValueControlPanel.

**Comment by Denz1994** [comment]
I made some adjustments to the MassValueControlPanel and the floating panels. I will move the issue relating to "tool panels need to float." As of right now, I have released a dev version for review.
@arouinfar How does the mass panel positioning look? How about the floating panels?

Should the masses float as well? 
http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.8/masses-and-springs_en.html

**Comment by arouinfar** [comment]
@Denz1994 the positioning of the mass panel and the floating panels look good! It seems that the velocity/acceleration panel on Lab doesn't float, though. The behavior of the floating masses looks good to me.

**Comment by Denz1994** [comment]
Oh sorry, must have missed that panel. I will work on the panel floating and the masses floating. Thanks.

**Comment by Denz1994** [comment]
The vector panel floats in the current [version](http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.10/masses-and-springs_en.html). A new issue has been opened for the massNodes. Reference #118.
