### ISSUE TITLE
consolidate and fix NaturalLengthLineNode and EquilibriumLineNode

### ISSUE THREAD

**Issue by jbphet** [phetsims/masses-and-springs#110]
`NaturalLengthLineNode` and `EquilibriumLineNode` are very similar - both are dashed, colored lines that follow a position property in the Y direction.  These should be consolidated.  Options can be used to set the differences.

Also, both have an issue with how they position themselves based on the property.  Below is an excerpt from `NaturalLengthLineNode`:

```js
    spring.bottomProperty.link( function( bottom ) {

      // @private {read-write} Y position of line in screen coordinates
      var yPos = modelViewTransform2.modelToViewY( bottom );

      // @private {read-write} position of line in screen coordinates
      self.positionProperty = new Property( new Vector2( xPos, yPos ), {
          tandem: tandem.createTandem( 'positionProperty' ),
          phetioValueType: TVector2
        } );

      // Link that handles the change in the lines position in screen coordinates
      self.positionProperty.link( function( position ) {
          self.translation = position.minus( new Vector2( LINE_LENGTH / 2, 0 ) );
        } );

    } );
```

This is creating a new property a linking to it every time the position of the spring changes, which is unnecessary and almost certainly leaks memory.  The Y position could just be set as the transformed bottom position, no secondary property is needed.

Finally, there is a `reset` function.  This won't be needed once the secondary property is removed, so it can go away as well.

**Comment by jbphet** [comment]
Also, both of these have code to dilate the touch and mouse areas, but as far as I can tell from interacting with the simulation, neither of them are interactive, so I suspect that code can be removed.

**Comment by Denz1994** [comment]
A new referenceLineNode.js was created to consolidate these two files. There was some code that was removed as well.
