### ISSUE TITLE
consolidate common model-view transform

### ISSUE THREAD

**Issue by jbphet** [phetsims/masses-and-springs#111]
The following code, with only very minor variations, is repeated five times in masses-and-springs.  This is a sign that this should be consolidated, either by refactoring other portions of the code or pulling into a common area.

```js
    var modelViewTransform2SpringHeight = ModelViewTransform2.createSinglePointScaleInvertedYMapping(
      Vector2.ZERO,
      new Vector2( 0, this.visibleBoundsProperty.get().height * 1 ),
      397
    );
```

**Comment by Denz1994** [comment]
I referenced the model view transform as a constant in the constant file. The springs still use a different mvt though. I will continue to investigate.

**Comment by Denz1994** [comment]
The mvt implemented now is used to set positioning values for the springNodes and for the hanger node. The function in the constant file suffices for the positioning arguments of our view components.
