### ISSUE TITLE
EnergyModel seems unnecessary

### ISSUE THREAD

**Issue by jbphet** [phetsims/masses-and-springs#114]
The `EnergyModel.js` file is just a specific configuration (i.e. two specified option values) of the `MassesAndSprings` parent type.  This adds an unnecessary level of inheritance, and it would be simpler to just use the parent model directly.  There is no rule that says that there must be a model type for each screen.

**Comment by jbphet** [comment]
This is also true for `EnergyScreenView`, i.e. it does essentially nothing, and the parent class should just be directly used in `EnergyScreen`.

**Comment by jbphet** [comment]
This was found during code review, see #36.

**Comment by jbphet** [comment]
This is also true of `VectorModel`.

**Comment by Denz1994** [comment]
> There is no rule that says that there must be a model type for each screen.

I think I got the original idea came from this point in the PhET code-review checklist:

>  Model and view code should be in model/ and view/ subdirectories for each screen and common/

I must have misinterpreted this because if there is nothing in the file it should be removed and not left in the sim code. I'll remove the unused files.

**Comment by Denz1994** [comment]
I removed some unused model/view directories.

**Comment by Denz1994** [comment]
Closing because these models have been removed and they are still unused.
