### ISSUE TITLE
consolidate SingleSpringHangerNode and SpringHangerNode

### ISSUE THREAD

**Issue by jbphet** [phetsims/masses-and-springs#115]
There are a number of duplicated values for things like the fill and the rectangle rounding in `SingleSpringHangerNode` and `SpringHangerNode`, which means these would need to be changed in two places if the design changes.  It should be reasonably straightforward to consolidate this object into a single type that takes an array of springs and adjusts the width and labeling accordingly.

This was noticed during code review, see #36.

**Comment by Denz1994** [comment]
Thanks for the suggestion. Some of these implementations were from months ago and I feel I know better now, but never got around to refactoring. Thanks for the review.
