### ISSUE TITLE
Tools don't drag well with floating bounds

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#117]
We may need to change the drag bounds on the ruler and timer. The toolbox items just warp back and forth on the sim rather than positioning where they should be. This was mentioned by @arouinfar as part of a review of #108.

**Comment by Denz1994** [comment]
We should look into employing MoveableDragHandler instead of TandemSimpleDragHandler.

**Comment by Denz1994** [comment]
Changed the drag bounds of the ruler and timer nodes to respect the visible bounds of the screen. I also used MoveableDragHandler and got rid of TandemSimpleDragHandler.

**Comment by Denz1994** [comment]
The ruler and timer can still be lost off of the screen if they are dragged too far to the extremes of the visible bounds of the screen. If you adjust the screen's bounds (minimize/maximize screen size) then they return into the view. 

We should probably have the bounds of the nodes not intersect with the visible bounds of the screen.

**Comment by Denz1994** [comment]
The rulerNode and timerNode no longer get lost off of the screen. The center of the nodes stays within the screen bounds as expected. Posting a [dev version](http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.9/masses-and-springs_en.html) for @arouinfar  to review behavior.

@arouinfar If you don't see any issues with the ruler and timer being dragged off or floating please close this issue. Thanks.

**Comment by arouinfar** [comment]
@Denz1994 tools an be completely dragged off-screen on the left and bottom part of the screen.

**Comment by arouinfar** [comment]
To reproduce:
Resize the window so it is very wide
Drag ruler as far left as possible.
To retrieve the ruler, make the window narrow, and then wide again.

**Comment by Denz1994** [comment]
I didn't apply the fix to all of the screens. Sorry for the mix-up. @arouinfar Try this [version](http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.10/masses-and-springs_en.html).

**Comment by arouinfar** [comment]
Thanks @Denz1994. Looks great!
