### ISSUE TITLE
Images need license entries

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#121]
Looks like the license.json file was deleted in https://github.com/phetsims/masses-and-springs/commit/a57d4c980a4d4e3b067c2194e91f39c5f2c91e49, not that it had anything in it... 

@Denz1994, all images need an associated license entry in that file if the sim is to build at all. Please look at other license files for how to do this (like https://github.com/phetsims/pendulum-lab/blob/master/images/license.json), or if you are unsure of an image's source, ask @ariel-phet or @arouinfar.

**Comment by Denz1994** [comment]
I added the license.json along with the licenses from the sim I derived the images from (Make-A-Ten). I was running into an issue where I couldn't build, but this solved it. I can run a successful local build now. Can you confirm a successful build as well? @phet-steele

**Comment by phet-steele** [comment]
I can build! Gracias!
