### ISSUE TITLE
Positioning of massNode when bounds change?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#124]
Consider the following:

Scenario A: Mass is at rest at the default position and the mass value changes, thereby increasing the size of the mass. The mass node should remain in the position as if it is at rest on the ground.

![image](https://user-images.githubusercontent.com/13894380/30920643-8500ba7a-a372-11e7-8339-7201ea133d35.png)

![image](https://user-images.githubusercontent.com/13894380/30920726-b0c56a0c-a372-11e7-9b5a-c3b41a2abd8d.png)

Scenario B: Mass is at rest at the default position and the screen size changes where there is a considerable gap in the bottom of the screen and the default position. Should the mass node then remain in its position while changing its size?

![image](https://user-images.githubusercontent.com/13894380/30921260-06bc7274-a374-11e7-9f6a-0ceb097a02a1.png)

![image](https://user-images.githubusercontent.com/13894380/30921309-2c41d502-a374-11e7-86f4-604c968bb03a.png)

**Comment by arouinfar** [comment]
@Denz1994 when the screen is narrow, the mass appears to be floating, which I find a little odd. Is it possible for the mass to maintain a fixed distance from the navbar? That way, it would essentially float down with the navbar at narrow aspect ratios.

**Comment by Denz1994** [comment]
We can make the masses float. However, if we take a situation where a massNode is a stationary mid-air (due to the sim being paused or zero gravity) we should not have this mass node float. Correct? @arouinfar

**Comment by arouinfar** [comment]
Correct @Denz1994. The floating would only apply to masses that _aren't_ connected to the spring.

**Comment by arouinfar** [comment]
During yesterday's design meeting, we decided to kill the floating massNode, and instead create a shelf for the masses to sit on. See the [meeting notes](https://docs.google.com/document/d/13SiJic3Ha_x2FNW_XYFLZGCHRxCG5YLxE_zAu4t5tmQ/edit#heading=h.jaakc7xvrv54) for further discussion.

I'll open a separate issue for the shelf, so I think you can close this one @Denz1994.

**Comment by Denz1994** [comment]
Thanks for the update @arouinfar.
