### ISSUE TITLE
Label the Zero cm on the ruler

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#126]
The ruler should have the zero right at the edge of the ruler. Get rid of the extra tick mark and the label at the ends. Like a real ruler.  
![image](https://user-images.githubusercontent.com/13894380/30988512-85cf90d8-a468-11e7-813f-df749d8e3305.png)

**Comment by arouinfar** [comment]
A little clarification @Denz1994 -- we decided to ditch the extra padding so that 0 and 100 line up with the edge of the ruler, but these tick marks do not need to be labelled. The team liked the ruler used in Pendulum Lab, so you can use that as a reference for the tick marks/labelling.
