### ISSUE TITLE
Create shelf for masses to sit on

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#127]
In #124 we considered allowing the massNode to float down with the navbar at narrow aspect ratios, because the masses appear to be floating in mid-air at narrow aspect ratios. Given that the masses free fall when released in play area, masses floating in mid-air is undesirable. 

In #123 we decided to explicitly show where GPE=0, and that it should be aligned with the bottom of the masses's resting position. For this reason, the masses should **not** float down with the navbar, as the GPE reference would become variable.

The consensus was to instead create a shelf for the masses to sit on. 
* Each mass will have its own specific home location on the shelf
* The z-ordering of the masses will keep the smallest on top
* When released in the play area, the mass will animate back to the shelf. Since it's desirable to continue to show the free fall, the horizontal and vertical motion will be animated separately. First, the mass will quickly zip across the screen horizontally, and then free fall into its home position. 
* Masses should be confined to the visible bounds when dragging, unless attached to a spring 

Self assigning to mock up the shelf and GPE=0 line.

**Comment by arouinfar** [comment]
Here are the shelf mockups discussed in the 10/5/17 design meeting.
* Thin shelf with same color used in Unit Rates
* The width can vary across screens, as necessary
* For Energy and Lab, add a "height = 0" reference line centered below the spring. It will have a similar look to the other reference lines, and will be the same light blue used for GPE in the bar graph. 

![image](https://user-images.githubusercontent.com/8419308/31512361-e43ffcea-af47-11e7-977e-6d59552338e5.png)

![image](https://user-images.githubusercontent.com/8419308/31512353-da0ed37c-af47-11e7-8957-fd70d51f6a56.png)

Tagging for design meeting to discuss the shelf appearance in dev.20.

**Comment by arouinfar** [comment]
Overall looking nice @Denz1994! 

Pixel-polishing requests for the shelf:
* Bottom-align the shelf with the h=0 line.
* Move play/pause/step and normal/slow up a bit so that the "height = 0" label is not obscured. A few px will probably do the trick.
* The shelf on the Energy screen could be a bit narrower. Here's a comparison between the current length, and a narrower shelf.


<img width="141" alt="screen shot 2017-10-12 at 3 43 50 pm" src="https://user-images.githubusercontent.com/8419308/31520782-5731d3e2-af64-11e7-9b48-5c6c8c91556e.png"> <img width="92" alt="screen shot 2017-10-12 at 3 44 19 pm" src="https://user-images.githubusercontent.com/8419308/31520783-5747a0b4-af64-11e7-842d-d50deb59abb5.png"> <img width="91" alt="screen shot 2017-10-12 at 3 45 59 pm" src="https://user-images.githubusercontent.com/8419308/31520826-7d48c96e-af64-11e7-8c56-c39b9be6f356.png">

* On Energy and Lab, left-align the shelf with the mass panel. 
* On Lab, the 300g mass hangs off the edge of the shelf. In general, I think the masses can be packed a bit tighter, and they'd still be grabbable. The shelf seems a bit cramped between the energy graph and the h=0 line, so I would also make the shelf slightly shorter too.
![image](https://user-images.githubusercontent.com/8419308/31521120-94a2a9b2-af65-11e7-89e1-878385f6b701.png)

**Comment by Denz1994** [comment]
I have applied the desired alterations to the shelf and the massNodes. They are visible in the latest dev version http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.21/masses-and-springs_en.html.

If @arouinfar doesn't see any room for improvement, you may close this issue. Thanks for the feedback!

**Comment by Denz1994** [comment]
After our discussion on Friday, I am closing this issue as there were no issues brought up with the shelf.
