### ISSUE TITLE
Animation for a falling mass?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#133]
There were two proposed designed for a mass that has been dropped by a user. If a mass isn't attached to a spring it should:

1. Fall at the rate of gravity and then animate to its default resting position on the shelf. Take a look here: [1.0.0-dev.22](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.22/masses-and-springs_en.html)

2. Animate to the x position of its default resting position and then fall at the rate of gravity to the shelf. Take a look here:  [1.0.0-dev.23](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.23/masses-and-springs_en.html)

In both cases, the "animating" part of the falling sequence should not be affected by slow motion.

DB and JO: Animation 1 looks more natural because the user gets immediate feedback about the system in relation to gravity. The sim related model isn't interrupted by an animation that is arbitrarily constructed for visual appeal.

AP: @arouinfar and @denz1994 should discuss this further in our meeting on Friday to make a final decision on the animation.

**Comment by arouinfar** [comment]
After discussion with @Denz1994 we've decided to go with option (1) -- fall then zoom (dev.22). Falling first makes more conceptual sense. While not a primary learning goal, students can also see that all objects fall at the same rate, which isn't possible with option (2). Back to you @Denz1994.

**Comment by Denz1994** [comment]
The decided on animation has been merged into master and fixed. Thanks for the suggestion @arouinfar. Revision made in commit 2f379e237ed33cf9f56cd9b9075a5cd85302511e.

**Comment by arouinfar** [comment]
Looks great @Denz1994!
