### ISSUE TITLE
Spacing between play/pause and step button

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#134]
@Denz1994 the spacing between the play/pause and step button is a bit large (they should feel like a coherent group).

![playpause](https://user-images.githubusercontent.com/4051174/31787495-3272bc32-b4c9-11e7-81d6-5fd95438c20f.PNG)

See pendulum lab for an example of ideal spacing.

**Comment by Denz1994** [comment]
After talking with @arouinfar, we decided that the spacing in Pendulum lab should be duplicated. This means using the same vertical spacing between the "Normal" and "Slow Motion" radio buttons and the spacing between step button and the play speed buttons.
