### ISSUE TITLE
Energy graph pixel Polishes

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#142]
- [x] Increase corner radius to match panels
- [x] T_tot should be E_tot
- [x] Top-align labels
- [x] Clear heat button below E_therm
- [x] Move up baseline so there’s more room to see a little big more of negative PE_grav, as well as allow room for i18n
- [x] Left-align info button with inner panel
- [x] Right-align zoom buttons with inner panel
- [x] Add a few px white space between zoom buttons
- [x] Add thin black border to bars

**Comment by arouinfar** [comment]
List looks good @Denz1994. Please let me know if you have any questions!

**Comment by Denz1994** [comment]
After merging with 'portedGraph' branch, these changes have been made.
