### ISSUE TITLE
Natural Length should remain constant (unless spring length changed)

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#143]
The natural length of a spring is its length when no force is applied, and in general, should never change. The only exception is on screen 1, scene 2 where the spring length can be changed.

For example, these natural lengths are correct
![image](https://user-images.githubusercontent.com/8419308/32013200-76577444-b977-11e7-8b31-987808fa7b55.png)

Adding a mass to the spring shifts the position of the natural length line. However, the natural length line should instead remain at the position shown in the screenshot above.
![image](https://user-images.githubusercontent.com/8419308/32013173-61474048-b977-11e7-996e-3c1a57ed7964.png)

**Comment by Denz1994** [comment]
@arouinfar I think I pushed a fix for this sometime earlier today. Were you able to reproduce this on master?

**Comment by arouinfar** [comment]
Please disregard @Denz1994! I thought I was looking at master, but I was instead using dev.24. The natural length behavior is correct in master.
