### ISSUE TITLE
String file housekeeping

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#151]
Looking at `masses-and-springs-strings_en.json`, there are some small changes to be made to follow convention and to clean it up:

- [x] I would recommend making this file alphabetical.
- [x] Screen title string keys should follow the convention: `screen.{{screenName}}`, eg. 

```js
 "screen.intro": {
    "value": "Intro"
  }
```
not 
```js
 "intro": {
    "value": "Intro"
  }
```
- [x] Vector (the screen) should be renamed to Vectors as per request
- [x] Should remove "0 g" (see #159):
```js
 "body.zeroG": {
    "value": "0 g"
  }
```
- [x] "Slow Motion" should be changed to "Slow". Change the string key as well.

For phetsims/QA/issues/67.

**Comment by phet-steele** [comment]
Looks good to me, thanks @Denz1994. We'll close this and wait for a code review to see if there are any remaining issues. Note that also now all files that still say "Vector", like `VectorScreenView.js`, should be changed to "Vectors". Ought to be fun.

**Comment by Denz1994** [comment]
The variable and file names that reference the Vectors tab have been updated.
