### ISSUE TITLE
Vectors should be at center of mass

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#152]
Every vector needs to be at the center of mass. They are currently wherever this is:

<img width="261" alt="screen shot 2017-11-10 at 3 19 13 pm" src="https://user-images.githubusercontent.com/5863899/32680997-980d207e-c62a-11e7-83f4-c614b57f9619.png">

Seen on macOS 10.13.1 Chrome. For phetsims/QA/issues/67.

URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.28/masses-and-springs_en.html
Version: 1.0.0-dev.28 2017-11-10 19:03:33 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4918cd72","branch":"master"},"babel":{"sha":"fcbcac44","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"ca18330e","branch":"master"},"dot":{"sha":"4a1ddd12","branch":"master"},"griddle":{"sha":"6e1983be","branch":"master"},"joist":{"sha":"f34dc747","branch":"master"},"kite":{"sha":"e4c0b773","branch":"master"},"masses-and-springs":{"sha":"9d24969e","branch":"master"},"phet-core":{"sha":"ad21faf3","branch":"master"},"phetcommon":{"sha":"d957aefc","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"8e5b0892","branch":"master"},"scenery-phet":{"sha":"11c7fdb3","branch":"master"},"sherpa":{"sha":"5079b265","branch":"master"},"sun":{"sha":"71295bf0","branch":"master"},"tandem":{"sha":"547eb84d","branch":"master"},"twixt":{"sha":"13905577","branch":"master"}}

**Comment by Denz1994** [comment]
The vectors have been aligned to start at the center of the mass nodes. However, the vectors now cover the labels of the masses like this:
 
![image](https://user-images.githubusercontent.com/13894380/32965644-1f7367ec-cba5-11e7-9eda-90915a1bee84.png)

I don't think the overlap is an issue because showing the vectors is optional. Any thoughts @arouinfar @phet-steele. I could make the arrows thinner if it is an issue.

**Comment by arouinfar** [comment]
@Denz1994 I think it's acceptable to occlude the mass labels. Vectors are generally drawn from the center of mass, so I think it's important to stick to this convention. As you point out, users can turn off the vectors to read the mass label.

**Comment by phet-steele** [comment]
Vectors are placed correctly in master.
