### ISSUE TITLE
Net force is not reset when a mass is stopped

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#164]
1. 2nd screen, turn on "Net Force"
2. Get a mass oscillating, then press the "stop" button for that mass
3. The "Net Force" arrow will still be visible and non-zero, even though the mass isn't moving (and at equilibrium):

<img width="710" alt="screen shot 2017-11-17 at 1 32 05 pm" src="https://user-images.githubusercontent.com/5863899/32967692-bc159660-cb9b-11e7-8ab2-72f2a82e789d.png">

The component view is correctly summing to zero after a reset:

<img width="380" alt="screen shot 2017-11-17 at 1 37 27 pm" src="https://user-images.githubusercontent.com/5863899/32967897-7d964046-cb9c-11e7-90df-29fe40860dbf.png">

Seen on macOS 10.13.1 Chrome. For phetsims/QA#67.

URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.28/masses-and-springs_en.html
Version: 1.0.0-dev.28 2017-11-10 19:03:33 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4918cd72","branch":"master"},"babel":{"sha":"fcbcac44","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"ca18330e","branch":"master"},"dot":{"sha":"4a1ddd12","branch":"master"},"griddle":{"sha":"6e1983be","branch":"master"},"joist":{"sha":"f34dc747","branch":"master"},"kite":{"sha":"e4c0b773","branch":"master"},"masses-and-springs":{"sha":"9d24969e","branch":"master"},"phet-core":{"sha":"ad21faf3","branch":"master"},"phetcommon":{"sha":"d957aefc","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"8e5b0892","branch":"master"},"scenery-phet":{"sha":"11c7fdb3","branch":"master"},"sherpa":{"sha":"5079b265","branch":"master"},"sun":{"sha":"71295bf0","branch":"master"},"tandem":{"sha":"547eb84d","branch":"master"},"twixt":{"sha":"13905577","branch":"master"}}

**Comment by Denz1994** [comment]
Commit bf504859b1e5ac46b74545ac047fbe5d5e1c83dc may have fixed this.

**Comment by phet-steele** [comment]
Looks fixed.
