### ISSUE TITLE
Thermal energy questions

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#167]
On the 3rd and 4th screen you'll see some funkiness with thermal energy. Do this:

0. From sim start, default damping, go to the 3rd screen.
1. Pause the sim.
2. Attach the variable mass item to the spring
3. Move the mass slider around and you'll see some thermal energy either increase or decrease

![mas07](https://user-images.githubusercontent.com/5863899/32970656-2a483902-cba7-11e7-9f5d-b1d87e719ed1.gif)

My questions/concerns:
1. The thermal energy goes negative, this certainly seems wrong
2. Should thermal energy being changing at all here?
3. Maybe thermal energy should change, but maybe total energy shouldn't be?
4. I'm really confused...

Seen on macOS 10.13.1 Chrome. For phetsims/QA#67.

URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.28/masses-and-springs_en.html
Version: 1.0.0-dev.28 2017-11-10 19:03:33 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4918cd72","branch":"master"},"babel":{"sha":"fcbcac44","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"ca18330e","branch":"master"},"dot":{"sha":"4a1ddd12","branch":"master"},"griddle":{"sha":"6e1983be","branch":"master"},"joist":{"sha":"f34dc747","branch":"master"},"kite":{"sha":"e4c0b773","branch":"master"},"masses-and-springs":{"sha":"9d24969e","branch":"master"},"phet-core":{"sha":"ad21faf3","branch":"master"},"phetcommon":{"sha":"d957aefc","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"8e5b0892","branch":"master"},"scenery-phet":{"sha":"11c7fdb3","branch":"master"},"sherpa":{"sha":"5079b265","branch":"master"},"sun":{"sha":"71295bf0","branch":"master"},"tandem":{"sha":"547eb84d","branch":"master"},"twixt":{"sha":"13905577","branch":"master"}}

**Comment by ariel-phet** [comment]
Thermal energy should definitely not go negative.

**Comment by arouinfar** [comment]
Thanks @phet-steele! Something's definitely amiss with the thermal energy.

> The thermal energy goes negative, this certainly seems wrong

As @ariel-phet said, thermal energy should NEVER be negative. Actually, the only energy that should be able to go negative is the gravitational potential energy. Anything else going negative would definitely be a bug.

> Should thermal energy being changing at all here?

When the sim is paused, no. If you change the mass while the sim is paused, the GPE will change (and therefore total energy) but the KE, EPE, and thermal energy would all remain the same. Similarly, if you change the spring constant while the sim is paused, the EPE (and therefore total energy) will change, but the KE, GPE, and thermal energy would be unaffected.

> Maybe thermal energy should change, but maybe total energy shouldn't be?

If the mass is changed while it oscillates, the thermal energy could potentially increase (but never decrease, as you can't "unaccumulate" thermal energy). I would recommend you compare this case to Pendulum Lab. Increase the mass of a swinging pendulum in Pendulum Lab, and the thermal energy can appear to jump up slightly. (In PL larger masses accumulate thermal energy faster, so this makes sense).

> I'm really confused...

Me too, but I think the way the total and/or thermal energy is handled could be to blame. Thermal energy is not directly calculated from the damping itself. Instead, it can be found by:
Thermal Energy = Initial Total Energy - KE - GPE - EPE 

The Initial Total Energy should be the sum of the GPE and EPE at the instant a mass is released. 

The total energy can change if the spring constant or mass is changed. If the total energy changes, the new value would overwrite the "Initial Total Energy" referenced above. For example, pause the sim (for simplicity) and then:
* increase/decrease spring constant. The EPE will increase/decrease (increasing/decreasing the total energy), but the KE, GPE, and thermal energy will not change. 
* increase/decrease the mass. The GPE will increase/decrease (increasing/decreasing the total energy), but the KE, EPE, and thermal energy will not change.

**Comment by Denz1994** [comment]
Sorry for the confusion everyone. This was due to a spelling error in a variable declaration, which meant it didn't get referenced during a logic check. The incorrect variable that was being referenced during the logic check didn't flag an error either so we got some funky behavior in the graph.

**Comment by phet-steele** [comment]
Works great now. Thanks for the novel @arouinfar. I learned something, so this was worthwhile 😄
