### ISSUE TITLE
Equilibrium position does not update when changing mass value

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#171]
1. Go to the Lab screen.
2. Increase to max damping (for dramatic effect) and attach the variable mass.
3. When it's done oscillating, increase the mass to max (300 g). Notice how the green equilibrium line did not move with this new mass.

Some fun consequences:
4. Enable the acceleration vector. There will be a non-zero acceleration, towards the equilibrium position, yet the mass is not moving:

<img width="497" alt="screen shot 2017-12-01 at 11 25 19 am" src="https://user-images.githubusercontent.com/5863899/33497373-fa20d2ae-d68a-11e7-90b9-4a26041a8400.png">

5. Pressing the stop button will place the mass at the old equilibrium position, meaning the mass will then oscillate afterwards (note it also loses its acceleration vector...which is technically correct):

![mas08](https://user-images.githubusercontent.com/5863899/33497430-277dbf64-d68b-11e7-8a27-4c312ca86477.gif)

6. If you do step 5 with zero damping, the mass will never ever stop no matter how many times you press the stop button! (looks like it stops here only because my gif isn't seamless):

![mas09](https://user-images.githubusercontent.com/5863899/33497495-5a6aadb0-d68b-11e7-93db-89d982bd0d54.gif)

Seen on macOS 10.13.1 Chrome. For phetsims/QA/issues/67.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.28/masses-and-springs_en.html
Version: 1.0.0-dev.28 2017-11-10 19:03:33 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Language: en-US
Window: 1920x1013
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4918cd72","branch":"master"},"babel":{"sha":"fcbcac44","branch":"master"},"brand":{"sha":"53cf227b","branch":"master"},"chipper":{"sha":"ca18330e","branch":"master"},"dot":{"sha":"4a1ddd12","branch":"master"},"griddle":{"sha":"6e1983be","branch":"master"},"joist":{"sha":"f34dc747","branch":"master"},"kite":{"sha":"e4c0b773","branch":"master"},"masses-and-springs":{"sha":"9d24969e","branch":"master"},"phet-core":{"sha":"ad21faf3","branch":"master"},"phetcommon":{"sha":"d957aefc","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"8e5b0892","branch":"master"},"scenery-phet":{"sha":"11c7fdb3","branch":"master"},"sherpa":{"sha":"5079b265","branch":"master"},"sun":{"sha":"71295bf0","branch":"master"},"tandem":{"sha":"547eb84d","branch":"master"},"twixt":{"sha":"13905577","branch":"master"}}
</details>

**Comment by Denz1994** [comment]
Note to self: Check reference point for mass position in SpringStopperNode. We may be setting this reference explicitly.

**Comment by Denz1994** [comment]
There were some inconsistencies in how were were referencing the springExtension from its natural length. This meant there we needed to recalculate the springExtension when it was being used. Additionally the equilibriumYPositionProperty was not using the updated value of the massValue.

The original approach for a psuedo-stopSpring callback revolved around stepping through the model at a prolonged dt. This should be avoided in the future. I found that some values were being stored (particularly in the energies of the mass) that should not have been. Also, it doesn't work in the case of zero dampening because we will oscillate in the model infinitely.

 Thanks for the bug report. Please test in master @phet-steele.

**Comment by phet-steele** [comment]
Nice fix @Denz1994. This is working for me.
