### ISSUE TITLE
Reducing floating boxes

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#172]
@arouinfar here are some suggestions from @emily-phet - might be worth discussing at a future design meeting. I think there are a few places we could reduce the feeling of many floating control boxes (eg the spring constant controls may not even need a box, also possible the check boxes do not need a box). 

@emily-phet said:

> I was looking again at Masses and Springs. I think it looks a bit overwhelming to me, in large part because each screen has so many different floating boxes. You guys know about “subitizing” I think (human’s ability to accurately know the the number of a small group of objects without individually counting). Most people are pretty good at subitizing up to at least four (e.g., abacus’ are designed to allow calculations without subitizing beyond five). 
> 
> When groups of things get larger than four-ish, I think they have the impression of…a lot. Which is not a good thing for sim control panels. In some screens of Masses and Springs, you can have as many as seven floating grey boxes. This feels like “a lot” and I feel like I have to kind of "brace myself" as I dig into figuring out what each one is for. I think if you visually grouped more of these floating boxes, it would help a lot. For example, instead of individual floating boxes along the right side, these could be grouped into one (multicomponent) grey panel. You could also group by having the background colors of some of the boxes be something besides grey. For example, the grey boxes holding the “spring constant” sliders for each spring could be each have the same non-grey color. Maybe that color could also be used for the little grey bar thing that holds the springs up, so that whole top panel piece looks like one thing, distinct from the side panels.

**Comment by arouinfar** [comment]
@ariel-phet @emily-phet definitely food for thought. I've also found the sim to be a bit much, at times, so I think it would be good to discuss.

I'll tag this for design meeting, and work on some alternative mockups.

**Comment by arouinfar** [comment]
In the last design meeting we discussed some ways to reduce the overall visual weight including:
* Give Mass, Spring Constant, and Length floating panels white background and gray stroke
* Consolidating other panels, where possible -- #181 

@Denz1994 has already made these changes, so I think we can go ahead and close this issue.
