### ISSUE TITLE
Handling offset between COM and equilibrium

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#176]
@kathy-phet noticed: 

> Hi Amy, 
I did some playing with masses and springs today, and wanted to open a discussion with you about the placement of the force and velocity/acceleration vectors.
I'm finding a lot of cognitive overload having the force and velocity vectors being offset from the location of the application of the spring force. And I am wondering whether we might consider an alternative solution that will help students map these relationships - but that goes against the convention of placing the forces at the center of mass (I know). 
So for instance, while I play I see this ... 
![image](https://user-images.githubusercontent.com/8419308/34274873-e08dde90-e657-11e7-9d25-81bb3a7ce8f8.png)
where the force vectors are parallel with the equilibrium line but they show a net force down - no balancing spring force. I realize this is because the spring force is actually from the location of the spring attachment. 
I also find it challenging in seeing the symmetry of the oscillation (magnitude) of the net force vector as associated with the displacement of the spring around its equilibrium position. Right now it looks like its unsymmetric displacement around the equilibrium position because of the vertical difference in location of the center of mass and the point of the mass attachment to the spring. 
![image](https://user-images.githubusercontent.com/8419308/34274877-e869f504-e657-11e7-8674-713c71e8ce53.png)
Maybe its just me, but I find it hard to see what I want to see with these connections, and that I have to think really hard to make sense of how this matches with the physics I know. This makes me concerned for students who don't know the physics yet. 
While it is the unconventional place to view the free body diagram, I think it would help with developing productive relationships by placing the vectors on the same vertical position as the spring-hook intersection. 
Can you mull this over and see what you think, and we can discuss next week? Maybe a design meeting? I would be curious about playing with a version that has the vectors in this alternative location to see how it feels cognitively. I can only imagine it. With projectile motion, we created a disembodied free body diagram and that did work OK.
Best, 
Kathy 

@ariel-phet responded:
> Hey Kathy and Amy,
Why don't we move the equilibrium position to the center of mass? This would solve Kathy's issue and seems more natural to me. The mass oscillates about its equilibrium position. For an oscillating mass we are really concerned about the stretch of the spring around the equilibrium position.
I think we had been thinking about the lines here more like we had in Hooke's law, where the focus is on the displacement from the natural length of the spring. But perhaps we should refocus more on the oscillation aspect. Part of me is wondering if we really even need the "natural length" anymore. Is it buying us anything? I know I had considered a potential learning goal was realizing that the natural length was a property of the spring, but maybe that is not key to this sim. It is also sort of implicit in the two length scene, when you take a mass off, the spring returns to a certain length. 
It seems for the learning goals, maybe the most powerful solution would be to have the Equilibrium position line at the center of mass, potentially remove "natural length" and potentially add an "amplitude Line" again associated with the center of mass (Which is what I think the moveable reference line is most often used for). This way you could see the displacement from equilibrium quite clearly. We could even change the check box to say "Mass equilibrium" so there is no confusion (I don't think the word position has to be there since it will be obvious from context).
I think having the velocity and acceleration right on the center of mass is the correct solution, and maps to what has worked well in pendulum lab.
I am fairly uncomfortable with moving the free body diagram to not be associated with the center of mass. In projectile motion I think the disembodiment works well, but there are several other cues in that sim that seem to make it mesh nicely.
Ariel

@kathy-phet:
> Hi Ariel, Amy, 
I had thought about moving the equilibrium position line, but the issue I see with that is that then you really lose the relationship with stretch distance to spring force which is also critical concept here. I don't have an ideal solution which is why I would like to brainstorm and discuss more about helping students see the relationships we are hoping they will with this sim. 
Kathy

@arouinfar:
> Kathy, thank you for bringing this to our attention! I also find the offset of the equilibrium position and the vectors a bit problematic. I really like Ariel’s suggestion to move the equilibrium position to the COM and rename it “Mass Equilibrium” (or similar), as I would prefer to keep all vectors tied to the COM. This, of course, will break the relationship between the Natural Length and Equilibrium Position lines.
My goal for the Natural Length line is more procedural than conceptual. I think it’s most helpful for measuring the displacement. Ariel’s suggested “Amplitude Line” is a good alternative, and would still support the goal I had in mind.
Let’s plan to discuss this further at design meeting. I’ll also move this discussion over to a GitHub issue, so we’ll be able to keep track of it in the future.
Best,
Amy

**Comment by arouinfar** [comment]
For Vectors, Energy, and Lab:
* Remove Natural Length
* Add "Displacement" checkbox
* Shift Equilibrium Position to COM and rename "Mass Equilibrium"

Rough mockup of Displacement:
![image](https://user-images.githubusercontent.com/8419308/34276143-50cf4bb2-e65d-11e7-89d6-c7f483534afb.png)

**Comment by arouinfar** [comment]
Discussion from in the 12/21/17 design meeting:
* The Equilibrium Position and Natural Length lines support learning goals for the Intro screen, so leave these as-is.
* For the Vectors, Energy, and Lab screens, it is more useful to know where the COM is at equilibrium. On these screens, shift the equilibrium position line to the COM and rename "Mass Equilibrium". 
* It is problematic to view the Natural Length and Mass Equilibrium together, as the former references the bottom of the spring and the latter references the COM. On Vectors, Energy, and Lab, the Natural Length line was useful for measuring displacement, so let's instead have a "Displacement" checkbox that shows the displacement.
* Displacement would behave similarly to Hooke's Law -- thin arrow that points in the direction of the displacement. Unlike Hooke's Law, we do not need to display the value. Students can use the ruler to measure the length of the displacement.
* The Movable Line is a useful reference that could serve a variety of goals, such as measuring amplitude. Keep this line on all four screens.

Leaving this self-assigned to clean up the mockups for the Displacement option.

**Comment by Denz1994** [comment]
@arouinfar How are we positioning the displacement vector for the second spring node? We get overlap in the vector nodes if we keep them in the same position, as seen below. I haven't found a good solution for this.

![image](https://user-images.githubusercontent.com/13894380/34422175-cf3f59d6-ebe1-11e7-96ee-579d51d19719.png)

**Comment by Denz1994** [comment]
@arouinfar The above suggestions were implemented.[Dev 34](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.34/masses-and-springs_en.html) can be reviewed for critique. If there aren't any suggestions regarding this issue could you close?

**Comment by arouinfar** [comment]
@Denz1994 in general the Displacement arrow is looking pretty good! I have a few suggestions/observations:

* Displacement should replace the Natural Length on the Energy and Lab screens
*  The arrows feel a little bit crowded. Would it be possible to separate the two springs a bit, say 20px? The gray panel the springs attach to would need to widen a bit, causing a shift in the stop button and spring constant panels. Here's a rough mockup showing each spring being shifted 10 px outward, and the displacement being moved 5 px outward. (Creating an extra 20 px between springs and 10 px between the displacement vectors.)
![image](https://user-images.githubusercontent.com/8419308/35524622-53c38ff4-04df-11e8-88c5-170b0207d14c.png)
* Something's not quite right with the way the vector is being drawn, and the tip appears to get be misaligned, at times (sometimes overlapping the mass itself). Since this is a bug, rather than a pixel polish, I'll open a separate issue for that.

@Denz1994, would it be possible to address the first point and release a new dev version sometime today?

**Comment by arouinfar** [comment]
> Displacement should replace the Natural Length on the Energy and Lab screens

Looks like @Denz1994 is tracking this in #204, so the only remaining work left for this issue is the pixel polishing described in the 2nd bullet in my [previous comment](https://github.com/phetsims/masses-and-springs/issues/176#issuecomment-361323352).

**Comment by Denz1994** [comment]
In the previous comment by @arouinfar there was a suggestion to add spacing between the springs.

> The arrows feel a little bit crowded. Would it be possible to separate the two springs a bit, say 20px? The gray panel the springs attach to would need to widen a bit, causing a shift in the stop button and spring constant panels. Here's a rough mockup showing each spring being shifted 10 px outward, and the displacement being moved 5 px outward. (Creating an extra 20 px between springs and 10 px between the displacement vectors.)

This [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.44/phet/masses-and-springs_en_phet.html) includes the above suggestion, could you review this @arouinfar and close if need be. I also expanded the movable line node (red line) to cover the increased spacing between the springs. Reassigning to @arouinfar to close if needed.

**Comment by arouinfar** [comment]
Getting close @Denz1994! 

The displacement vectors a a bit too close to the masses, and can overlap at times.
![image](https://user-images.githubusercontent.com/8419308/35536312-c355a982-0503-11e8-9877-99b8e406c219.png)

Can you move the vectors a few pixels towards the middle?

**Comment by Denz1994** [comment]
Ahh, good catch. The patch in this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.46/phet/masses-and-springs_en_phet.html) should fix this for both two spring and one spring views. Assigning to @arouinfar for review.

**Comment by arouinfar** [comment]
Getting closer @Denz1994, but it looks like the arrow on the left is still closer to the spring than the arrow on the right. Can you move the right displacement arrow 3px further to the right, so that they match?

![image](https://user-images.githubusercontent.com/8419308/35596381-e21b55f0-05d6-11e8-970b-ae213306a303.png)

Now you know why we call it pixel polishing! 😃

**Comment by Denz1994** [comment]
The position displacement vectors have been adjusted slightly. @arouinfar Could you check in this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.60/phet/masses-and-springs_en_phet.html) if the pixels have been polished?

**Comment by arouinfar** [comment]
@Denz1994 the padding appears to be equal now! However, I think you may have moved the left arrow towards the middle rather than moving the right arrow further right. The displacement arrows are looking a bit crowded together, and should be a bit closer to their respective masses. 
![image](https://user-images.githubusercontent.com/8419308/36111129-50e975f6-0fe2-11e8-85dc-3511e29d3611.png)

Can you move each arrow 2px closer to its mass?

**Comment by Denz1994** [comment]
Sorry for all the minor changes, could you review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.62/phet/masses-and-springs_en_phet.html) @arouinfar?

**Comment by arouinfar** [comment]
@Denz1994 the pixels have all been polished! 😄
