### ISSUE TITLE
Make damping slider snappy

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#177]
From #145:

> Discussed in the 12/21/17 design meeting.
On the Vectors screen, we would need to include a damping force, which is constantly changing (bounded by exponential envelope). This representation would be quite complicated, and is not something typically covered, so we decided not to include damping.
Since Vectors will not include damping, it would be a bit odd flow-wise to include damping on the Intro screen. Other sims, such as ESPB and FAMB, do not introduce friction on the first screen, so it would not be unreasonable to leave damping off the Intro screen.
On Energy and Lab, a damping slider is appropriate, though it should be snappy (like the Friction slider in PL) so that experiments are repeatable. By default, the damping should be set to "none".

>To summarize:
Intro & Vectors: No damping
Energy & Lab: Snappy damping slider ranging "none" to "lots" (similar to Friction in PL), set to "none" by default.

Currently, the damping slider is continuous. However, a snappy slider would be more pedagogically advantageous, as it allows for repeatable measurements or instructions such as "set damping to the 3rd tick mark".

The Damping slider would look exactly like the Friction slider in Pendulum Lab:
![image](https://user-images.githubusercontent.com/8419308/34315107-1b0bfdcc-e739-11e7-87d3-cfe496d2b93d.png)

**Comment by Denz1994** [comment]
The damping slider has been made snappy along with the same visual update as pendulum lab.
