### ISSUE TITLE
convert from PropertySet to Property

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/masses-and-springs#18]
PropertySet is deprecated and should be replaced by Property, see phetsims/axon#102. Since this sim hasn't been published yet, this should be done before RC testing and publishing.

**Comment by Denz1994** [comment]
The properties contained withing the PropertyCall() have been made new Property types allowing for the removal of the PropertyCall() within the model.
Assigning @pixelzoom for input.

**Comment by Denz1994** [comment]
Reassigning to @jbphet

**Comment by Denz1994** [comment]
Commit message 4762712 should read:
Used preventGetSet() for properties to move away from PropertySet()

**Comment by Denz1994** [comment]
There are no more instances of propertySet() and removed usages of property.preventGetSet().
