### ISSUE TITLE
Consolidating Panels for Toggling Options

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#181]
Some suggestions from @ariel-phet: 
- Panels on outer bounds: Merge toolbox, gravity/damping panel, reference line panel
- Instead of white space, we want a thin horizontal hairline. Look at projectile motion intro screen.
- Do this for every screen and we can adjust as needed.
- On the lab screen swap the position of the tools and the vector checkbox to keep it consistent with the other screens.

**Comment by Denz1994** [comment]
The panels on the right side of every screen have been consolidated into one panel. The sections of the panel are separated by thin hairlines as suggested by @ariel-phet. The version of the panels in [1.0.0.dev-23](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.33/masses-and-springs_en.html) are mockups and can be refined programmatically. However, I do want some input from @ariel-phet or @arouinfar before I refine the code.

Personal Take: 

- This removes a lot of the clutter.
- This makes managing the panels simpler in the code because everything regarding this panel is created in one place for each screen view.
- This is an overall improvement.

Notes on development:

- The current version of the gravity slider is currently being refined to match pendulum lab, but that doesn't change the idea of having one panel to house everything.
- This version of the panel follows this scheme. ``` parentPanel.children[ VBox.children[ panelContents.<Panel> ] ]``` . I'm sticking to this approach because it makes manipulating the parentPanel's contents more accessible for each screen view. Also, the panels are becoming more and more unique and abstraction is getting complex.

**Comment by Denz1994** [comment]
Sidebar: I have been referencing the wrong issue in commits so I have just updated the relevant issues. Continue as normal.

**Comment by ariel-phet** [comment]
@Denz1994 I think this is definitely an improvement, both visually and UX wise and agree with your comments above. 

I think I would still put the "tools" (the ruler and stop watch) in a separate floating panel. To me they are conceptually a bit different. And that way the basic division is "sim controls" and then "measuring tools" - that seems like a good conceptual division to me, and matches sims like projectile motion.

**Comment by Denz1994** [comment]
The idea of a separate tools panel would be great because alleviates changing the bounds of when a tool should be returned. In the current version, you can drop a tool over the options panel and the tool won't return if it isn't in the tool section.

**Comment by Denz1994** [comment]
The panels have been consolidated and the toolbox has been removed and placed in its own panel.
