### ISSUE TITLE
User suggestion: hang multiple masses from single spring

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/masses-and-springs#19]
I was working with the masses and springs lab and want to suggest the ability to hang more than one mass on the springs.
This could even be using a virtual slotted mass set.

**Comment by ariel-phet** [comment]
Kicking this over to @arouinfar. As long as we have the ability to have masses that are double, I am not sure what being able to hanging multiple masses buys us. It seems like an unnecessary complication. It seems we are better off having just a well thought out set of potential masses.

**Comment by arouinfar** [comment]
Currently we have a 250g mass, two 100g masses, and one 50g mass, so I think there are plenty of opportunities for meaningful comparisons. I generally agree with @ariel-phet here. I think hanging multiple masses would be more complicated that it's worth. The only potential benefit I see would be to increase the number of data points that could be added to a plot of F vs. x to find the spring constant. However, we could achieve that by adding another mass or two (and moving the unknowns to the lab screen only, if need be).

**Comment by ariel-phet** [comment]
@arouinfar the one other thing I could see is potentially having a "custom mass" that perhaps is controlled by a slider or discrete picker or such on the lab screen, so you could adjust is value to a few points.

**Comment by arouinfar** [comment]
Oh, I like that idea @ariel-phet! I'll mock up a version with the custom mass slider for our next meeting.

If we go down this route, I think we'll want to make sure the largest unknown mass is beyond the slider range. This would be similar to mystery materials in Bending Light -- one has an index of refraction within the range of the n-slider, and the other doesn't.

**Comment by arouinfar** [comment]
The current design includes a custom mass, so I believe we can go ahead and close this issue.
