### ISSUE TITLE
Dev version for interviews

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#190]
In a slack conversation @ariel-phet made said: 

> I would suggest having a decent dev test before interviews, however the QA team is fairly back logged currently. Once you fix that bug, I would say do about an hour of "self QA" (a good habit anyhow, and see if things seem stable (for instance just hammer away on Chrome). If generally everything is functional, smooth, and no obvious bugs, make a dev version, and I will also take a look. Then Amy can interview on something like chrome and know it is in pretty good shape

I will tag any new bugs that I find in this issue until a stable version of MAS is secured.

**Comment by arouinfar** [comment]
@Denz1994 thank you for this review! I'm in the process of reviewing of dev.38/master to see if there's anything that needs addressing before interviews. So far only #197 and #198 are critical to 
address before interviews, which will likely be Monday/Tuesday next week.

**Comment by Denz1994** [comment]
Posting a new dev version for review. Issues #136 and #194 are not priorities for the purposes of the interviews. Assigning to @arouinfar for review of this latest [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.40/phet/masses-and-springs_en_phet.html). Thanks for the feedback @arouinfar.

**Comment by arouinfar** [comment]
@Denz1994 Things are looking pretty good! I finished my review of the latest dev this afternoon, and have a few issues to open. None of them will need to be addressed before interviews, and are mostly pixel polishing. 

I'll reassign this to you in case you want to keep it open until the remaining tagged issues are addressed. Otherwise, feel free to close.
