### ISSUE TITLE
Play/Pause button expansion should be at button's center.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#195]
@ariel-phet mentioned when reviewing #190, that the play/pause button should not be shifting when it is clicked and should expand in reference to its center.

**Comment by phet-steele** [comment]
@Denz1994 I thought this was fixed in https://github.com/phetsims/masses-and-springs/issues/154?

**Comment by arouinfar** [comment]
@Denz1994 actually, I would prefer that the play button didn't expand at all. In some sims, the button expands to draw attention to itself, but there are several other cases where play and pause are the same size (such as Pendulum Lab, Rutherford Scattering, and Gravity and Orbits). 

Given the button's placement and general flow, I think that play and pause can be the same size. Currently, the size of the pause button looks good, so I would resize play to match.

**Comment by Denz1994** [comment]
@phet-steele  I was able to track down commit 52dc78d56e047e510e0235618c37409596ee1806 which may have altered the previous behavior. The change happened between [dev 24](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.24/masses-and-springs_en.html) and [dev 25](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.25/masses-and-springs_en.html). It was made to fix #134, but in doing so reverted the older buggy code. The button is now using a static size as suggested by @arouinfar.
