### ISSUE TITLE
Mass Equilibrium Text in panel

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#198]
The OneSpringView should be using the "Mass Equilibrium" text instead of the current "Equilibrium Position" text. The line that is being used is correctly representing the Mass Equilibrium, but the text is incorrect.

Discovered while reviewing #190.

**Comment by arouinfar** [comment]
@Denz1994 to be clear, Mass Equilibrium should be on Vectors, Energy, and Lab. Looks like the behavior is correct, but the string in the panel needs to be updated.
