### ISSUE TITLE
sim title?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/masses-and-springs#2]
The title for the HTML5 version is currently "Masses And Springs".  Capitalizing the "And" is inconsistent with titles of other PhET sims.  Words that are deemphasized ("and", "an", "a",...) are usually in lowercase. Eg:

Balloons and Static Electricity
Build an Atom
Forces and Motion: Basics
Molecules and Light
Reactants, Products and Leftovers
Resistance in a Wire

Also, the title for the Java version of this sim was "Masses & Springs".  I think "Masses and Spring" is more consistent with other titles. But I don't know if having a different title for Java and HTML5 versions has any repercussions for the website.

If the title is changed:
(1) the description of the GitHub repo needs to be manually edited
(2) the README.md file needs to be regenerated using `grunt unpublished-README`.

**Comment by arouinfar** [comment]
I prefer "Masses and Springs" since we haven't included ampersands in HTML5 sim titles, and I'd like to keep consistent with our modern conventions.

I also noticed that the Flash version of Masses & Springs is mass-spring-lab which isn't consistent with the convention of simulation-name.

When the sim goes lives, would it be possible to move the sim pages to /masses-and-springs and /legacy/masses-and-springs and redirect /mass-spring-lab to the HTML5 sim page?

**Comment by ariel-phet** [comment]
+1 to @arouinfar comments 

and yes, the redirects should be possible, and should be doen

**Comment by mattpen** [comment]
> If the title is changed:
> (1) the description of the GitHub repo needs to be manually edited
> (2) the README.md file needs to be regenerated using grunt unpublished-README.

These items are complete. 

> When the sim goes lives, would it be possible to move the sim pages to /masses-and-springs and /legacy/masses-and-springs and redirect /mass-spring-lab to the HTML5 sim page?

I'll leave the issue open to address this request.

**Comment by arouinfar** [comment]
Thanks, @mattpen!

On Feb 13, 2016 12:57 PM, Matt Pennington notifications@github.com wrote:

If the title is changed:
(1) the description of the GitHub repo needs to be manually edited
(2) the README.md file needs to be regenerated using grunt unpublished-README.

These items are complete.

When the sim goes lives, would it be possible to move the sim pages to /masses-and-springs and /legacy/masses-and-springs and redirect /mass-spring-lab to the HTML5 sim page?

I'll leave the issue open to address this request.

##

**Comment by jonathanolson** [comment]
> and yes, the redirects should be possible, and should be doen

It sounds like a **headache** to rename a production Flash sim to match a new HTML name, as this would touch most of our systems. This means:
1. Rename, patch and rebuild the original Flash simulation (hasn't been done for a while, 20+ hours expected to resolve versioning, could be more).
2. Patch everything statistics-related to be relative to the new name. Yotta will need to sum "masses-and-springs" and "mass-spring-lab", etc.
3. Patch everything in the website to combine/handle the specific change. Relates to metadata, URLs, etc.
4. Patch offline statistics and sim-info queries to handle the change
5. Additional redirections for everything that mentions mass-spring-lab.

**I don't want to be on the hook for potentially upwards of 200+ hours (not joking!) to handle this**.

Depending on how Aaron set up the handling for "legacy Java/Flash + new HTML", it may be possible to have legacy/mass-spring-lab AND masses-and-springs (the HTML), and see if we can hook them together.

So my recommendation is to pick one of the following:
1. Keep the old sim name. If it gets moved to legacy/mass-spring-lab, have a redirection from mass-spring-lab to the new HTML sim. Have @mattpen investigate and give estimate for amount of work to hook "legacy/mass-spring-lab" to "masses-and-springs". Remember in every statistics report to combine the two. Also presumably add redirections to other URLs that contained mass-spring-lab.
2. Rename the HTML sim to mass-spring-lab (I'm fine with keeping the title the same).

Assigning to @ariel-phet for initial feedback.

**Comment by arouinfar** [comment]
@jonathanolson I don't think 200+ hours of work is worth it.  

I'm fine with either option you've proposed, though I would rather keep the sim named "Masses and Springs" for continuity. I know it breaks convention, but I could live with Masses and Springs being housed in /mass-spring-lab if need be.

**Comment by ariel-phet** [comment]
@jonathanolson 

So it sounds like an easy solution would be to just publish the new sim as "masses-and-springs" , migrate the flash version to "legacy/mass-spring-lab" and redirect "/mass-spring-lab" to the "masses-and-springs" url. Is that correct? (the point being if people use the old url, they will see the new HTML5 sim)

We will **definitely NOT** rename the old flash version

**Comment by jonathanolson** [comment]
> So it sounds like an easy solution would be to just publish the new sim as "masses-and-springs" , migrate the flash version to "legacy/mass-spring-lab" and redirect "/mass-spring-lab" to the "masses-and-springs" url. Is that correct?

Yes, that was what I was suggesting.

Assigning to @mattpen for investigation of difficulty for migrating to /legacy/mass-spring-lab while leaving the new sim at /masses-and-springs.

**Comment by ariel-phet** [comment]
tagging as low priority since it will be awhile before the sim is fully developed, and changing the name of the github repo/HTML5 sim is pretty easy these days.

**Comment by mattpen** [comment]
Currently, the flash version of this sim is published as both /legacy/mass-spring-lab and /mass-spring-lab.  Today I added this sim to the routes /legacy/masses-and-springs and /masses-and springs as part of phetsims/website#659.  When the html5 MAS is published, it will be available at /mass-spring-lab and /masses-and springs, and the flash version will be available at /legacy/mass-spring-lab and /legacy/masses-and-springs.  Fortunately Aaron left an easy path to implement this change so there is no need to rename either sim.

**Comment by Denz1994** [comment]
Thanks for closing @mattpen.
