### ISSUE TITLE
Arrangement of bars in total energy bar.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#200]
@ariel-phet commented via Slack 01/24/17, 1:42 EST

> The current order from bottom to top is thermal, elastic, gravitational, kinetic.
> I would be curious to see, this order: kinetic, elastic, gravitational, thermal.

**Comment by Denz1994** [comment]
The original orientation was fitted to match the arrangement in pendulum lab, but [dev 41 ](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.41/phet/masses-and-springs_en_phet.html
)has been adjusted to follow the new suggestion mentioned above.

**Comment by Denz1994** [comment]
The original order of the total energy bar was done in accord with pendulum lab, but [dev 41](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.41/phet/masses-and-springs_en_phet.html) has the above suggestion implemented for review. Assigning to @ariel-phet for feedback.

**Comment by ariel-phet** [comment]
@arouinfar see what you think about dev 41. I think this is much easier to interpret than dev 40. Here is my reasoning

1. I like the thermal energy coming "off the top" - I think this gives the feeling that as it grows it is "shriking" the available amounts of mechanical energy, which feels natural to me.

2. Putting KE on the bottom feels like a more natural mapping to me, it is easir for me to interpret that as the motion

3. I also feel that the elastic energy now feels better mapped to the spring movement in the total stack

When I compare to dev.40, that one just feels more jumbled and tougher to interpret.

See what you think

**Comment by arouinfar** [comment]
Thanks for this suggestion @ariel-phet. Looks awesome! I think and the stacking order makes the graph far more interpretable and intuitive. I definitely think this is a change we should migrate over to PL the next time it's up for a maintenance release. I'll open an issue for that.
