### ISSUE TITLE
Masses are shaking

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#201]
I recorded this video from @kathy-phet laptop:

![export5](https://user-images.githubusercontent.com/679486/35403533-37f69bf6-01bd-11e8-9fb0-462b8701d9b9.gif)

**Comment by Denz1994** [comment]
Thanks for the issue @samreid. I'll investigate with @jonathanolson.

**Comment by Denz1994** [comment]
Closing and referring to #206
