### ISSUE TITLE
Incorrect displacement magnitude

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#202]
In reviewing #176 I noticed that the displacement arrow tip can become misaligned. The tip should align with base of the spring, since that's where its zero point is. 

The base of the displacement vector is correct. At more extreme displacements, the vector overshoots (left and right). For smaller displacements, the vector undershoots a bit (center).

<img width="717" alt="screen shot 2018-01-29 at 10 47 07 am" src="https://user-images.githubusercontent.com/8419308/35525500-e37b3ee2-04e1-11e8-915a-471e4f43f9e2.png">

@Denz1994 this would be good to address in time for Wednesday's interviews, if possible.

**Comment by Denz1994** [comment]
After investigating the previous dev versions, the above commit should patch the bug. Could you review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.43/phet/masses-and-springs_en_phet.html) @arouinfar to assure that this bug is corrected?

**Comment by arouinfar** [comment]
Looks great!! Thanks @Denz1994.
