### ISSUE TITLE
Should we shift equilibrium position?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#203]
The equilibrium position generally doesn't include the bit of the spring that attaches to the mass, so it would be more technically correct if we shifted the equilibrium position up to base of the final coil. We'd also need to shift the Natural Length too.

![image](https://user-images.githubusercontent.com/8419308/35526219-f522afe8-04e3-11e8-9c0a-227809aadd7d.png)

That said, the base of the spring is easier to see/measure, and what matters is measuring from a consistent point. I'm inclined to the leave the equilibrium position and natural length where they are, but make a note of it in the Teacher Tips. If we get a lot of teacher pushback, we could make the change later.

Tagging for design meeting to get input from others on the team.

**Comment by ariel-phet** [comment]
Hooke's Law uses the base of the spring as the measurement point. The "natural length" of the spring to me does not mean the "length of the coils" it means the natural "resting" length of the spring as a whole. I think if you look up the length of extension springs the overall length is often mentioned:

https://www.masterspring.com/wp-content/uploads/2015/07/extension_spring_dimensions.gif

I think using the end of the spring to measure is more natural and brings up less questions.

**Comment by arouinfar** [comment]
> The "natural length" of the spring to me does not mean the "length of the coils" it means the natural "resting" length of the spring as a whole.

Agreed @ariel-phet. Thanks for your input!

I think the equilibrium position and natural length should reference the same point, because they'll likely be used to facilitate displacement measurements. If the natural length sits at the end of the spring, then the equilibrium position should too.

I think it makes the most sense to leave the equilibrium position at the end of the spring, so I'll go ahead and close this issue.

Tagging @kathy-phet so she's in the loop.
