### ISSUE TITLE
Displacement Arrow on Energy and Lab Screen

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#204]
@arouinfar made a comment on slack 01/29/2018:

> If possible, it’d be nice to have a new dev version with the Displacement on the Energy and Lab screens for today’s interview (4:30 MT)

**Comment by Denz1994** [comment]
The dev version [1.0.0-dev.42](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.42/phet/masses-and-springs_en_phet.html
) includes the displacement vector on the Vector, Energy, and Lab Screen. The bug found in #202 is still present. I will continue working on #202 and will post a new dev version when ready.

Assigning to @arouinfar to close this issue.

**Comment by arouinfar** [comment]
👍
