### ISSUE TITLE
Pixel polishing

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#205]
@Denz1994 here are some suggested pixel polishes. Please let me know if you have any questions, or if you would prefer to discuss over Zoom.

**Font Size**
(Anything not mentioned here is good as-is.)
- [x] Slider/panel titles, checkboxes, radio buttons, and value readouts (e.g. '100 g') = 14 pt
- [x] Combobox, slider min/max = 12 pt

**Padding**
- [x] Accordion box open/close button -- shift down 2 px 
- [x] Increase padding between checkboxes in `ReferenceLinePanel` (first 3 checkboxes) to match padding between checkboxes in the Vectors section.
- [x] Mass & Gravity sliders: increase padding between min/max value and slider track to be more on par with Spring Constant and Damping sliders. 
<img src="https://user-images.githubusercontent.com/8419308/35536475-45c13666-0504-11e8-80a0-136ff7c8d6ec.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/35536464-3ddb0652-0504-11e8-8aa5-a0b9cab193e0.png" width=300>
- [x] Gravity combobox: increase height 3 px so string has a bit more padding

**Alignment**
- [x] Right-align icons with gravity tweakers
- [x] Right-align mass & gravity readout with right tweaker
- [x] Left-align "Gravity" and "Damping" with checkboxes
- [x] Center-align scene selection icons with panel
- [x] Velocity and acceleration vectors should be equidistant from spring attachment point. Slight misalignment is most obvious on 50g mass.
![image](https://user-images.githubusercontent.com/8419308/35594771-93073222-05d1-11e8-81b0-5dac34acefd3.png)
- [x] Indent Gravity and Spring so that checkbox is left-aligned with "Forces" 

**Misc**
- [x] Change 'Constant' to 'Constant Parameter'
- [x] Make 'Gravity' and 'Damping' slider titles bold 
- [x] Increasing font sizes will likely make panels a bit tight, so slightly increase size of standalone (e.g. mass) panels to compensate.

**Comment by Denz1994** [comment]
If @arouinfar doesn't see any more revisions in this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.75/phet/masses-and-springs_en_phet.html), then I am leaving it to you to close. Thanks for the input!

**Comment by arouinfar** [comment]
Looking good @Denz1994! It's getting close, but I found a few more pixels to polish 😄 
- [x] Constant Parameter, Spring Constant, Length: increase to 12 pt
- [x] Gravity & Damping sliders: titles bold (Leave "Damping = 0" as is.)
- [x] Mass slider: Increase "Mass" and value readout to 14 pt
- [x] Mass & Gravity sliders: Thumb is still too close to min/max readouts, so move min/max values up a px. (Perhaps this can be done by making the min/max tick marks a bit taller?)
![image](https://user-images.githubusercontent.com/8419308/36502058-003873fc-1706-11e8-84ef-18ad86cf65d8.png) ![image](https://user-images.githubusercontent.com/8419308/36502085-0a26dbce-1706-11e8-850d-669b893b129c.png)

**Comment by Denz1994** [comment]
The above changes have been implemented. The font of the mass and readout was already 14. I don't know if this is a change that was made in another commit. Could you try this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.81/phet/masses-and-springs_en_phet.html) @arouinfar. Thanks.

**Comment by arouinfar** [comment]
Looks great @Denz1994! Two more requests:
- [x] Mass sliders: Bold "Mass" -- the title gets a bit lost
- [x] Constant Parameter: Left-align with "Short" (shift radio options over with title)

**Comment by Denz1994** [comment]
The above changes were applied in this [dev version.](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.83/phet/masses-and-springs_en_phet.html) Leaving to @arouinfar to close.

**Comment by arouinfar** [comment]
👍
