### ISSUE TITLE
Shaking masses

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#206]
This problem appears to occur on multiple platforms. It is obvious on my Win 7 desktop on latest FF. It does not appear to be happening much on Win 7 chrome or IE (but maybe ever so slightly). It is obvious happening on my Win 10 laptop on chrome and firefox. The below recording is from Win 10 chrome. The easiest way to reproduce is just to pick up one mass and move it around, as the mass is moved, the other masses will "shake" on the shelf

![recording 4](https://user-images.githubusercontent.com/4051174/35539458-de1b160c-050e-11e8-8eb7-b3748ee97a23.gif)

I imagine @jonathanolson will have some insight as to what is causing this behavior. It seems the other masses are being redrawn unecessarily

**Comment by ariel-phet** [comment]
Labeling high priority since this bug will block publication

**Comment by jonathanolson** [comment]
I believe the above commit should fix this, can you verify?

**Comment by ariel-phet** [comment]
Appears fixed on master. Closing
