### ISSUE TITLE
Increase range of Movable Line

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#207]
The range of the Movable Line is a bit too restrictive. Here's the current min/max:
<img width="268" alt="screen shot 2018-01-30 at 10 27 21 am" src="https://user-images.githubusercontent.com/8419308/35581202-5ab3803e-05a8-11e8-9569-9b885807c64c.png"> <img width="268" alt="screen shot 2018-01-30 at 10 27 31 am" src="https://user-images.githubusercontent.com/8419308/35581203-5ad06596-05a8-11e8-8f83-bfc68af4afd3.png">

I think a more productive range would be something like this, where the the line could move up an additional 20px to measure a compressed short spring, or all the way down to the level of the shelf.
![image](https://user-images.githubusercontent.com/8419308/35592382-0e15d46c-05ca-11e8-933f-37b9632fd990.png)

**Comment by Denz1994** [comment]
Good suggestion. This [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.50/phet/masses-and-springs_en_phet.html) includes that above suggestion. How do you think the red movable line looks against the blue 'height = zero' line on the energy and lab screen?

**Comment by arouinfar** [comment]
The updated range is great @Denz1994! The dashes of the movable line and GPE reference line are offset from one another, similar to the Mass Equilibrium. Can you increase the range of the movable line so that  it can align with GPE reference line? You'll also need to move the "Height = 0 m" string over a few pixels to the right to avoid occlusion.

<img src="https://user-images.githubusercontent.com/8419308/35656697-f648249c-06b5-11e8-961a-00ccce4702e8.png"><img src="https://user-images.githubusercontent.com/8419308/35656706-065a4b6c-06b6-11e8-99bd-2852aba9f57a.png">

**Comment by Denz1994** [comment]
@arouinfar what do you think about this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.53/phet/masses-and-springs_en_phet.html
)?  If this checks out, I'll leave up to you to close this issue.

**Comment by arouinfar** [comment]
Looks great @Denz1994. Thanks!
