### ISSUE TITLE
Movable Line unusable on single-spring screens

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#208]
Observed on latest Mac/Chrome.

Steps to reproduce:
* On startup, go to Energy or Lab
* Turn on Movable Line, and it appears where it should
![image](https://user-images.githubusercontent.com/8419308/35592591-bbf5b96c-05ca-11e8-9625-97019a2e7f8a.png)
* Drag movable line, and it gets shifted to the far-left side of the screen
![image](https://user-images.githubusercontent.com/8419308/35592605-c76f44fc-05ca-11e8-8e4b-70ba3479f5ca.png)

To return the Movable Line
* Resize browser
* Browser refresh (Reset All doesn't return line)

This behavior isn't present on the Intro or Vectors screens, which have two springs

**Comment by Denz1994** [comment]
This behavior was corrected in the above commit. There was a translation on the position property that had an incorrect origin.
