### ISSUE TITLE
Equilibrium lines inconsistently layered

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#209]
I've noticed that the Equilibrium Position and Mass Equilibrium lines are inconsistently layered.

![image](https://user-images.githubusercontent.com/8419308/35595687-c6dd8828-05d4-11e8-896c-b7c1a5fe37f4.png)
(On Intro, the spring was compressed to demonstrate layering.)

I prefer the layering on Energy/Lab because it doesn't occlude the mass. @Denz1994 can you update the Intro and Vectors screens to match?

**Comment by Denz1994** [comment]
This layout issue has been corrected and is fixed in the latest [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.51/phet/masses-and-springs_en_phet.html).
