### ISSUE TITLE
remove usages of Property.preventGetSet

### ISSUE THREAD

**Issue by jbphet** [phetsims/masses-and-springs#21]
As part of working on #18 we used `Property.preventGetSet` to detect unconverted usages of properties.  We will leave this in for a while, but in the interest of clean code, they should be removed prior to publication.  This GitHub issue is being logged to remind us to do this.  It will remain unassigned until we get closer to publishing this sim.

**Comment by Denz1994** [comment]
This was handled a while removing the usages of propertySet. There are no more use cases of property.preventGetSet in the code base.
