### ISSUE TITLE
Consider having mass "jump" to pointer if clicking on oscillating spring

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#210]
@Denz1994 @arouinfar 

As I am playing with the latest version of masses and springs (which is looking really nice by the way), I was thinking about a way to improve the UX. It seems "snagging" a mass can be a bit tricky when the mass is oscillating (yes I can press stop, but if feel natural to want to grab the mass).

Perhaps we could make it such that if the mass is attached to the spring, if you click anywhere on the mass or on the spring, the mass "jumps" to your pointer (mouse or finger). I feel like that might make the interaction more seamless. Maybe @jonathanolson will have some clever thoughts on how to do that nicely. I think for most users, it will just feel like they are clicking on the mass (since that is what they will be aiming for). Thoughts?

**Comment by arouinfar** [comment]
@ariel-phet I love this idea! I think this change would be super helpful. Students definitely click on the mass to try and grab it, though eventually switch over to using the stop button. However, I think jumping the mass to their cursor/finger would be better UX.

**Comment by jonathanolson** [comment]
It would also be technically possible (and might be useful in sims like this or Pendulum Lab) to start a drag if the mass moves over a pressed mouse/finger. For example, if the user presses a mouse down (and misses the mass barely), when the mass moves over the mouse location it could start a drag.

It would also definitely work to be able to click on the spring (where the mass would jump to that location), but that would miss the case where they pressed the mouse down below the mass (while it is oscillating).

**Comment by arouinfar** [comment]
Based on the discussion last design meeting, I'm going to mark this issue as deferred and unassign @Denz1994.

The root issue is that the oscillations themselves are a bit too fast, so we've decided to reduce the k values, instead. If the oscillations are still too fast, we may consider this solution.

> It would also definitely work to be able to click on the spring (where the mass would jump to that location), but that would miss the case where they pressed the mouse down below the mass (while it is oscillating).

For the record, we were fine with missing the cases where the click occurs below the mass.

**Comment by ariel-phet** [comment]
It seems that with the newly tuned oscillations periods and the suggestions in #257, this is no longer needed. Closing
