### ISSUE TITLE
Reduce spring constants

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#215]
Overall, the oscillations are a bit fast (even in slow motion) which partly motivated the change requested in #210. During the last design meeting, we decided to tweak the spring constants so that the oscillations would be a bit slower.

@Denz1994 I think one tick mark above "Small" is probably large enough to become the new "Large".

**Comment by Denz1994** [comment]
The spring constant range has been lowered with the above suggestion. Try it out in this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.56/phet/masses-and-springs_en_phet.html) and @arouinfar can close if acceptable.

**Comment by ariel-phet** [comment]
@Denz1994 @arouinfar overall I think this current range is much better. The default is moving at a very reasonable pace for most masses.

My one suggestion might be to tweak the range a bit for one type of fun challenge question. I think a natural question might be..."Can you get the 100 g and 50 g mass to oscillate at the same frequency?"

Currently the range is not quite enough. Even with the spring constant set minimum on the 50 g mass and maximum on the 100 g mass, the 50 g mass still outpaces the 100 g mass. 

Just a thought

**Comment by arouinfar** [comment]
Thanks for your input @ariel-phet! I agree that the oscillation speed is much easier to observe.

I would also like to see the maximum spring constant increased a bit, as it would support @ariel-phet's teaching example. 

It would also be nice if the 250g mass's equilibrium position at max gravity and max k could be within dev. Currently, it's impossible to retrieve the 250 g mass at max gravity by increasing k. If this would require k to be increased too much, then perhaps we could instead choose a max k that would allow the 250g mass on Jupiter to have an equilibrium position within dev.

**Comment by Denz1994** [comment]
I was to reproduce the question posed above by @ariel-phet regarding a 50g and 100g mass and keep the 250g within the dev bounds at max gravity. Can you review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.69/phet/masses-and-springs_en_phet.html) to ensure the oscillation isn't too fast?

**Comment by arouinfar** [comment]
@Denz1994 confirmed that the current range of k is 5-10 N/m. I think that range is a bit too small, as it only allows k to be doubled. I think it would be better to allow k to be quadrupled, so users could more easily observe the square root relationship between k and the period.

Locally, I experimented with a k range of 3-12 N/m, which looked nice. However, this range doesn't nicely divide into 11 tick marks. Ten tick marks would allow for 1 N/m step size, but we'd need to ditch the major tick mark in the middle of the slider track:
![image](https://user-images.githubusercontent.com/8419308/36521455-179793ae-1754-11e8-98d6-63a39eb01bc4.png)

@Denz1994 I recommend you:
* Change the range of `DAMPING_RANGE_PROPERTY` to 3-12 N/m, with a default at 6 N/m.
* Change the total number of tick marks to 10
* Snap the thumb to the tick marks

**Comment by Denz1994** [comment]
The range has been updated along with the tick marks in this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.78/phet/masses-and-springs_en_phet.html). Leaving to @arouinfar to close.

**Comment by arouinfar** [comment]
Looks great, thanks @Denz1994!
