### ISSUE TITLE
Reduce damping range

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#216]
In design meeting, we discussed reducing the overall damping because it feels a bit too harsh. The current midpoint looks about right to be the max damping.

Desired behavior
* When damping is small, the amplitude decay shouldn't be obvious until the spring has gone through a few oscillations.
* Critical damping should be observable for at least some range of masses. (Currently critical damping isn't observable at the midpoint, but reducing k in #215 will hopefully take care of this.)

**Comment by Denz1994** [comment]
Damping range has been reduced using the above suggestion from @arouinfar. Please review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.55/phet/masses-and-springs_en_phet.html) for the change.

**Comment by arouinfar** [comment]
It's looking a better @Denz1994!

A few suggestions...
* At max damping, the 50 g mass is still a bit underdamped. Can you increase it a bit so critical damping can be observed?
* At min (non-zero) damping, the amplitude decay is still pretty obvious early on. Can you decrease it slightly? I realize the amplitude decays exponentially, so this may not be something you can accommodate, but I think it's worth a try.

**Comment by Denz1994** [comment]
I increased the range of the damping to accommodate for critical damping at 50g and max damping value. Also, I decreased the steps in the damping slider so we can snap to smaller min (non-zero) values. 

In a [previous dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.66/phet/masses-and-springs_en_phet.html) it would take longer to stop oscillating (specifically 40 seconds using a 20 cm displacement and 100g mass). Now it takes about 61 seconds. I am considering a "stopped oscillation" when the spring stopper button is disabled.

Could you review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.68/phet/masses-and-springs_en_phet.html
) @arouinfar?

**Comment by arouinfar** [comment]
I think the new range is looking much better! However, I'm finding it a bit hard to reproduce experiments with so many available positions for the thumb. In general, I like the half steps, but perhaps we could reduce the total number of tick marks (while keeping the range the same) as a compromise. 

@Denz1994 can you reduce the number of tick marks from 11 to 7, while keeping the half steps and same overall range?

**Comment by Denz1994** [comment]
The slider tick marks have been reduced and the steps are still in half increments. Could you review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.79/phet/masses-and-springs_en_phet.html) @arouinfar?

**Comment by arouinfar** [comment]
👍
