### ISSUE TITLE
Add "Damping = 0" to Intro and Vectors

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#217]
In interviews, students expected some amount of damping to be present. In #145 we had discussed the possibility of a damping checkbox or readout to emphasize that there isn't any damping on the Intro and Vectors screens.

We ultimately decided against a damping checkbox because
* If we allow damping on Vectors, we would need to show the damping force which is beyond the scope of the learning goals
* Including damping on Intro, but not Vectors, would be a strange flow.

However, it seems that adding "Damping = 0" below the Gravity controls on Intro and Vectors would be useful, after all.

**Comment by Denz1994** [comment]
A text that reads "Damping = 0" was added beneath the gravity combo box. It can be reviewed in this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.55/phet/masses-and-springs_en_phet.htm).

**Comment by arouinfar** [comment]
@Denz1994 a few tweaks: 
* Increase padding between Gravity slider and "Damping = 0" by a few px
* Left-align with checkboxes

**Comment by Denz1994** [comment]
Check this latest [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.77/phet/masses-and-springs_en_phet.html) @arouinfar for the above improvements.

**Comment by arouinfar** [comment]
Thanks @Denz1994! Looks good.
