### ISSUE TITLE
Shorten spring attachment point?

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#219]
In #203 we decided against shifting the equilibrium position, but @kathy-phet and I had wondered if it was possible to shorten the bit of wire extending from the end of the coil by a few px, as a sort of compromise.

@Denz1994 if this would be a quick and noninvasive change (e.g. displacement, mass equilibrium won't need to be adjusted) can you shorten the wire a few px? If not, please feel free to close.

**Comment by Denz1994** [comment]
Could @arouinfar review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.58/phet/masses-and-springs_en_phet.html) for the change?

**Comment by arouinfar** [comment]
Looks great, thanks @Denz1994!
