### ISSUE TITLE
Scene selection button cleanup

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#220]
Currently, the scene selection buttons appear to be screenshots of the default springs. 
![image](https://user-images.githubusercontent.com/8419308/35835516-624e11b6-0a98-11e8-874a-d7e7c3cfb868.png)

Generally, the scene selection button are a bit more iconic. For example, the scene selection buttons in Hooke's Law
<img src="https://user-images.githubusercontent.com/8419308/35833705-7848e12a-0a8f-11e8-811d-39f3452dae7c.png" width=200><img src="https://user-images.githubusercontent.com/8419308/35833713-809df57c-0a8f-11e8-8cde-b4501a3dfc58.png" width=200>.

@Denz1994 I'd like to make the scene selection buttons a bit more Hooke's Law-like, in color and style. The Hooke's Law icons were generated in code, and [HookesLawIconFactory.js](https://github.com/phetsims/hookes-law/blob/master/js/common/view/HookesLawIconFactory.js) may be helpful.

Here's a rough mockup of the scene selection buttons (the longer spring should have 6 uninterrupted coils).

![image](https://user-images.githubusercontent.com/8419308/35833949-a1684928-0a90-11e8-8575-b71d39ba6940.png)

**Comment by Denz1994** [comment]
I believe the outside border is a bit too thick, but just for clarity is this the direction we want to go in @arouinfar? I had to darken the springs in the icon a bit. The blue color was pulled from the image above as well. 

Can you check this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.55/phet/masses-and-springs_en_phet.htm)?

**Comment by Denz1994** [comment]
Can you review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.73/phet/masses-and-springs_en_phet.html) @arouinfar to check if the scene buttons are okay?

**Comment by arouinfar** [comment]
Getting closer @Denz1994! I think the icons are looking great, but I have a few tweaks to suggest:
- [x] Remove the yellow stroke (contrasts poorly against white) 
- [x] Use single black stroke which is heavier for the active selection (e.g. 2 pt on active, 1 pt on inactive)
- [x] There's a lot of blank space below the springs, so change aspect ratio of buttons to get rid of excess padding.  Square buttons would work nicely.
- [x] Center the scene selection group below the toolbox.

![image](https://user-images.githubusercontent.com/8419308/36493861-cbdc3426-16ed-11e8-9eca-57c017e84505.png)

(Please ignore the inconsistency in the background color of the inactive scene. It's a side effect of reducing the opacity of the screenshot in Illustrator.)

**Comment by Denz1994** [comment]
What do you think about this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.76/phet/masses-and-springs_en_phet.html) @arouinfar?

**Comment by arouinfar** [comment]
Love it @Denz1994!!
