### ISSUE TITLE
Ruler shrunk

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#224]
The ruler is quite a bit smaller than it used to be. The change appears to have occurred between dev.54 and dev.55. Can you look into it @Denz1994?

![image](https://user-images.githubusercontent.com/8419308/35987796-f11698aa-0cb9-11e8-8832-47f0fb46e497.png)  ![image](https://user-images.githubusercontent.com/8419308/35987751-d397db4a-0cb9-11e8-8d1d-6d42184b5ff5.png)

**Comment by Denz1994** [comment]
Slack discussion on this between @arouinfar and myself:


Me: February, 8 2018 12:33 PM

> Hey Amy, I just saw the issue you opened regarding the ruler shrinking. I was comparing the model values to the ruler length and I believe it was too long in the previous versions. It wasn’t measuring a meter in model space and was a bit longer  than it should of been. I’m using the length of the springs as a measurement.

@arouinfar: February, 8 2018 12:33 PM

> Ooooh, thanks. Makes sense!

Me:  February, 8 2018 12:42 PM

> I opened an issue for this and closed it relatively quickly. I will update the issue to be more explicit for the change. Thanks for the notice though.

With that mentioned, I will close this issue and reference #222.
