### ISSUE TITLE
Gravity tweaker step size should be 0.1 m/s^2

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#225]
I've noticed that the Gravity slider thumb snaps to steps of 1.0 m/s^2 (similar to the PL mass & length sliders) which is great. However, the tweakers seem to be following the same step size, which means users can't access all possible values. 

@Denz1994 can you update the step size to 0.1 m/s^2?

**Comment by Denz1994** [comment]
Great notice @arouinfar I will update this.

**Comment by Denz1994** [comment]
The step has been updated to 0.1 m/s in this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.63/phet/masses-and-springs_en_phet.html). Closing this issue.
