### ISSUE TITLE
branch: portedGraph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/masses-and-springs#228]
Identified by `print-branches.sh`.  @Denz1994 please describe. 

FYI, all non-release branches are supposed to have an associated GitHub issue. Title is of the form "branch: {{branchName}}}". The description should include: the purpose of the branch, expected lifetime of the branch, references to any related issues. The issue can be closed when the branch is deleted.

**Comment by chrisklus** [comment]
this branch should be re-deleted as part of https://github.com/phetsims/special-ops/issues/198
