### ISSUE TITLE
Natural Length observable on all screens

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#229]
In dev.65, the Natural Length is observable on Screens 2-4, but should only be on Intro. As a side note, toggling the checkbox on Intro does not change the visibility on the other screens.

For example, here's the Energy screen:
![image](https://user-images.githubusercontent.com/8419308/36235003-5d12f102-11ab-11e8-89a1-2f89c8dac170.png)

**Comment by Denz1994** [comment]
Sorry @arouinfar, I should have made an issue for this earlier. In a slack meeting on 02/13/18 @ariel-phet mentioned, that it would be good to have the natural length line visible on every screen. The main reason being that it would make it more clear that the displacement vector extends from the natural resting length of the spring.

I've added the toggle checkbox to every screen as well. Assigning to @ariel-phet and @arouinfar for review of this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.67/phet/masses-and-springs_en_phet.html).

**Comment by arouinfar** [comment]
Thanks for the clarification @Denz1994! I spoke with @ariel-phet about the issue this morning, and we decided that the natural length's visibility should be tied to the Displacement.  If the Natural Length is independent of displacement, students may measure the distance between the natural length and the mass equilibrium, which would not be productive, as the reference points are different. One option would be for Natural Length to be sub-check beneath Displacement, but I think it's better for Natural Length to always be on when Displacement is on. 

We decided that a single checkbox should control both the Natural Length and the Displacement. Here's a mockup with the addition of the `BracketNode` from scenery.
![image](https://user-images.githubusercontent.com/8419308/36288088-3a59c534-1276-11e8-8b08-30a4b03ce726.png)


A similar example would be the component forces in Atomic Interactions:
![image](https://user-images.githubusercontent.com/8419308/36287969-8fc23a5c-1275-11e8-8b29-530d581219da.png)

**Comment by Denz1994** [comment]
Woah, I like it. Will work on this and update.

**Comment by Denz1994** [comment]
What do you think about this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.71/phet/masses-and-springs_en_phet.html) @arouinfar? The natural length and displacement arrow have been coupled and the bracket has been added. I think this is a great improvement.

**Comment by arouinfar** [comment]
Looks great @Denz1994! 

The bracket might look better as the third checkbox, but flow wise, I think it's important to leave at the top. It's also the only checkbox that has any physical meaning for an empty spring. 

I reviewed this with @kathy-phet, and she pointed out that the Mass Equilibrium doesn't make much sense without a mass, and could actually be confused for the natural length. It would be better to show nothing for an empty spring, so I'll open a separate issue.
