### ISSUE TITLE
branch: alternative-falling

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#230]
Purpose: Branch was created to provide an alternative animation for a mass that has been dropped and then animated back to its original position on the mass shelf.

Expected Lifetime: Short-term. The use of this branch was only used for about a week. It can be deleted after a decision was made in #133.

Relevant Issues: #133, #226

**Comment by chrisklus** [comment]
this branch should be re-deleted as part of https://github.com/phetsims/special-ops/issues/198

**Comment by chrisklus** [comment]
branch re-deleted, closing
