### ISSUE TITLE
branch: mipmap-ruler

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#231]
Purpose: This branch was created to compare the initialization of the draggable ruler node in the tool box using an icon.

Expected Lifetime: Short-term. The use of this branch was only used for about a week. It can be deleted after a decision was made in #199.

Relevant Issues: #199, #227

**Comment by chrisklus** [comment]
this branch should be re-deleted as part of https://github.com/phetsims/special-ops/issues/198
