### ISSUE TITLE
branch: portedGraph

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#232]
Purpose: Branch was created to provide an alternative animation for a mass that has been dropped and then animated back to its original position on the mass shelf.

Expected Lifetime: Short-term. The use of this branch was used to merge relevant changes from the Masses and Springs ```EnergyGraphNode.js``` into a common code component consisting of ```BarChartNode.js``` and ```BarNode.js``` in Griddle. This can be closed when the merging of the common code elements is completed.

Relevant Issues:  #228

**Comment by chrisklus** [comment]
this branch should be re-deleted as part of https://github.com/phetsims/special-ops/issues/198

**Comment by chrisklus** [comment]
branch re-deleted, closing
