### ISSUE TITLE
Hide Mass Equilibrium for empty springs

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#233]
In reviewing #229  @kathy-phet pointed out that the Mass Equilibrium doesn't make much sense without a mass, and could actually be confused for the natural length. It would be better to show nothing for an empty spring. 

@Denz1994 can you hide the Mass Equilibrium when the springs are empty? No need to disable the checkbox, just hide the black dashed line in the play area.

**Comment by Denz1994** [comment]
Good input. Try out this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.72/phet/masses-and-springs_en_phet.html
) @arouinfar and if it looks good, close.

**Comment by arouinfar** [comment]
👍
