### ISSUE TITLE
Period trace for mass oscillation.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#235]
In a zoom meeting, @ariel-phet suggested having a period trace similar to the one in pendulum lab. He mentioned that there was interest in having one by a teacher and both sims are similar in demonstrating oscillation. Here are some key takeaways:

- A vertical rectangular path that follows the COM of the oscillating mass.
- Only on Lab Screen
-  Positioning should be in line with mass equilibrium line 
- 4hr maximum of labor otherwise check in with AP

Here is a mock up:

![image](https://user-images.githubusercontent.com/13894380/36563455-20abd506-17e8-11e8-8b68-b9de45cd0df9.png)

Assigning to @ariel-phet and @arouinfar for any further input. Otherwise, unassign yourself and I will work on a prototype and report back.

**Comment by ariel-phet** [comment]
I think you captured my thoughts well, removing my assignment for the moment

**Comment by arouinfar** [comment]
@ariel-phet and I discussed this briefly last week, and I think it'd be a good addition. The general idea and mockup looks good to me @Denz1994.

**Comment by arouinfar** [comment]
@Denz1994 to clarify -- the period trace should have a "Period Trace" checkbox located below "Movable Line". By default, the checkbox will be turned off.

**Comment by Denz1994** [comment]
The period trace is in a stable condition. There is one consideration that I found. If we have minor oscillations the trace starts to look like a straight line until the mass stops oscillating. I don't think we want this behavior, but I wanted to get it reviewed in case someone may find it useful. 

@ariel-phet  and @arouinfar Review this [dev version ](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.92/phet/masses-and-springs_en_phet.html)for the trace behavior along with the checkbox.

**Comment by Denz1994** [comment]
@ariel-phet  mentioned: Thickness of the trace should be a bit thinner. Also, the color selection could use some work.

**Comment by Denz1994** [comment]
A new [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.93/phet/masses-and-springs_en_phet.html) with a thinner line and contracted xOffset for the period trace has been pushed for review @arouinfar. 

@ariel-phet Mentioned: 

> "Color selection is up to Amy. I would be fine with black."

**Comment by arouinfar** [comment]
Looks nice @Denz1994! I definitely prefer the thinner period trace. Generally, I like the behavior, but here are few suggestions for improvements:
- [x] Move period trace 25px closer to the mass. Currently, it feels really far away, and I think that being in closer proximity to the mass would make the trace more interpretable.
- [x] Change color to black (sim already has plenty of color elsewhere)
- [x] The fade should be responsive to play/pause, see https://github.com/phetsims/pendulum-lab/issues/96

**Comment by Denz1994** [comment]
Changes should be implemented on master @arouinfar.

**Comment by arouinfar** [comment]
Looks great @Denz1994!

**Comment by phet-steele** [comment]
> There is one consideration that I found. If we have minor oscillations the trace starts to look like a straight line until the mass stops oscillating. I don't think we want this behavior, but I wanted to get it reviewed in case someone may find it useful.

I see no response to this behaviour in a comment. Is the "practically a horizontal line" behaviour okay? I was going to raise a similar question.

**Comment by arouinfar** [comment]
Yikes, looks like I missed that comment @phet-steele. 

I don't think the period trace is very useful when it gets smaller than this:
<img width="151" alt="screen shot 2018-05-22 at 12 34 30 pm" src="https://user-images.githubusercontent.com/8419308/40382905-bcf4a7de-5dbc-11e8-99d1-f18caad85de7.png">

When the oscillation is really small, the trace looks pretty ugly and could be confusing to students.
<img width="151" alt="screen shot 2018-05-22 at 12 34 59 pm" src="https://user-images.githubusercontent.com/8419308/40382903-bce0f5f4-5dbc-11e8-9876-c2a94be6256c.png">

@Denz1994 is it possible to suppress the Period Trace when the displacement is sufficiently small?

**Comment by Denz1994** [comment]
Agreed. Work in progress.

**Comment by Denz1994** [comment]
@arouinfar This [dev version](https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.106/phet/masses-and-springs_en_phet.html) has the update behavior. Some notes about this behavior: The trace is hidden from view and doesn't fade once it goes below a certain threshold. 

There are three main reasons for this. One, the fading behavior would continue to show the "ugly" trace that we are trying to hide (especially at higher damping values). Two, the logic would be more complex because we can step through the model using the step forward button and fading is disabled when paused (see issue #269). Three, the code is a lot simpler with the current solution and more readable then what I prototyped for a fade behavior.

Some implementation details: There is a threshold that is based on velocity. Once the mass goes below a certain velocity the trace is hidden from view.

**Comment by arouinfar** [comment]
Thanks @Denz1994. I didn't immediately love the new behavior, but I do think it's an improvement. I'm still tinkering a bit to figure out what recommendations to make to improve the behavior a bit more.

**Comment by Denz1994** [comment]
I pushed a new [dev version ](https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-dev.108/phet/masses-and-springs_en_phet.html)with the threshold removed from the period trace, as per our meeting with @DianaTavares and @arouinfar. Can you confirm this is the correct behavior @arouinfar?

**Comment by arouinfar** [comment]
Looks good to me @Denz1994, thanks.

We ultimately decided to let the period trace die down, even if a bit unsightly at the end, for a few reasons.
* Thinking about the use case in context, the small period trace makes sense as the amplitude dies down, and is unlikely to cause confusion.
* The threshold had some strange side effects. The disappearing trace was abrupt and sometimes aborted mid-trace. I think this would be harder for students to understand, and is more likely to look buggy.
