### ISSUE TITLE
branch: periodTrace

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#236]
Purpose: Branch was created to provide an added feature to the lab screen. This feature is a period trace that tracks the oscillation of the mass in a similar fashion to pendulum lab. 

Expected Lifetime: Short-term. @ariel-phet Mentioned that this feature is a last minute addition that is worth investigating within a short timeframe. It was expected that I would work on this for 4 hours and a decision will be made about whether it is worth continuing. At the time of this issue creation, only 1 hour and 30 minutes have been dedicated to #235.

Relevant Issues: #235

**Comment by jonathanolson** [comment]
Looks like it was merged into master, can the branch be removed now?

**Comment by Denz1994** [comment]
Yes. Due to the merging of this branch into master, I am closing this issue.

**Comment by chrisklus** [comment]
this branch should be re-deleted as part of https://github.com/phetsims/special-ops/issues/198

**Comment by chrisklus** [comment]
branch re-deleted, closing
