### ISSUE TITLE
Gravity panel contents shift when selecting mystery planet

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#238]
I am only seeing this in the Lab screen.

Changing back and forth between "Planet X" and anything else causes the contents of that panel to shift  (expand and shrink).

![mas10](https://user-images.githubusercontent.com/5863899/36755010-0611d5f4-1bc8-11e8-85ab-e1d067579385.gif)

Seen on macOS 10.13.3 Chrome. For phetsims/QA/issues/103.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.81/phet/masses-and-springs_en_phet.html
Version: 1.0.0-dev.81 2018-02-27 19:48:17 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"6ea6b964","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"4ae76b30","branch":"master"},"dot":{"sha":"8d471f40","branch":"master"},"griddle":{"sha":"9028614b","branch":"master"},"joist":{"sha":"40c4ae27","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"masses-and-springs":{"sha":"18511604","branch":"master"},"phet-core":{"sha":"f35ff65e","branch":"master"},"phet-io":{"sha":"3cecc850","branch":"master"},"phet-io-website":{"sha":"6e54fcc2","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"master"},"phet-io-wrapper-sonification":{"sha":"7d51caa9","branch":"master"},"phet-io-wrappers":{"sha":"290b6892","branch":"master"},"phetcommon":{"sha":"9c8018af","branch":"master"},"query-string-machine":{"sha":"485e174e","branch":"master"},"scenery":{"sha":"6b844c44","branch":"master"},"scenery-phet":{"sha":"e95210c0","branch":"master"},"sherpa":{"sha":"01058f19","branch":"master"},"sun":{"sha":"962fa366","branch":"master"},"tandem":{"sha":"5c68df6a","branch":"master"},"twixt":{"sha":"3f2cc19d","branch":"master"}}
</details>

**Comment by Denz1994** [comment]
After reviewing this the panel's logic, I found an easier way of dealing with this questionTextNode for planetX. We can just make the questionNode's local bounds equal the hSlider/numberControl local bounds. That way we don't have to manually adjust them. 

Can you check if this was fixed in master @phet-steele?

I will be releasing a new dev version because there have been some significant changes and bug fixes.

**Comment by phet-steele** [comment]
@Denz1994 this works great in English, but breaks in i18n. Neither of these were broken in dev.81:

`?stringTest=double`:

<img width="333" alt="screen shot 2018-03-02 at 11 53 14 am" src="https://user-images.githubusercontent.com/5863899/36916156-56dd90a0-1e10-11e8-9d28-4d41dca26b1a.png">

`?stringTest=i` (short strings):

<img width="314" alt="screen shot 2018-03-02 at 11 53 02 am" src="https://user-images.githubusercontent.com/5863899/36916155-56cadcbc-1e10-11e8-9719-2ce7579fa323.png">

**Comment by Denz1994** [comment]
There was some bugginess in adding and removing elements from the panel. Instead, we are just adding all of the nodes to the panel and toggling visibilities based on what planet is selected.

I think commit 7e370e694b51d698fb49e8eee4b7df35597c1f55 might have fixed this in master. Can you confirm @phet-steele.

**Comment by phet-steele** [comment]
@Denz1994 this works. Makes i18n pretty tight though (shrinks quite a bit).
