### ISSUE TITLE
Movable Line does not reset

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#239]
1. Enable Movable Line
2. Move it
3. Reset All

Enable the Movable Line again and notice that its position did reset to default.

Seen on macOS 10.13.3 Chrome. For phetsims/QA/issues/103.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.81/phet/masses-and-springs_en_phet.html
Version: 1.0.0-dev.81 2018-02-27 19:48:17 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"6ea6b964","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"4ae76b30","branch":"master"},"dot":{"sha":"8d471f40","branch":"master"},"griddle":{"sha":"9028614b","branch":"master"},"joist":{"sha":"40c4ae27","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"masses-and-springs":{"sha":"18511604","branch":"master"},"phet-core":{"sha":"f35ff65e","branch":"master"},"phet-io":{"sha":"3cecc850","branch":"master"},"phet-io-website":{"sha":"6e54fcc2","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"master"},"phet-io-wrapper-sonification":{"sha":"7d51caa9","branch":"master"},"phet-io-wrappers":{"sha":"290b6892","branch":"master"},"phetcommon":{"sha":"9c8018af","branch":"master"},"query-string-machine":{"sha":"485e174e","branch":"master"},"scenery":{"sha":"6b844c44","branch":"master"},"scenery-phet":{"sha":"e95210c0","branch":"master"},"sherpa":{"sha":"01058f19","branch":"master"},"sun":{"sha":"962fa366","branch":"master"},"tandem":{"sha":"5c68df6a","branch":"master"},"twixt":{"sha":"3f2cc19d","branch":"master"}}
</details>

**Comment by Denz1994** [comment]
Hey, @phet-steele could you check if this is fixed in master?

**Comment by phet-steele** [comment]
Fixed in master.
