### ISSUE TITLE
Update screen icons 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#240]
For https://github.com/phetsims/QA/issues/103

- [x] Intro screen: Update unknown mass color
- [x] Energy screen: Update stacking order of total energy 
- [x] Lab screen: Remove equilibrium position

**Comment by arouinfar** [comment]
Updated assets have been sent to @Denz1994.

**Comment by Denz1994** [comment]
The screen icons have been applied in this [dev version.](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.82/phet/masses-and-springs_en_phet.html) What do you think @arouinfar?

**Comment by arouinfar** [comment]
👍
