### ISSUE TITLE
Position velocity/acceleration vectors dynamically

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#241]
@Denz1994 @arouinfar it might be a sleek enhancement to position the Velocity/Acceleration vectors based on their visibility. What I mean is:

When only one of these vectors is enabled, that vector appears in the middle of the mass like so:

<img width="250" alt="screen shot 2018-02-28 at 11 09 53 am" src="https://user-images.githubusercontent.com/5863899/36804573-3c2b8904-1c78-11e8-8535-8f14b8a958d3.png">

(so if acceleration was the only one enabled, it would be at the same spot as the velocity vector in this screenshot).

Only once BOTH are enabled at one time will they resort to being side by side as they are now.

How does this sound? @Denz1994 does this sound easy to do?

For phetsims/QA/issues/103.

**Comment by Denz1994** [comment]
I like this and it shouldn't be too hard to implement. I'll work on it.

**Comment by arouinfar** [comment]
Thanks for the suggestion @phet-steele. From Slack discussion, this sounds like a straight-forward change, so I'd say go for it @Denz1994.

**Comment by Denz1994** [comment]
Great suggestion @phet-steele. Could you see if this issue resolved in master?

**Comment by phet-steele** [comment]
This is working great in master! Now I'm noticing though that arrows are not quite centered on the mass (when alone). This is most noticeable on mystery masses. Using the ruler as a straightedge, the arrow is a bit far to the right of the center:

<img width="185" alt="screen shot 2018-02-28 at 1 54 51 pm" src="https://user-images.githubusercontent.com/5863899/36812631-fc77e764-1c8e-11e8-88c9-5e2de459c461.png">

**Comment by Denz1994** [comment]
Good catch. There were some inconsistencies in the view elements compared to the model that was taken care off. This should be fixed in master @phet-steele.

**Comment by phet-steele** [comment]
Nice and centered! Gracias everyone.
