### ISSUE TITLE
Stop button is disabled during the first step of oscillation

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#245]
1. Pause the sim.
2. Attach a mass to a spring.
3. Drag the spring and release.
4. Step the sim forward once.

On this first step, the mass is moving (you can verify with the energy graph or velocity vector), however the Stop button is still disabled. On the second step forward, the Stop button will be enabled.

![mas12](https://user-images.githubusercontent.com/5863899/36866394-6a026118-1d4f-11e8-98f4-80df5328fd92.gif)

Seen on macOS 10.13.3 Chrome. For phetsims/QA/issues/103.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.81/phet/masses-and-springs_en_phet.html
Version: 1.0.0-dev.81 2018-02-27 19:48:17 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"6ea6b964","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"4ae76b30","branch":"master"},"dot":{"sha":"8d471f40","branch":"master"},"griddle":{"sha":"9028614b","branch":"master"},"joist":{"sha":"40c4ae27","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"masses-and-springs":{"sha":"18511604","branch":"master"},"phet-core":{"sha":"f35ff65e","branch":"master"},"phet-io":{"sha":"3cecc850","branch":"master"},"phet-io-website":{"sha":"6e54fcc2","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"c84e3046","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ebf7c7dc","branch":"master"},"phet-io-wrapper-sonification":{"sha":"7d51caa9","branch":"master"},"phet-io-wrappers":{"sha":"290b6892","branch":"master"},"phetcommon":{"sha":"9c8018af","branch":"master"},"query-string-machine":{"sha":"485e174e","branch":"master"},"scenery":{"sha":"6b844c44","branch":"master"},"scenery-phet":{"sha":"e95210c0","branch":"master"},"sherpa":{"sha":"01058f19","branch":"master"},"sun":{"sha":"962fa366","branch":"master"},"tandem":{"sha":"5c68df6a","branch":"master"},"twixt":{"sha":"3f2cc19d","branch":"master"}}
</details>

**Comment by Denz1994** [comment]
This may explain why the button is flickering in issue #244. I will track down the link responsible for this.

**Comment by Denz1994** [comment]
Could you check if this is solved in master @phet-steele? See [#244 comment](https://github.com/phetsims/masses-and-springs/issues/244#issuecomment-369941366) for explaination of solution. Thanks.

**Comment by phet-steele** [comment]
Yes, this is fixed. Thanks for the explanation.
