### ISSUE TITLE
ResetAllButton should be in front of scene graph at all times.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#248]
@phet-steele noted that the reset all button can be blocked by draggable sim elements (masses, ruler, and timer). He mentioned in a slack message 03/07/18.

> "It’s sort of the “last resort” button so it should always be usable"

Note: This behavior isn't something that is found in Pendulum Lab or CCK, but maybe it should be.

**Comment by Denz1994** [comment]
Can you check this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.88/phet/masses-and-springs_en_phet.html) @phet-steele for the desired behavior?

**Comment by Denz1994** [comment]
Addendum to above note: Unit rates does follow this behavior, where the reset all button isn't blocked by draggable nodes.

**Comment by phet-steele** [comment]
@ariel-phet I'm correct in this convention, right? Clearly it's not something we always remember to check (hence PL and CCK being different). Maybe well suited to be checked in a code review as an additional check after QA (easy to verify from looking at code I believe).

Then @Denz1994 asked if this extended to play/pause and sim speed options....does it @ariel-phet?

> Can you check this dev version @phet-steele for the desired behavior?

@Denz1994 dev.88 is correct on the first two screen, but the last two have not changed.

For phetsims/QA/issues/103.

**Comment by ariel-phet** [comment]
@phet-steele I don't think we have a "hard and fast" rule. For something like pendulum lab, if you cover the button with the ruler or timer, it is not a big deal to just move them out of the way. 

@arouinfar - I don't think we have ever said the reset all button must always be on top have we?

**Comment by ariel-phet** [comment]
My instinct would be that as long as the reset all button is not getting covered in "normal" use cases, it is not a concern.

**Comment by phet-steele** [comment]
> @phet-steele I don't think we have a "hard and fast" rule.

@ariel-phet @arouinfar is there any harm in having a hard and fast rule? Has there been a situation where it's been problematic to have something behind the button (ie something small gets stuck behind)?

**Comment by Denz1994** [comment]
> Has there been a situation where it's been problematic to have something behind the button (ie something small gets stuck behind)?

Charges and fields has charges and sensors that are smaller than the button.

Could @phet-steele review this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.89/phet/masses-and-springs_en_phet.html). It wasn't too hard of a fix.

**Comment by arouinfar** [comment]
> @arouinfar - I don't think we have ever said the reset all button must always be on top have we?

@ariel-phet I don't think it's ever been explicitly discussed in design, but I think it's generally been a QA convention to check the z-order (recently, at least).

> For something like pendulum lab, if you cover the button with the ruler or timer, it is not a big deal to just move them out of the way.

Agreed, but I think it's best to leave ResetAllButton on top, whenever possible. If the user encounters a bug, the ResetAllButton will be more accessible if it's kept on top.

> Charges and fields have the charges and sensors that are smaller than the button.

Good example, @Denz1994. That might be a case were we should consider allowing other objects on top of the ResetAllButton. 

> Could you review this dev version. It wasn't too hard of a fix.

Looks good to me @Denz1994!

**Comment by phet-steele** [comment]
@Denz1994 dev.89 is working great

> Charges and fields have the charges and sensors that are smaller than the button.

Good point!
