### ISSUE TITLE
Icon artwork needed for scene switching buttons.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#25]
The current implementation of the scene switching buttons uses a placeholder as the icon for the buttons. Official artwork should be used instead unless this suffices. Please advise @arouinfar. Thanks!

_Current artwork:_
![half-spring-icon](https://cloud.githubusercontent.com/assets/13894380/22898922/4cad54aa-f1e6-11e6-87e3-788890e97887.PNG)

![two-spring-icon](https://cloud.githubusercontent.com/assets/13894380/22898921/4ca8d484-f1e6-11e6-8d4c-4db59051fb42.PNG)

**Comment by arouinfar** [comment]
@Denz1994 I don't have true Illustrator assets for the springs, just screenshots from scenery-phet. I can certainly send you image files to use for now, but I think a better long-term solution would be to draw the icons in code.

**Comment by arouinfar** [comment]
@Denz1994 here are image files for the scene icons.

[different_length_scene.png](https://cloud.githubusercontent.com/assets/8419308/22906021/e31afaaa-f1ff-11e6-9e75-1c67be769901.png)
[same_length_scene.png](https://cloud.githubusercontent.com/assets/8419308/22906020/e3191a46-f1ff-11e6-9dba-7fb64497ee63.png)

**Comment by Denz1994** [comment]
@arouinfar I was using Color-Vision as a model for how to implement the icons and in that sim, artwork is used for the icon. I will follow through with your suggestion of drawing it in code. Thanks for the images in the meantime.

**Comment by arouinfar** [comment]
Sounds good @Denz1994. It's not uncommon to create the artwork for scene icons in Illustrator (like color-vision), but in this case I just don't have them.

**Comment by Denz1994** [comment]
Makes sense. I will implement these changes.

**Comment by Denz1994** [comment]
Commit 95ce0809622118f7febb5f51e438a372482a9df6 fixed this issue.
