### ISSUE TITLE
Add icon to mass panel

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#250]
On the Lab screen, it may not be immediately clear which mass the slider is adjusting.  After discussion with @ariel-phet we decided that adding an iconic mass to the panel would address this issue. @Denz1994 can you add an iconic adjustable mass to the left of the "Mass" title? Here's a mockup:

![image](https://user-images.githubusercontent.com/8419308/37170441-0ea12c90-22c8-11e8-8f4d-f41232a5f0d5.png)

**Comment by Denz1994** [comment]
One cute little mass icon coming up.

**Comment by Denz1994** [comment]
@arouinfar Can you check this [dev version](https://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.94/phet/masses-and-springs_en_phet.html) for review?

**Comment by arouinfar** [comment]
Those are indeed cute little mass icons! 😄 

A few tweaks:
* The mass looks a bit too small, can you increase the size ~10%?
* There's also appears to be quite a bit of extra padding at the top of the panel. Can you trim those extra pixels off?
![image](https://user-images.githubusercontent.com/8419308/38329724-e85be40e-380b-11e8-8902-258329cd2751.png) ![image](https://user-images.githubusercontent.com/8419308/38329741-ee30a860-380b-11e8-918b-9cf78695a53d.png)

**Comment by Denz1994** [comment]
Panel changes were made on master @arouinfar?

**Comment by arouinfar** [comment]
@Denz1994 it looks like trimming off the extra padding from the top of the panel shifted the icon down.
![image](https://user-images.githubusercontent.com/8419308/38625680-3fcb925a-3d68-11e8-89d0-2995b772bb90.png)

Can you center-align the icon with "Mass"? 
![image](https://user-images.githubusercontent.com/8419308/38625819-874eb77e-3d68-11e8-8f1d-dd1939994a21.png)

**Comment by Denz1994** [comment]
What about now @arouinfar? Try in master.

**Comment by arouinfar** [comment]
Getting closer @Denz1994, but it's still not quite centered
![image](https://user-images.githubusercontent.com/8419308/38629414-2f8bffde-3d71-11e8-9768-d2f4e2a13745.png)

**Comment by arouinfar** [comment]
Mass icon looks great! 

I've noticed that the "Mass" string looks way smaller than other slider titles. Can you bump it up to 14pt to match the others?

**Comment by Denz1994** [comment]
The mass string was smaller, due to the size of the panel it is contained in. I made the panel a bit larger so the string also increased in size. What do you think @arouinfar?

**Comment by arouinfar** [comment]
Sorry to keep kicking this back to you @Denz1994, but the font size still looks pretty small. Can you bump it up a bit more? It's okay if the panel ends up slightly larger.

**Comment by Denz1994** [comment]
There was a problem with the overall layout of the contentNode of the panel. We needed to remove the force vectors from the mass icon. The icon created bounds to include them despite not being visible. This makes the adjustment of fonts and positioning the panel's content a lot less hacky.

Could you review the massValueControlPanel in master @arouinfar?

**Comment by arouinfar** [comment]
Getting really close @Denz1994!! Alignment looks good, but the relative font sizes look a bit off. The min/max labels look too large, and the readout looks a bit too small. The min/max/readout should all be the same size, as in the Gravity slider (12 pt, I believe).

![screen shot 2018-05-15 at 2 59 58 pm](https://user-images.githubusercontent.com/8419308/40083429-56f4bc50-5851-11e8-884e-7dcb7a440782.png)
![screen shot 2018-05-15 at 2 59 58 pm copy](https://user-images.githubusercontent.com/8419308/40083430-5705c81a-5851-11e8-8c58-2608a4a7245f.png)

**Comment by arouinfar** [comment]
Looking good!
