### ISSUE TITLE
Phet-io status?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/masses-and-springs#254]
I see some instrumentation, but the sim isn't listed as having phet-io support in its package.json. What is the current phet-io status with this sim?

See https://github.com/phetsims/masses-and-springs/issues/253

**Comment by Denz1994** [comment]
At one point there was supposed to be phet-io integration, but as the phet-io engine has implementation methods have undergone changes, I believe phet-io implementation was to be postponed.
