### ISSUE TITLE
Some touch areas could be improved

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/masses-and-springs#257]
The tweaker buttons for mass/spring-constant have pretty small touch areas. Gravity too, so maybe all of them could be increased? In the energy graph, the thermal button and info button could be increased. Areas in the toolbox (ruler/timer icons) could be increased to fit. Reset-all has some space to be increased.

Up to @arouinfar if touches that barely miss a mass should grab it. This requires slightly different logic that I can help with (listens to events on the background that "miss", finds the closest mass, and checks if it is within the touch threshold).

Also @arouinfar, any disagreement with expanding the touch areas I mentioned?

See https://github.com/phetsims/masses-and-springs/issues/253

**Comment by arouinfar** [comment]
@Denz1994 let's expand the touch areas as @jonathanolson suggested.

@jonathanolson I'm not sure I follow:
> Up to @arouinfar if touches that barely miss a mass should grab it. This requires slightly different logic that I can help with (listens to events on the background that "miss", finds the closest mass, and checks if it is within the touch threshold).

Would this be somewhat similar (in spirit) to the request made in #210? I'm generally in favor of changes that would make the oscillating masses easier to grab. I'd say it's worth investigating if it won't require a huge amount of resources or have large adverse effects on iPad2 performance.

**Comment by jonathanolson** [comment]
Yes, I was thinking it would be like Charges and Fields / Pendulum Lab. https://github.com/phetsims/pendulum-lab/issues/117 is a good reference, and hopefully the tagged commits help with the implementation.

**Comment by jonathanolson** [comment]
> I'd say it's worth investigating if it won't require a huge amount of resources or have large adverse effects on iPad2 performance.

Shouldn't require a lot of resources, and shouldn't hurt performance.

**Comment by arouinfar** [comment]
Thanks for the clarification @jonathanolson. Let's go for it!

**Comment by arouinfar** [comment]
@Denz1994 I'm having trouble using phettest on the iPad. Can you publish a new dev version?

**Comment by arouinfar** [comment]
@Denz1994 I cannot touch or click many UI elements, please see the above bug report.

**Comment by Denz1994** [comment]
Just pushed a fix for that to master. Still having issues with releasing dev versions. I will push a dev version once it is corrected if testing from phettest is still an issue.

**Comment by arouinfar** [comment]
Sounds good @Denz1994. Still can't load phettest on the iPad, so I'll wait for the new dev.

**Comment by arouinfar** [comment]
Looks good @Denz1994!
