### ISSUE TITLE
Performance check?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/masses-and-springs#259]
I'm not able to test on a range of lower-performance devices. As part of the code review, it wants a performance check.

@phet-steele, is performance acceptable, and/or is there anything that could be improved?

See https://github.com/phetsims/masses-and-springs/issues/253

**Comment by phet-steele** [comment]
I probably won't have time for this, and @jonathanolson I know you have an iPad 2. That's all you need.

**Comment by jonathanolson** [comment]
@lmulhall-phet, can you let me know how the performance looks as part of the QA tests for https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.102/phet/masses-and-springs_all_phet.html?

If it needs improvement, I'll be available for collaboration with @Denz1994.

**Comment by ghost** [comment]
@jonathanolson, I tested the latest dev on an iPad 2, and IMO the performance is not great, but acceptable.

EDIT: The dev version you linked above has a bug that breaks the sim, hence testing it on a newer dev.

**Comment by Denz1994** [comment]
Being that https://github.com/phetsims/QA/issues/122, https://github.com/phetsims/QA/issues/126, and https://github.com/phetsims/masses-and-springs/issues/285 were closed and perfromanced was measured several times in the last month of testing, I'm closing this issue. iPad 2 performance seems accemptable.
