### ISSUE TITLE
LineArrowShape common code work? 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#261]
It seems like https://github.com/phetsims/scenery-phet/issues/165 should be done as part of finishing this sim off. Noting here so that work does not get overlooked.

**Comment by Denz1994** [comment]
As noted in a https://github.com/phetsims/scenery-phet/issues/165#issuecomment-390337404, LineArrowShape (now LineArrowNode) is now being considered as its own common code component. This would remove consolidation with ArrowNode.js. 

Currently, MAS is using the new added common code component LineArrowNode.js that is a copy from Hookes-Law (which was already reviewed). This is the final blocking issue for another round of dev testing. Awaiting @pixelzoom for input on the matter in phetsims/scenery-phet#165.

**Comment by Denz1994** [comment]
phetsims/scenery-phet#165 has been closed and as noted in the above comment we are moving on with sim code in M&S.  Closing this issue.
