### ISSUE TITLE
Update Credits

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#263]
Opening this issue so we don't forget to update credits.

Current Credits are as follows:
 ```js 
credits: {
      leadDesign: 'Amy Rouinfar',
      softwareDevelopment: 'Denzell Barnett, Matt Pennington',
      team: 'Ariel Paul, Kathy Perkins, Mike Dubson',
      qualityAssurance: 'Steele Dalton'
```

**Comment by arouinfar** [comment]
QA credits should include Arnab Purkayastha and Liam Mulhall, and will likely expand to include others, so @lmulhall-phet should confirm the QA credits once we get to RC testing.

@jonathanolson may also need a dev credit, but I'm not sure about the scope of his contributions.

**Comment by ghost** [comment]
So far as I know, it’s Arnab, Steele, and myself. Possibly Ethan as well. I don’t know if Bryce or Ben tested, but I suppose we can include them just in case.

**Comment by Denz1994** [comment]
Should we include anyone else in the credits @ariel-phet? Sorry, I don't know Bryce and Ben's full names @lmulhall-phet.

Current Credits:
```js
    credits: {
      leadDesign: 'Amy Rouinfar',
      softwareDevelopment: 'Denzell Barnett, Matt Pennington',
      team: 'Ariel Paul, Kathy Perkins, Mike Dubson',
      qualityAssurance: 'Steele Dalton, Arnab Purkayastha, Liam Mulhall'
    }
```

**Comment by ariel-phet** [comment]
@Denz1994 our policy has been to include all people from the original sim in the credits for the port

Mike Dubson should be moved up to "lead design" (after Amy)

Wendy Adams should be included in "team" alphabetically

confirm with @lmulhall-phet for QA members

Ask @jonathanolson if he wants to be included in software (since he did help develop the model I believe)

**Comment by jonathanolson** [comment]
> Ask @jonathanolson if he wants to be included in software (since he did help develop the model I believe)

I think @mattpen was the one who wrote the model?

**Comment by Denz1994** [comment]
@mattpen was the original author of the model. Here is the final version of the credits. Can you confirm the QA team @lmulhall-phet or @phet-steele?
```js;
    credits: {
      leadDesign: 'Amy Rouinfar, Mike Dubson',
      softwareDevelopment: 'Denzell Barnett, Matt Pennington',
      team: 'Wendy Adams, Ariel Paul, Kathy Perkins',
      qualityAssurance: 'Steele Dalton, Arnab Purkayastha, Liam Mulhall'
    }
```

**Comment by ghost** [comment]
@Denz1994, I've updated the QA credits with people I've seen testing M&S.

**Comment by Denz1994** [comment]
Thanks @lmulhall-phet. I'm going to close this issue.

**Comment by phet-steele** [comment]
@Denz1994 I went ahead and added the changes to 1.0 as well.

**Comment by phet-steele** [comment]
QA has a handful of new members. @Denz1994 @KatieWoe please update this sim's QA credits in 1.0 and master, before publication.

**Comment by KatieWoe** [comment]
Add Kathryn Woessner, Megan Lai, Jacob Romero, and Ethan Johnson
@megan-phet @JRomero0613 @EthanWJohnson Let me know if this is how you want your names written.  Remove your assignment when you've approved.

**Comment by Denz1994** [comment]
Credits have been updated in both branches. The last person to approve their name please close this issue.

**Comment by KatieWoe** [comment]
@Denz1994 I think @CWilson4960 also contributed.

**Comment by arouinfar** [comment]
That's correct @KatieWoe. @Denz1994 please add Clara Wilson to the QA credits.

**Comment by Denz1994** [comment]
Clara Wilson has been added. Is there anyone else? If not, I will close.

**Comment by arouinfar** [comment]
@Denz1994 should the QA additions in https://github.com/phetsims/masses-and-springs/commit/fc6432191d7f5191fafa8c4a5c52a323b2a1ae73 and https://github.com/phetsims/masses-and-springs/commit/584f0553ca1ec5945454536a3d8a7e0fd14b0920 also apply to the `accessibleScreenView` branch? Otherwise, I think we can go ahead and close this issue.

**Comment by Denz1994** [comment]
Based on this comment, https://github.com/phetsims/masses-and-springs/issues/326#issue-355277448 I don't think credits need to be updated, since the branch is to be deleted.

**Comment by Denz1994** [comment]
The latest[ rc version](https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-rc.9/phet/masses-and-springs_all_phet.html) includes the updated credits.
