### ISSUE TITLE
Spring anchors are not centered

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#266]
@arouinfar @Denz1994 likely not a huge deal, but now that I've seen it I can't unsee it. On the Energy and Lab screens, the spring anchor point is not quite centered on the gray block. It is shifted closer to the left. This throws the entire spring, and masses attached to the spring, off to the left as well.

<img width="250" alt="screen shot 2018-05-21 at 5 25 37 pm" src="https://user-images.githubusercontent.com/5863899/40334660-4e2f6a46-5d1c-11e8-9960-925bc674983d.png">

@arouinfar can we move it over to the right a tad? I don't think it would cause other issues 🤞.

Seen on macOS 10.13.4 Chrome. For phetsims/QA/issues/122.

<details>
<summary>Troubleshooting Information</summary>

URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.102/phet/masses-and-springs_all_phet.html
Version: 1.0.0-dev.102 2018-05-21 16:49:55 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"aaa0d77a","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"griddle":{"sha":"f9afbaec","branch":"master"},"joist":{"sha":"0d2b102d","branch":"master"},"kite":{"sha":"bd06199c","branch":"master"},"masses-and-springs":{"sha":"577e8758","branch":"master"},"phet-core":{"sha":"49911783","branch":"master"},"phet-io":{"sha":"545d86c9","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"1b254bcf","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"588f22fb","branch":"master"},"scenery-phet":{"sha":"b31317ca","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"9ebf1a6c","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"}}
</details>

**Comment by phet-steele** [comment]
> I might also just shrink the gray block a bit (so the right side is a bit shorter)

Sure thing...unless the location of the anchor is dependent on the bounds of the gray block, like it's placed at width/2 or something. Shortening the length of the block would also shift the anchor over in that case 😄.

**Comment by Denz1994** [comment]
The controls towards the center of the screen around the spring are grouped together. This makes the view more manageable and a lot more readable. So we can just shift the controls, including the springHangerNode (gray block) to the left to center it over the springNode. Can you check in master @phet-steele if it looks good?

**Comment by phet-steele** [comment]
@arouinfar @Denz1994 while we are at it, can we center the "1" and "2" over the anchors?
<img width="258" alt="screen shot 2018-05-22 at 3 45 54 pm" src="https://user-images.githubusercontent.com/5863899/40391958-5143b320-5dd7-11e8-8cdf-85a84dde6522.png">

**Comment by arouinfar** [comment]
Agreed @phet-steele.

**Comment by Denz1994** [comment]
Good point. Can you try in master @phet-steele for the centered labels?

**Comment by phet-steele** [comment]
Lookin' good.

**Comment by arouinfar** [comment]
For https://github.com/phetsims/QA/issues/165

@Denz1994 on Energy and Lab, the springNode is no longer centered in the gray block. The attachment point is shifted a bit to the right. (Intro and Vectors alignment still looks fine.)

![screen shot 2018-08-10 at 12 05 02 pm](https://user-images.githubusercontent.com/8419308/43973779-ab460cb8-9c95-11e8-9c4b-5ca69bcc12a6.png)


![screen shot 2018-08-10 at 12 04 27 pm](https://user-images.githubusercontent.com/8419308/43973718-8e6a7fde-9c95-11e8-8b97-76bf1e3ac7f9.png)

**Comment by Denz1994** [comment]
Minor tweak to centering. This came about when we changed the size of the hSlider panels. Can you check in master @arouinfar?

**Comment by arouinfar** [comment]
Looks great!
