### ISSUE TITLE
PhET-iO Instrumentation

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#27]
As an introduction to PhET-iO Instrumentation for @Denz1994 and for me to get feedback on the "How To Instrument" documents, we would like to take the first steps toward instrumenting Masses and Springs.  I'll paste the checkboxes here, and we can proceed with the instructions.  I want to clarify: this simulation does not need to be instrumented for any 3rd parties for a deadline, but we chose this simulation for @Denz1994 instrumentation because he is most familiar with it.

https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md
  - [x] [Understand the goal](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#understand-the-goal)
 - [ ] [Code review](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#code-review)
 - [x] Use Property instead of PropertySet
 - [x] [Import Tandem to main.js](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#import-tandem-to-mainjs)
 - [x] [Create root tandem](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#create-root-tandem)
 - [x] [Pass tandems to sim screens](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-sim-screens)
 - [x] [Pass tandems to model and view](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-model-and-view)
 - [x] [Pass tandems to all constructors](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-all-constructors)
   + See also [Testing while adding Tandem instances](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#testing-while-adding-tandem-instances). Test with `?phetioValidateTandems=false` since common code components don't yet have tandems.
 - [x] [Pass tandem instances to common code components](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandem-instances-to-common-code-components)
   + See also [Testing while adding Tandem instances](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#testing-while-adding-tandem-instances).
 - [x] [Replace types with tandemized equivalents](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#replace-types-with-tandemized-equivalents)
 - [ ] [Instrument any Uninstrumented Common Code Components Used by the Sim](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#instrument-any-uninstrumented-common-code-components-used-by-the-sim)
 - [x] [Instrument new component types defined by the sim](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#instrument-new-component-types-defined-by-the-sim)
 - [x] [Add simulation specific support](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#add-simulation-specific-support)
 - [x] [Support dynamic state](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#support-dynamic-state)
 - [x] Make sure Joist `dt` values are used instead of Date.now() or other Date functions.  This is necessary for reproducible playback via input events.
 - [x] Are random numbers using `phet.joist.random`, and all doing so after modules are declared (non-statically)?  For
 instance, the following methods (and perhaps others) should not be used: `Math.random`, `_.shuffle`, `_.sample`, `_.random`
 - [x] `undefined` values cannot be saved from the phet-io state save, sims should be written to use `null` instead
 - [ ] Verify that the simulation works in all of the phet-io wrappers
 - [ ] Set up a task to have the newly instrumented sim tested by the QA team
 - [ ] Update these instructions if you find them to be incomplete, inconsistent or incorrect
 - [ ] Add your instrumented simulation to the spreadsheet here: https://docs.google.com/spreadsheets/d/1ToW8wc9zOFpMglIf63jB1j8YA9Qmh2dxNLH2Sm4qxEo/edit?usp=drive_web

**Comment by Denz1994** [comment]
As per our discussion on 12/6/17  with @ariel-phet, can I close this issue as far as phet-io implementation? There seems to be some fundamental changes to the phet-io engine that won't be included in the published version of masses and springs. We can always open a new issue in the future.

**Comment by samreid** [comment]
Yes, let's close for now and we can re-evaulate when it is time to bring Masses and Springs PhET-iO to production.
