### ISSUE TITLE
Period trace does not draw horizontally very gracefully

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#270]
When stepping forward, at the moment when the trace is drawn horizontally, the horizontal bit looks ugly with a visible overhang:

<img width="200" alt="screen shot 2018-05-21 at 5 48 22 pm" src="https://user-images.githubusercontent.com/5863899/40335111-454e68ca-5d1f-11e8-8c16-819ab5c5179e.png">

@arouinfar I would imagine we do not want the overhang? This happens regardless of sim speed, it's just most obvious when stepping.

Seen on macOS 10.13.4 Chrome. For phetsims/QA/issues/122.

<details>
<summary>Troubleshooting Information</summary>

URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.102/phet/masses-and-springs_all_phet.html
Version: 1.0.0-dev.102 2018-05-21 16:49:55 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"aaa0d77a","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"griddle":{"sha":"f9afbaec","branch":"master"},"joist":{"sha":"0d2b102d","branch":"master"},"kite":{"sha":"bd06199c","branch":"master"},"masses-and-springs":{"sha":"577e8758","branch":"master"},"phet-core":{"sha":"49911783","branch":"master"},"phet-io":{"sha":"545d86c9","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"1b254bcf","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"588f22fb","branch":"master"},"scenery-phet":{"sha":"b31317ca","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"9ebf1a6c","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"}}
</details>

**Comment by arouinfar** [comment]
Quite the catch @phet-steele. The overhang was not a deliberate design decision. @Denz1994 can you kill it?

**Comment by arouinfar** [comment]
@Denz1994 while a bit unsightly, the overhang isn't harmful. If it would require significant time to address, please feel free to veto.

**Comment by Denz1994** [comment]
I'll wait for @jonathanolson input (just out of curiosity). It may be a Shape.js or Path.js issue.

**Comment by jonathanolson** [comment]
Checking into it (self-assigning).

**Comment by jonathanolson** [comment]
So this looks like the general way browsers render stroked lines when one of the starting/ending line segments is very short (shorter than the lineWidth/2).

I'm not sure if we need to figure out a better way to handle this in the general case (maybe?), but for now, in PeriodTraceNode, we could avoid drawing the "second line" and "third line" if their points are less than lineWidth/2 from the last point (and figure out how that works for very small period traces).

Thoughts @Denz1994?

**Comment by Denz1994** [comment]
> and figure out how that works for very small period traces

Will work on #235 to squelch small period trace oscillations, before handling this issue. Will return after that work is complete.

**Comment by phet-steele** [comment]
> and because we are squelching small oscillations we don't need a general case for this sim (see #235).

@Denz1994 @arouinfar care to reconsider now that we are keeping small oscillations? Up to you. This is how a **_complete_** trace looks:

<img width="300" alt="screen shot 2018-06-05 at 10 57 13 am" src="https://user-images.githubusercontent.com/5863899/40990982-9f49e962-68af-11e8-891a-6f00bd730bc0.png">
 
I even get the impression that this trace looks upside down:
<img width="300" alt="screen shot 2018-06-05 at 11 15 44 am" src="https://user-images.githubusercontent.com/5863899/40991721-eab86d36-68b1-11e8-837b-82819d642e5f.png">


For phetsims/QA/issues/126.

**Comment by Denz1994** [comment]
I think part of the decision involved the fact, in order to get this trace you have to make the mass oscillate. You would see it get to this point and can still be interpreted. A better summary is here in https://github.com/phetsims/masses-and-springs/issues/235#issuecomment-393958310.

**Comment by arouinfar** [comment]
@phet-steele please take a look at my last https://github.com/phetsims/masses-and-springs/issues/235#issuecomment-393958310, and let me know if you still have questions/concerns.

**Comment by phet-steele** [comment]
@arouinfar I believe https://github.com/phetsims/masses-and-springs/issues/235#issuecomment-393958310 you linked me to is more aligned to the discussion of having small period traces or not, and glosses over the trace's appearance in such a case (which is what I'm referring to in https://github.com/phetsims/masses-and-springs/issues/270#issuecomment-394785193). Saying the trace is "a bit unsightly at the end" is an oversimplification in my mind. I think the screenshots in https://github.com/phetsims/masses-and-springs/issues/270#issuecomment-394785193 are much more than "a bit unsightly" and fixing that overhang would be a substantial polish. In other words, I'm doing my job and trying to assure the quality of our sims. This issue was closed based on the old information that we wouldn't have small traces, so I thought it needed to be brought up again since that is no longer the case.

**Comment by ariel-phet** [comment]
@phet-steele I am going to take over this issue and discuss with @Denz1994 - thanks for pointing out. I think we might be able to make a simple change or two and accomplish the polish without big time investment.

**Comment by ariel-phet** [comment]
This unsightliness basically disappears (or is at least very strongly mitigated) if the line width is made smaller. The larger line width at reasonable oscillations looks very good so I am proposing that at a certain threshold we shrink the line width. I think this will have two good consequences

1. It should accomplish the polishing issue
2. It should help the idea of the oscillation "fading away"

@Denz1994 is going to try this proposed solution.

**Comment by Denz1994** [comment]
In about 1 hour two versions have been produced.

[Dev Version 210](https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.110/phet/masses-and-springs_all_phet.html): The period trace thins to a smaller line width after a certain threshold. This is inline with @ariel-phet [comment](https://github.com/phetsims/masses-and-springs/issues/270#issuecomment-394843936)

[Dev Version 211](https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.111/phet/masses-and-springs_all_phet.html): The period trace incrementally thins after it passes its threshold. There is some room to play around with the rate at which it thins. This wasn't requested, but it seemed like a natural progression and was fun to code at the cost of 25 minutes.

Thoughts @ariel-phet?

**Comment by phet-steele** [comment]
My two cents: dev.111 is much better between the two. dev.110 has a sudden "jump" to thinness that looks very ugly if it happens in the middle of a trace. dev.111 gets around this by having the thinness occur gradually.

Sorry to be that guy, but the original issue was about the overhang at *any* trace height, not just small traces. See the screenshot in the first post. So if this thinness becomes an acceptable solution to the overhang, I would have to advocate for it being thin all the time at any trace height.

**Comment by Denz1994** [comment]
Me a few comments ago:
> I've implemented a prototype for a general solution that involves drawing a line relative to being a distance away from its previous point, but it is making the code less readable and not covering all cases.

@phet-steele I can investigate for another hour on not drawing lines relative to its previous position. This may be a solution we can apply to Path.js in common code. I'll report back.

**Comment by ariel-phet** [comment]
@Denz1994 @phet-steele @arouinfar 

I really like dev.111 !  I had thought that might be nice, but didn't bring it up, so nice initiative trying the @Denz1994. 

As for the overhang, I have to look pretty closely to notice it at large trace heights, and I don't think it is currently worth the time to polish it further.

**Comment by ariel-phet** [comment]
@arouinfar should make the final call, but I think this it good to go.

**Comment by Denz1994** [comment]
Thanks @ariel-phet. I'll wait for @arouinfar 's decision before further investigation.

**Comment by arouinfar** [comment]
My vote is also for dev.111 @Denz1994. It looks really nice!

> As for the overhang, I have to look pretty closely to notice it at large trace heights, and I don't think it is currently worth the time to polish it further.

I agree @ariel-phet, though I do appreciate @phet-steele's attention to detail. To observe the overhang, I have to actively seek it out by stepping forward.

**Comment by Denz1994** [comment]
Okay, it seems like @ariel-phet and @arouinfar are in agreement about proceeding with dev.111

I will close this issue because the overhang is something we will not fix. Thanks, input for the team.
