### ISSUE TITLE
Period trace layering

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#271]
@arouinfar this is not an issue unless you say it is, so I just wanted to check: are we okay with the period trace layering?

It's layered over everything (except dialogs):

<img width="421" alt="screen shot 2018-05-21 at 5 53 26 pm" src="https://user-images.githubusercontent.com/5863899/40335243-e7591a16-5d1f-11e8-8297-28728d132894.png">

For phetsims/QA/issues/122.

**Comment by Denz1994** [comment]
The ruler has been moved to the front of the sceneGraph. Could you try the layering in this [dev version](https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-dev.105/phet/masses-and-springs_en_phet.html) @arouinfar?

**Comment by arouinfar** [comment]
👍
