### ISSUE TITLE
Period trace is always running

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#273]
@arouinfar @Denz1994 it looks like the Period Trace checkbox is only toggling the visibility of the trace, instead of also toggling its calculation. In other words, the trace is ALWAYS being drawn, you just can't see it sometimes. This means that, when checking the Period Trace checkbox, there is a 50% chance (I didn't think too hard on the math) that you will see an "in progress" trace, one that does not start from the beginning:

![mas15](https://user-images.githubusercontent.com/5863899/40335466-0d48185c-5d21-11e8-9042-fae43f3ac93e.gif)

You'll even see at the end of this gif that I clicked the checkbox and caught a trace mid-fade. @arouinfar I'm imaging this is less than ideal? Your call. I'm also somewhat concerned about performance implications, but I have no grounds to make an issue for that. It's just a hunch.

Seen on macOS 10.13.4 Chrome. For phetsims/QA/issues/122.

<details>
<summary>Troubleshooting Information</summary>

URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.102/phet/masses-and-springs_all_phet.html
Version: 1.0.0-dev.102 2018-05-21 16:49:55 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"aaa0d77a","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"griddle":{"sha":"f9afbaec","branch":"master"},"joist":{"sha":"0d2b102d","branch":"master"},"kite":{"sha":"bd06199c","branch":"master"},"masses-and-springs":{"sha":"577e8758","branch":"master"},"phet-core":{"sha":"49911783","branch":"master"},"phet-io":{"sha":"545d86c9","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"1b254bcf","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"588f22fb","branch":"master"},"scenery-phet":{"sha":"b31317ca","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"9ebf1a6c","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"}}
</details>

**Comment by Denz1994** [comment]
This is a great point @phet-steele. I too am concerned about the performance issue and any reduction step functions that aren't being used in the view would be a benefit to performance. Check out this [dev version](https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-dev.103/phet/masses-and-springs_en_phet.html) and tell me what you think @arouinfar. I think this is the behavior @phet-steele suggested.

**Comment by arouinfar** [comment]
Good find @phet-steele. This behavior is problematic. Performance is definitely a concern, but I think students could also be confused by the trace appearing already in progress. @Denz1994 dev.103 looks good, but I think @phet-steele should also verify.

**Comment by phet-steele** [comment]
Looks like it is working, thanks.
