### ISSUE TITLE
Period trace can get stuck when a mass has stopped

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#275]
1. Start a period trace.
2. BEFORE HALF the trace has been drawn, press the Stop button (or just somehow stop the mass ie. with damping, though that is much harder)

The trace will continue to drawn to the mass's stopping point then will just hang there indefinitely waiting to draw a full period, but it never will). @Denz1994 I would suggest that traces are removed when a mass has stopped (regardless of *how* the mass stopped).

<img width="429" alt="screen shot 2018-05-21 at 6 06 28 pm" src="https://user-images.githubusercontent.com/5863899/40335684-2dec264c-5d22-11e8-9068-d9c3a7e30d6a.png">

Seen on macOS 10.13.4 Chrome. For phetsims/QA/issues/122.

<details>
<summary>Troubleshooting Information</summary>

URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.102/phet/masses-and-springs_all_phet.html
Version: 1.0.0-dev.102 2018-05-21 16:49:55 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"aaa0d77a","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"griddle":{"sha":"f9afbaec","branch":"master"},"joist":{"sha":"0d2b102d","branch":"master"},"kite":{"sha":"bd06199c","branch":"master"},"masses-and-springs":{"sha":"577e8758","branch":"master"},"phet-core":{"sha":"49911783","branch":"master"},"phet-io":{"sha":"545d86c9","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"1b254bcf","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"588f22fb","branch":"master"},"scenery-phet":{"sha":"b31317ca","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"9ebf1a6c","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"}}
</details>

**Comment by arouinfar** [comment]
phettest is being a bit temperamental right now. I'll check back later this afternoon @Denz1994.

**Comment by phet-steele** [comment]
@Denz1994 turns out there is another part of this issue that I overlooked. If you change step 2 to:

-AFTER HALF but BEFORE COMPLETION, press stop...

...you get odd looking drawing. The end result is the same screenshot I have above, but it will visually "compress" the trace drawing. I think you have to start oscillation by compressing the spring, not expanding (changes the direction the trace is drawn) to see this.

So unless that gets fixed, I'd recommend just making the trace disappear so we don't see the ugly state.

**Comment by arouinfar** [comment]
@Denz1994 if the stop button is pressed, the Period Trace should immediately clear. The trace doesn't have any meaning when the mass is prematurely stopped, and it just looks weird. Better to immediately clear it than let it fade away.

**Comment by Denz1994** [comment]
That pesky period trace disappears at the press of the stop button. Can you test in master @phet-steele to make sure?

**Comment by phet-steele** [comment]
Looking good! I'l let @arouinfar close; should be a simple behaviour to verify. Side note for @Denz1994, you have small formatting issues throughout `PeriodTraceNode.js`. Maybe you'll get around to it later, so ignore me.

**Comment by arouinfar** [comment]
Looks good to me @Denz1994! 

> Side note for @Denz1994, you have small formatting issues throughout PeriodTraceNode.js. Maybe you'll get around to it later, so ignore me.

I'll leave this issue open so @Denz1994 sees this comment. Please feel free to close.

**Comment by Denz1994** [comment]
Thanks for the notice @phet-steele. I'm very active in that file today, but I'll clean it up soon enough.
