### ISSUE TITLE
Immovable lines appear movable

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/masses-and-springs#276]
In a similar vein to https://github.com/phetsims/masses-and-springs/issues/274, the mass equilibrium, natural length, and zero height lines appear interactable. The cursor changes to a hand when hovering over, but these lines cannot be manipulated in any way (zero height particularly, as it doesn't have a UI element that toggles its visibility). I checked prior versions, and it appears the elements began to look interactable in version dev.101

Seen on Win 10 Chrome, for https://github.com/phetsims/QA/issues/122

**Comment by Denz1994** [comment]
Good catch. I believe I caught all of the immovable lines with the above commit. Could you try in master @EthanWJohnson?

**Comment by EthanWJohnson** [comment]
Looks good; all of the lines no longer appear clickable.
