### ISSUE TITLE
RIAW left then right click issue present in M&S

### ISSUE THREAD

**Issue by ghost** [phetsims/masses-and-springs#277]
@Denz1994, I'm not sure this warrants an issue, but I wanted to notify you and document the fact that for phetsims/QA/issues/122, M&S has the same issue documented in phetsims/resistance-in-a-wire/issues/147. @jonathanolson created phetsims/scenery/issues/803 in response. It seems like there might be some changes to scenery that will resolve this issue, but perhaps not.
![ms](https://user-images.githubusercontent.com/31285590/40555296-d72ef834-6005-11e8-9906-cb327631e8e4.gif)

**Comment by Denz1994** [comment]
It seems that @jonathanolson is working on this in phetsims/scenery#803, but its current status is awaiting @ariel-phet for prioritization. Thanks for tracking in an affected sim, but I'll wait for @jonathanolson 's work before implementing any of my own. This doesn't seem sim code related though. 

Tagging @jonathanolson. If this bug isn't fixed from scenery work then he may have input on this matter.
