### ISSUE TITLE
Line drawn when mass moves

### ISSUE THREAD

**Issue by ghost** [phetsims/masses-and-springs#278]
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.13.4

<b>Browser</b>

Firefox 60.0.1

<b>Problem Description</b>

For phetsims/QA/issues/122. A line is "drawn," i.e. is left behind, when a mass is moved next to a mass that is slightly bobbing.

<b>Steps to Reproduce</b>

1. Go to the Intro screen or the Vectors screen.
2. Attach the 250g mass and the orange mass. (It doesn't have to be these masses; some other masses work. Thus far, the 50g and pink masses don't work.)
3. Stop the masses from moving.
4. Nudge the orange mass.
5. Move the 250g mass up or down.

<b>Visuals</b>

You have to click on the gif to see the line:

![msbug](https://user-images.githubusercontent.com/31285590/40570832-3d556c74-604c-11e8-9ce8-36aa86b044ef.gif)

This is a closeup of the orange mass:

![ms2](https://user-images.githubusercontent.com/31285590/40570856-86689c2e-604c-11e8-922f-ed62a91fc59f.gif)

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Masses and Springs‬
URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.102/phet/masses-and-springs_all_phet.html
Version: 1.0.0-dev.102 2018-05-21 16:49:55 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Language: en-US
Window: 1440x723
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"aaa0d77a","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"griddle":{"sha":"f9afbaec","branch":"master"},"joist":{"sha":"0d2b102d","branch":"master"},"kite":{"sha":"bd06199c","branch":"master"},"masses-and-springs":{"sha":"577e8758","branch":"master"},"phet-core":{"sha":"49911783","branch":"master"},"phet-io":{"sha":"545d86c9","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"1b254bcf","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"588f22fb","branch":"master"},"scenery-phet":{"sha":"b31317ca","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"9ebf1a6c","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"}}

</details>

**Comment by ghost** [comment]
@Denz1994, so far as I know, it's only an issue on macOS/FF. I can't consistently reproduce this with the exact same set of conditions. Sometimes I need to use a different set of masses, or move the right mass instead of the left mass, but I can usually reproduce the ghost line if I mess around with it for a bit.

**Comment by jonathanolson** [comment]
Yup, basically it seems like a bug in certain SVG implementations that don't properly repaint some regions.

One potential workaround would be to wrap each mass with an invisible rectangle that is slightly larger than the actual mass. Thus when it redraws things, the region it repaints will be slightly larger, and thus will not include the artifact.

Let me know if it would be good to collaborate on this.

**Comment by Denz1994** [comment]
Okay, this makes sense. I don't know why certain regions wouldn't get painted though. Could it have to do with the gradients on the massNodes? Perhaps, the whole gradient isn't completely being painted before the next step is being called.

I added a background Rectangle with bounds slightly larger than the mass to compensate for the paint callbacks. Could you try in master @lmulhall-phet? 

It would be good to also see if the springNodes replicates this behavior because each ring in the spring is three different segments. I tried switching on all the options on the vectors screen and having two masses oscillate quickly while changing the size of the sim screen. I wasn't able to get any ghost lines, but then again I'm not on a low-performance machine.

**Comment by jonathanolson** [comment]
> I don't know why certain regions wouldn't get painted though. Could it have to do with the gradients on the massNodes? Perhaps, the whole gradient isn't completely being painted before the next step is being called.

It's possible. It totally depends on the browser code, their optimizations, etc. If we ever DO discover a consistent trigger for browser-specific bugs, it may be possible to work around it generally. So far it hasn't been worth the time to discover that (would probably take a while).

**Comment by Denz1994** [comment]
Understandable, thanks for the input @jonathanolson.

**Comment by phet-steele** [comment]
@jonathanolson this just looks like another one for https://github.com/phetsims/john-travoltage/issues/193 IMO.

**Comment by ghost** [comment]
@Denz1994, I'm still seeing the ghost line in master.

**Comment by Denz1994** [comment]
Just adding this snapshot from Pendulum Lab, because it has the same bug. I could not reliably reproduce it though. I found that it goes away if a pendulum stops oscillating. 
![image](https://user-images.githubusercontent.com/13894380/40855890-e32e9b32-65a3-11e8-8a2d-ee12e7592ff8.png)

**Comment by Denz1994** [comment]
After review with @jonathanolson, the current solution for this bug is sim specific and will most likely require more work in common code. Since this is present in other published sims and isn't sim breaking, can we defer this issue @ariel-phet? Assigning to @ariel-phet for input.

**Comment by Denz1994** [comment]
Closing this issue as it is related to a larger issue in https://github.com/phetsims/scenery/issues/810.
