### ISSUE TITLE
Vectors and forces should be quelled after a certain threshold.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#279]
Similar to the point brought up in https://github.com/phetsims/masses-and-springs/issues/235#issuecomment-391097298, should we limit the visibility of small vectors. At some point they start to look like straight lines. 

![image](https://user-images.githubusercontent.com/13894380/40579996-3f80240a-6103-11e8-8b89-0fb16351897e.png)

This is also present in pendulum lab. Noting here because of the similarities.

I believe tackling this problem with some logic that says if the velocity or acceleration ( haven't figured out which would be better yet) is below a certain threshold, then we hide the vector. Before going into this solution:

 @ariel-phet Can you think of a scenario where an extremely small oscillation as depicted in https://github.com/phetsims/masses-and-springs/issues/235#issuecomment-391097298 can also have a large velocity or acceleration?

 Also do we want to hide these vectors that start to look like straight lines?

**Comment by Denz1994** [comment]
Tagging @arouinfar as well.

**Comment by ariel-phet** [comment]
@Denz1994 @arouinfar 

1. There will not be a scenario where an extremely small oscillation could have large velocity or acceleration 

2. The vectors going to straight lines doesn't bother me horribly. This behavior only occurs (normally) on the lab screen where you can have velocity and acceleration displayed, and also have damping active. A normal use case on the vectors screen you have to try to make such a small osccillation (doable, but not a normal use case). 

3. So in general you are watching the vectors "decay" -- it is not a surprise that they are fading to nearly nothing, so I don't think the straight line is confusing. In addition, if you were timing the decay, seeing the moment the vectors disappear tells you when the oscillation has truly stopped. Putting a different threshold will skew that timing a bit.

In my opinion, I would just leave the current behavior.

**Comment by arouinfar** [comment]
Good question @Denz1994. I think this situation is a bit different from #235. There, the small oscillation makes it impossible to accurately display the period trace, which could be pedagogically problematic. In the case of the vectors (on the Lab screen), the magnitude is decaying, so shrinking down to zero is exactly what the users should see. I agree with @ariel-phet -- let's stick with the current behavior.
