### ISSUE TITLE
pressing scenery buttons makes sim uninteractable

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/masses-and-springs#280]
Test device: iPad Air 2/ iPad 2/ iPad PRO

Operating System: iOS 11.2.5/ iOS 9.3.5/ iOS 11.3.1

Browser: Safari

For phetsims/QA/issues/122

Problem description: Once certain buttons are pressed the simulation continues, however all other buttons, sliders, and menu are not able to be used. After the button is pressed the only way to resolve the issue is to exit and reload the sim. The console does not show an error when this bug occurs.

Steps to reproduce: Select any of the following buttons on any screen: home screen icon, intro screen icon, vectors screen icon, energy screen icon, lab screen icon, PhET menu, pause button, step forward button, reset all button, any stop sign, or either the reset or play/pause button on the clock once it has been brought up. On certain screens where the sliders can be adjusted by hitting arrows on either side these arrows also break the sim. Screens containing graphs also break the sim when the info, and zoom in/out buttons are pressed. On the intro screen the button to switch to springs of various lengths also breaks the sim. 

Troubleshooting information (do not edit):
Name: ‪Masses and Springs‬
URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.102/phet/masses-and-springs_all_phet.html
Version: 1.0.0-dev.102 2018-05-21 16:49:55 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Language: en-US
Window: 1920x1012
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"aaa0d77a","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"griddle":{"sha":"f9afbaec","branch":"master"},"joist":{"sha":"0d2b102d","branch":"master"},"kite":{"sha":"bd06199c","branch":"master"},"masses-and-springs":{"sha":"577e8758","branch":"master"},"phet-core":{"sha":"49911783","branch":"master"},"phet-io":{"sha":"545d86c9","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"1b254bcf","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"588f22fb","branch":"master"},"scenery-phet":{"sha":"b31317ca","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"9ebf1a6c","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"}}

**Comment by Denz1994** [comment]
Could you test if this is reproducible on this latest [dev version](https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.106/phet/masses-and-springs_all_phet.html)?

This may have been fixed in master. Though I'm not sure what could be causing this on this specific platform.

**Comment by Denz1994** [comment]
Leaving to @JRomero0613 to close. This seems to be fixed in the last dev version.

**Comment by ghost** [comment]
@Denz1994, seems to be working using latest dev on iPad Pro.
