### ISSUE TITLE
Home Screen Select Issue

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/masses-and-springs#281]
Test device: iPad Air 2/ iPad 2/ iPad PRO

Operating System: iOS 11.2.5/ iOS 9.3.5/ iOS 11.3.1

Browser: Safari

For phetsims/QA/issues/122

Problem description: When selecting a screen from the home screen the selected screen does not become highlighted to be selected again, instead it loads the selected screen as soon as the user chooses what screen they want to use. May be related to #280.

Steps to reproduce: Load the sim and once at the home screen select a screen other than the intro screen and it will load the selected screen automatically.

Troubleshooting information (do not edit):
Name: ‪Masses and Springs‬
URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.102/phet/masses-and-springs_all_phet.html
Version: 1.0.0-dev.102 2018-05-21 16:49:55 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Language: en-US
Window: 1920x1012
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"aaa0d77a","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"griddle":{"sha":"f9afbaec","branch":"master"},"joist":{"sha":"0d2b102d","branch":"master"},"kite":{"sha":"bd06199c","branch":"master"},"masses-and-springs":{"sha":"577e8758","branch":"master"},"phet-core":{"sha":"49911783","branch":"master"},"phet-io":{"sha":"545d86c9","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"1b254bcf","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"588f22fb","branch":"master"},"scenery-phet":{"sha":"b31317ca","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"9ebf1a6c","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"}}

**Comment by Denz1994** [comment]
@JRomero0613 Is this reproducible on this [dev version](https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.106/phet/masses-and-springs_en_phet.html)?

**Comment by Denz1994** [comment]
I was able to reproduce the original bug on my iPhone 6 (iOS 11.3), but was not able to reproduce on this [dev version ](https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.106/phet/masses-and-springs_all_phet.html). Could you try this version as well? 

It is the "all_phet.html" link.

**Comment by ghost** [comment]
I can't reproduce the issue on an iPad Pro using [dev.106](https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.106/phet/masses-and-springs_all_phet.html).

**Comment by JRomero0613** [comment]
@Denz1994 I was not able to reproduce the bug on either version you gave me, the new versions also seem to have fixed issue #280 but I'll let you know once I have tested futher

**Comment by Denz1994** [comment]
Roger. Will be on standby.

**Comment by JRomero0613** [comment]
@Denz1994 It looks fine to me, the home screen works fine now and issue #280 is also resolved.

**Comment by Denz1994** [comment]
Great work. I'll assign both issues to @JRomero0613 to close.
