### ISSUE TITLE
Vectors Can be Grabbed to Pickup a Mass

### ISSUE THREAD

**Issue by JRomero0613** [phetsims/masses-and-springs#282]
Test device: PC Laptop/ iPad Air 2/ iPad 2/ iPad PRO/ Chromebook

Operating System: OS 17134.48/ iOS 11.2.5/ iOS 9.3.5/ iOS 11.3.1/ OS 67.0.3396.49

Browser: Chrome V. 66.0.3359.181/ Safari/ Safari/ Safari/ Chrome V. 67.0.3396.49

Problem description: For phetsims/QA/issues/122 when viewing the vectors screen with the velocity vector selected, clicking on this vector or any other vector makes the velocity vector disappear. The vector reappears when the simulation continues or is resumed, however it will stay gone for the duration of the pause.

Steps to reproduce: 
1. Load the vectors screen
2. Add any mass to either spring
3. Select the velocity vector and any additional vectors (works with only the velocity vector as well)
4. Disturb the mass
5. Pause the simulation using the pause button
6. Click on any vector including the velocity vector, the velocity vector should disappear.

Troubleshooting information (do not edit):
Name: ‪Masses and Springs‬
URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.102/phet/masses-and-springs_all_phet.html
Version: 1.0.0-dev.102 2018-05-21 16:49:55 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
Language: en-US
Window: 958x994
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"aaa0d77a","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"griddle":{"sha":"f9afbaec","branch":"master"},"joist":{"sha":"0d2b102d","branch":"master"},"kite":{"sha":"bd06199c","branch":"master"},"masses-and-springs":{"sha":"577e8758","branch":"master"},"phet-core":{"sha":"49911783","branch":"master"},"phet-io":{"sha":"545d86c9","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"1b254bcf","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"588f22fb","branch":"master"},"scenery-phet":{"sha":"b31317ca","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"9ebf1a6c","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"}}

**Comment by phet-steele** [comment]
@JRomero0613 what's happening here is that the velocity vectors can be used to drag a mass, so clicking them will pickup a mass and set its velocity back to zero.

@arouinfar did you want this behaviour?

**Comment by Denz1994** [comment]
I pushed a new [dev version](https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.107/phet/masses-and-springs_all_phet.html) without this behavior for comparison. Personally, I think it makes sense to not grab the vectors. Their mouse/touch areas are pretty small as well.

**Comment by arouinfar** [comment]
Nice observation @JRomero0613!

My initial thought was that making the vectors grabbable would make the moving masses easier to grab (though I don't remember it being an explicit design decision). In practice, I don't think it actually helps much, and at worst can look buggy.

I prefer the behavior in dev.107 @Denz1994.

**Comment by Denz1994** [comment]
The fix has been pushed to master. Can you confirm @JRomero0613 and close if fixed?

**Comment by JRomero0613** [comment]
@Denz1994 The fix in master has fixed the issue.
