### ISSUE TITLE
What happens to thermal energy when "Stop" is pressed?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#284]
@arouinfar I have a question about which is more correct:

In masses-and-springs, pressing the "stop" button will NOT clear any thermal energy.

In pendulum-lab, pressing the "stop" button DOES clear all thermal energy.

Maybe each is correct in its own sim, or should they both behave the same? I'm not an expert on the physics here and couldn't find a discussion. 😕

For phetsims/QA/issues/126.

**Comment by arouinfar** [comment]
@phet-steele pendulum-lab has the desired behavior. The thermal energy should clear because because the stop button is essentially resetting the system. I find it a bit surprising that masses-and-springs behaves differently, so I wonder if the undesired behavior may have crept in.

**Comment by phet-steele** [comment]
Been there since the first dev I found that charts thermal energy: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-dev.15/masses-and-springs_en.html (Sep 2017).

**Comment by Denz1994** [comment]
I didn't even realize the difference in behaviors. Thanks for noticing @phet-steele. Can you check master for this fix?

**Comment by phet-steele** [comment]
Magnifique 👍
