### ISSUE TITLE
1.0 Screenshot

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#288]
Hello @arouinfar! What were you thinking for a screenshot? (assign to @lmulhall-phet to make)

**Comment by arouinfar** [comment]
@lmulhall-phet here's the screenshot + alternates. The Intro screen should be the primary screenshot.

<img width="1440" alt="screen shot 2018-06-11 at 4 28 46 pm" src="https://user-images.githubusercontent.com/8419308/41260795-2cb86180-6d96-11e8-875a-e55e8bd992e8.png">
<img width="1440" alt="screen shot 2018-06-11 at 4 35 57 pm" src="https://user-images.githubusercontent.com/8419308/41260796-2cc7ee3e-6d96-11e8-8453-7a46a5f10bc9.png">
<img width="1440" alt="screen shot 2018-07-10 at 12 08 26 pm" src="https://user-images.githubusercontent.com/8419308/42528924-4e20a598-843a-11e8-9d8b-6e965a48a5bb.png">
<img width="1440" alt="screen shot 2018-07-10 at 12 14 27 pm" src="https://user-images.githubusercontent.com/8419308/42529147-e1ff55a2-843a-11e8-9104-691cf4f2ff93.png">

**Comment by arouinfar** [comment]
For #1.

**Comment by arouinfar** [comment]
@lmulhall-phet not sure if you've gotten started on these or not, but I'd like to tweak screenshots 3 and 4, so reassigning myself.

**Comment by arouinfar** [comment]
I updated the 3rd and 4th screenshots in https://github.com/phetsims/masses-and-springs/issues/288#issuecomment-396409871. Back to you, @lmulhall-phet.

**Comment by Denz1994** [comment]
@KatieWoe @lmulhall-phet  Have screenshots been taken with the new procedure in #310? @jonathanolson mentioned that they should be added to both branches in the assets directory.

**Comment by arouinfar** [comment]
@KatieWoe we generally take screenshots during the RC process, after last-minute pixel polishing wraps up. For MAS, that was probably around rc.3 or so, so please go ahead and take/commit the screenshots so we can move forward with publication.

**Comment by KatieWoe** [comment]
@arouinfar @Denz1994 just added to master branch and 1.0 branch.  Take a look and let me know if they work.

**Comment by arouinfar** [comment]
The screenshots look good to me @KatieWoe!

> @jonathanolson mentioned that they should be added to both branches in the assets directory.

@Denz1994 to clarify, did you mean both the master and 1.0 branches? There's also the accessibleScreenView branch -- not sure if the screenshots need to be checked in there as well.

**Comment by Denz1994** [comment]
They should also be checked into the accessibleScreenView branch as well. Thanks for the clarification @arouinfar.

**Comment by arouinfar** [comment]
@KatieWoe can you add the screenshots to the accessibleScreenView branch?

**Comment by KatieWoe** [comment]
@arouinfar Done

**Comment by arouinfar** [comment]
:+1:
