### ISSUE TITLE
"Gravity" heading should not disappear when on Planet X

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#289]
For https://github.com/phetsims/QA/issues/129

Switching to Planet X correctly replaces the slider with the string, "What is the value of gravity?". However, the "**Gravity**" heading should remain visible, as in Pendulum Lab (bottom).
![image](https://user-images.githubusercontent.com/8419308/41319062-d32c9c22-6e57-11e8-9d93-58a6741776a0.png)  

![image](https://user-images.githubusercontent.com/8419308/41319211-4ca933ee-6e58-11e8-8cf3-6ec11048a42c.png)

**Comment by Denz1994** [comment]
Could you check this in master @arouinfar? I believe this was fixed.

**Comment by arouinfar** [comment]
👍

**Comment by KatieWoe** [comment]
This no longer seems to be fixed in RC2
It does seem to be fixed in master.
for phetsims/QA/issues/153

**Comment by KatieWoe** [comment]
Closing

**Comment by KatieWoe** [comment]
This no longer seems to be fixed in rc.3 For phetsims/QA/issues/165
Edit: Sorry, wrong issue
