### ISSUE TITLE
Switching Gravity from Planet X to Custom reveals unknown g

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#290]
For https://github.com/phetsims/QA/issues/129

1. On startup go to Lab, default gravity is Earth. (Bug is on all screens, but easier to spot on Lab, which has a readout.)
![image](https://user-images.githubusercontent.com/8419308/41319048-c79015ba-6e57-11e8-9d41-fbbb7a7508c8.png)
2. Switch to Planet X
![image](https://user-images.githubusercontent.com/8419308/41319062-d32c9c22-6e57-11e8-9d93-58a6741776a0.png)
3. Switch to Custom, Planet X gravity is now revealed
![image](https://user-images.githubusercontent.com/8419308/41319073-dd823178-6e57-11e8-9861-e91369cb9eb6.png)

In this case, the slider thumb should be at 9.8 m/s^2, which is the most recent non-mystery value of g.

@Denz1994 the desired behavior is present in Pendulum Lab, so it may be helpful to compare.

**Comment by Denz1994** [comment]
I believe this should fix the issue. We needed to prevent setting a value for Body.CUSTOM.gravity when the previous body was being set to Body.PLANET_X. Can you check in master @arouinfar?

**Comment by arouinfar** [comment]
Close, but not quite @Denz1994.

Custom, in general, shouldn't have a saved state. Suppose the user sets g=17, then switches to Earth. When returning to Custom, the thumb would stay at 9.8, not jump to 17. This behavior was correct in rc.1. Selecting Custom from the combobox doesn't generally change the value of g.
 
The only exception to this is Planet X. Going Planet X > Custom should move the thumb back to whatever the value of g was immediately before Planet X was selected. 

The behavior is correct in Pendulum Lab, so you might want to play with it there.

**Comment by Denz1994** [comment]
Sorry I missed that use case. Can you double check master for the fix @arouinfar?

**Comment by arouinfar** [comment]
👍

**Comment by KatieWoe** [comment]
Reopening for phetsims/QA/issues/153.  This seems to be happening again in RC 2

**Comment by KatieWoe** [comment]
Looks good

**Comment by Denz1994** [comment]
Closing this issue. Thanks for the feedback @KatieWoe.

**Comment by Denz1994** [comment]
If you select a Custom body in the combo box without adjusting any of the settings, the sim crashes. This is due to having a null oldGravity value. Fix is pending.

**Comment by Denz1994** [comment]
This was a relatively quick patch. The bug was fixed in master. Closing.

**Comment by KatieWoe** [comment]
This no longer seems to be fixed in rc.3 For phetsims/QA/issues/165

**Comment by Denz1994** [comment]
I reverted some logic pushed from https://github.com/phetsims/masses-and-springs/commit/98951d448882c664d8a37849c69a382307ea4c65. Can you check master to assure this is fixed @KatieWoe?

**Comment by phet-steele** [comment]
@Denz1994 @arouinfar I'm going to be super nit-picky about the current logic, and you can choose to ignore me. The logic prevents the Planet X value from being applied when switching from Planet X -> Custom by using the user's previously stored gravity value. For example, if my gravity was 10.7, then Planet X -> Custom, my gravity would be back to 10.7. However, if my stored value is equal to Planet X (14.2), then doing Planet X -> Custom will not restore my previous value to 14.2. I've seen the gravity change to 14.1, 14.3, and 14.4 (not sure how it decides what value to use). Again, I'm just being nit-picky, but maybe a perceptive student might realize how the system works and deduce that 14.2 is a "special" value.

In other news, this issue looks fixed on my end (on master).

**Comment by phet-steele** [comment]
If it were me, I would have gravity switch back to the stored value without giving diddly-squat if that value was the same as Planet X. Pretty much just what @arouinfar said in https://github.com/phetsims/masses-and-springs/issues/290#issuecomment-398569154.

> The only exception to this is Planet X. Going Planet X > Custom should move the thumb back to whatever the value of g was immediately before Planet X was selected.

...regardless of the previous value of g.

**Comment by KatieWoe** [comment]
Problem seems fixed in master.  I do agree with Steele that the specific value of 14.2 doesn't need to be avoided if it was entered into custom then Planet X was selected and then custom was.  It's probably an unlikely case, but it might be worth looking at.

**Comment by arouinfar** [comment]
@phet-steele great catch. This behavior is never desired:

>  However, if my stored value is equal to Planet X (14.2), then doing Planet X -> Custom will not restore my previous value to 14.2. I've seen the gravity change to 14.1, 14.3, and 14.4 (not sure how it decides what value to use). Again, I'm just being nit-picky, but maybe a perceptive student might realize how the system works and deduce that 14.2 is a "special" value.

I completely agree with this sentiment:
 >>Going Planet X > Custom should move the thumb back to whatever the value of g was immediately before Planet X was selected.
>
>...regardless of the previous value of g.

@Denz1994 if the previous custom value happens to be 14.2, then going Planet X > Custom should not move the thumb.

**Comment by arouinfar** [comment]
Looks good @Denz1994!

**Comment by jeffroy11** [comment]
what is the gravity values of planet x?
anyone who can tell me
