### ISSUE TITLE
Changing mass detaches mass from spring when paused & off-screen

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#291]
For https://github.com/phetsims/QA/issues/129

The mass detaches itself from the spring if its mass is changed while it is hanging off-screen.

1. Attach adjustable mass to spring
2. Set k to min, mass to max, then click stop. Mass is off-screen.
3. Pause sim.
4. Reduce mass, and it detaches itself from the spring.

![image](https://user-images.githubusercontent.com/8419308/41319583-924010ca-6e59-11e8-9231-78105bd8e920.png)

This only occurs when the sim is paused AND the mass is off-screen. Changing the mass when paused OR when the mass is off-screen behaves normally.

**Comment by ghost** [comment]
![ms](https://user-images.githubusercontent.com/31285590/41625293-8a83ea1a-73d5-11e8-8462-cb6907d74239.gif)

**Comment by arouinfar** [comment]
Thanks for the screen capture @lmulhall-phet!

**Comment by Denz1994** [comment]
This one was a bit tricky. Could you check to see if this is fixed in master @arouinfar?

**Comment by ghost** [comment]
@Denz1994, it seems to be fixed in master. @arouinfar, can you confirm?

**Comment by arouinfar** [comment]
It's looking good @Denz1994!
