### ISSUE TITLE
More Pixel Polishing 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#292]
For https://github.com/phetsims/QA/issues/129

- [x] On Vectors, it looks like the vector checkboxes may be a tad larger than the top group of checkboxes. Here's a comparison. It's subtle, but does look slightly different. (Edit: Is it possible that there's a slight difference in font size causing this issue?)
![image](https://user-images.githubusercontent.com/8419308/41379760-1c8b45e4-6f20-11e8-88af-cc59c3aa3a0b.png)

- [x] Increase toolbox height 10% (relative height of panel and icons is good, but everything could a bit taller).

**Gravity and Damping sliders should be formatted like Gravity and Friction sliders and Pendulum Lab (right).  In particular:**
- [x] Reduce height of gravity combobox
- [x] Increase padding between combobox and "Damping" title
- [x] Increase padding between "Damping" title and slider (should be the same as padding between "Gravity" and slider). 
- [x] Increase readout font size to same size at title (14pt, I believe)
<img src="https://user-images.githubusercontent.com/8419308/41380556-913a4c3a-6f22-11e8-9f5a-ef2d69d2f407.png" width=300>  <img src="https://user-images.githubusercontent.com/8419308/41380577-a012617a-6f22-11e8-92b8-e85309942e7a.png" width=300>

- [x] "Damping = 0" string should be aligned such that "Damping" doesn't shift when switching to screens with Damping slider.

**Format Spring Constant sliders like Spring Length slider:**
- [x] Increase font size of "Spring Constant #" title and min/max labels to match Spring Length 
- [x] Increase padding between slider title and max/min label to match Spring Length
- [x] Increase panel width to match Spring Length
![image](https://user-images.githubusercontent.com/8419308/41381069-b74758cc-6f23-11e8-857f-ef069cc34155.png) ![image](https://user-images.githubusercontent.com/8419308/41381082-c3a4f750-6f23-11e8-9921-ce85349db4f3.png)

**Tweaks to Mass Panel**
- [x] Increase readout font size to match updated Gravity readout (14 pt?)
- [x] Increase max/min labels to 12 pt
- [x] Move slider down a bit to increase padding between "Mass" title and min/max labels.
- [x] Make panel a bit taller to accommodate the above changes.
- [x] Move Mass panel left 20px so it isn't so tight against the spring.

**Comment by arouinfar** [comment]
@Denz1994 if you have any questions, please let me know. I'd also be happy to discuss over Zoom.

**Comment by arouinfar** [comment]
> @arouinfar Can you verify that this was corrected? I need a second eye to make sure.

@Denz1994 the checkboxes are not the same size. GitHub resized the screenshots, but the red line is the same length in both screenshots. Looks like the vector checkboxes are still a tad bit larger. 

![image](https://user-images.githubusercontent.com/8419308/41987039-4f1e5b9c-79f5-11e8-9926-1be9d2808ea3.png)
![image](https://user-images.githubusercontent.com/8419308/41987089-6ed64f58-79f5-11e8-9d0f-0fb38d5b6500.png)

**Comment by arouinfar** [comment]
@Denz1994 looks like these items haven't been addressed in master:
> 1. Increase readout font size to same size at title (14pt, I believe) 

Gravity readout is 12 pt, but should be increased to 14 pt to match "Gravity" title. Perhaps you need to make the readout box a tad bigger so the font can be larger.

> 2. Increase padding between slider title and max/min label to match Spring Length

Small/Large is still closer to the title than Short/Long
![image](https://user-images.githubusercontent.com/8419308/42235409-eaeaccf4-7eb4-11e8-8a74-7a6f98292e84.png)

> 3.  Increase panel width to match Spring Length

Spring Constant and Spring Length now have the same width, which is great. However, it looks like you ended up making the Spring Length panel narrower to match Spring Constant, which crowds the Short/Long labels. The Constant Parameter title/options are now also indented too much.

![image](https://user-images.githubusercontent.com/8419308/42235758-fbdaa51a-7eb5-11e8-8eb9-0830dd19ef7e.png)

* Keep Spring Length and Spring Constant panels the same width, but increase width by a few px. This will give min/max slider labels a bit more padding on the sides.
* Left-align Constant Parameter and radio options with "Short".


> 4. Increase readout font size to match updated Gravity readout (14 pt?)

Mass readout is currently a tad bit smaller than Gravity readout. Both readouts should be 14 pt.

**Comment by Denz1994** [comment]
Work in progress. Thanks for the feedback.

**Comment by Denz1994** [comment]
Good catch @arouinfar. Could you review master now?

**Comment by arouinfar** [comment]
@Denz1994 (1) and (4) look great. It doesn't look like any action was taken for (3).
> Keep Spring Length and Spring Constant panels the same width, but increase width by a few px. This will give min/max slider labels a bit more padding on the sides.
Left-align Constant Parameter and radio options with "Short".

It looks like (2) had some unintended consequences. The "Gravity" and "Damping"  titles have shrunken quite a bit. This is particularly noticeable if you switch between the Energy and Lab screens. The title should remain the same size -- compare to the Energy/Lab screens in Pendulum Lab.

You may also need to add an extra pixel of whitespace between the bottom of the readout and the slider because because the readout and max label are looking pretty cramped. Any additional padding added to the Gravity slider should apply to Damping as well, so that their formatting remains the same.

**Comment by Denz1994** [comment]
You are right about (3). I need a second eye to review the other changes @arouinfar.

**Comment by arouinfar** [comment]
Everything looks great @Denz1994. Thanks!
