### ISSUE TITLE
Allow panel/toolbox on right side to expand 50px before scaling down strings

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#293]
For https://github.com/phetsims/QA/issues/129

There are a lot of long strings in this sim, which may get even longer when translated. When reviewing `?stringTest=double` I noticed that the panel remains the same width, so the strings don't really have any room to grow.
<img src="https://user-images.githubusercontent.com/8419308/41553360-c98c5464-72ee-11e8-8184-cda53a43f4e0.png" width=300> <img src="https://user-images.githubusercontent.com/8419308/41553380-dfeae306-72ee-11e8-82aa-1d007d19df87.png" width=300>

@Denz1994 can you allow this panel to expand by 50px before scaling down the strings? Keep in mind that the toolbox width should also increase so it matches the panel width. 

This has been a strategy that has been used in other sims, such as Capacitor Lab: Basics.

![image](https://user-images.githubusercontent.com/8419308/41553532-4392effc-72ef-11e8-9f91-6b225a5d96a2.png)
![image](https://user-images.githubusercontent.com/8419308/41553559-5607ca36-72ef-11e8-95c1-1b2afdb41af2.png)

**Comment by arouinfar** [comment]
It also looks like all three reference line checkboxes seem to have the same font size. However, I think "Movable Line" has room to be a bit larger, so I'm not sure why it's so small. 

In the above CLB example, "Current Direction" is a tad bit smaller because it is a long string, while "Bar Graph" was short enough to keep its original size.

Edit: Decided to open a separate issue for this - #296.

**Comment by Denz1994** [comment]
Can you check master @arouinfar? I expect that the panel widths are still too small, but should the Movable Line string be given more room to expand?

**Comment by arouinfar** [comment]
@Denz1994 the panel width is looking pretty good, actually. I think the checkbox strings will all have adequate room to maintain a reasonable font size for most (if not all) locales. However, I'm noticing two undesirable side effects. 

First, the Gravity and Damping sliders looks pretty horizontally cramped. Additionally, the Vector checkboxes are no longer left-aligned with the first group of checkboxes. Compare rc.1 (top) to master (bottom).

![image](https://user-images.githubusercontent.com/8419308/42838030-eb670b44-89bc-11e8-9bac-e08c8198aebb.png) ![image](https://user-images.githubusercontent.com/8419308/42838055-f4959d20-89bc-11e8-8ea5-52753ad5cbb9.png)

**Comment by Denz1994** [comment]
Nice thanks for the feedback.

**Comment by Denz1994** [comment]
Can you check master now @arouinfar? There was also a bug fix. Should the gravity section be expanded more?

Note to self: The disparity in the two versions above is due to the optionsPanel getting wider, not the content getting smaller.

**Comment by arouinfar** [comment]
@Denz1994 master is still looking about the same as https://github.com/phetsims/masses-and-springs/issues/293#issuecomment-405682414, even after pulling all repos. The Vector checkboxes have moved over a bit, but are still not left-aligned with the other checkboxes. Gravity and Damping still looking equally squished to me.

![image](https://user-images.githubusercontent.com/8419308/42843274-d678b182-89cc-11e8-81da-03bed5a42f95.png)

**Comment by Denz1994** [comment]
I tracked down the misalignments in a previous set of commits. Can you try master @arouinfar? Thanks for the feedback.

**Comment by Denz1994** [comment]
What do you think about master now @arouinfar?

**Comment by arouinfar** [comment]
Looks great! Thanks @Denz1994.

**Comment by arouinfar** [comment]
@Denz1994 in reviewing #305 , I noticed that the panel doesn't appear to be expanding more than a few px (if at all) for long strings.
![image](https://user-images.githubusercontent.com/8419308/43348479-6ad414b0-91b7-11e8-8f31-0323e4496260.png)
![image](https://user-images.githubusercontent.com/8419308/43348485-74f0fc24-91b7-11e8-899b-595d5f4c5b9f.png)

**Comment by arouinfar** [comment]
By the way, it appears that this was unfixed in rc.2
![image](https://user-images.githubusercontent.com/8419308/43348617-3c25bc26-91b8-11e8-9fa0-18158df193fb.png)
![image](https://user-images.githubusercontent.com/8419308/43348636-4ce602a0-91b8-11e8-989e-8dba56e62d9a.png)

**Comment by Denz1994** [comment]
The panels no longer have maxWidths and instead the contents have adjusted maxWidths. The toolboxes on each screen have widths that match the optionsPanels respectively. Could you review master @arouinfar to make sure that there is adequate spacing for i18n?

**Comment by arouinfar** [comment]
Looks good to me, thanks @Denz1994!
