### ISSUE TITLE
"Mass" title occluded by icon under i18n

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#294]
For https://github.com/phetsims/QA/issues/129

The string should expand to the right so that the relative spacing between the icon and "Mass" remains the same.

![image](https://user-images.githubusercontent.com/8419308/41554833-32df5f70-72f3-11e8-9e2b-3822bae026e7.png)

**Comment by Denz1994** [comment]
There are some limitations on how the title expands based on the common code. Without creating a new numberControl scheme for this specific case, could we try reversing the massString and its icon? 

This pattern of description/readout/title on the left followed by its icon on the right seems to be standard for the other panels as well, such as the reference line panel and vector indicator panel. It would also save a lot of time. Is this acceptable @arouinfar? Check in master.
