### ISSUE TITLE
Damping=0 gets misaligned under i18n

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#295]
For https://github.com/phetsims/QA/issues/129

When reviewing `?stringTest=double`, I noticed that "Damping = 0" gets misaligned. The string should maintain left-alignment with "Gravity".

<img src="https://user-images.githubusercontent.com/8419308/41554295-abdd2d0a-72f1-11e8-88c4-40eb3ecc65ab.png" width=300>  <img src="https://user-images.githubusercontent.com/8419308/41554305-b8920b38-72f1-11e8-8360-67a8a63f5b88.png" width=300>

**Comment by Denz1994** [comment]
@arouinfar Can you confirm this has been fixed in master?

**Comment by arouinfar** [comment]
Alignment is looking good!
