### ISSUE TITLE
Energy Legend suggestions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/masses-and-springs#297]
Noted while working on https://github.com/phetsims/joist/issues/413.

masses-and-springs and pendulum-lab both have a dialog titled "Energy Legend"., but their styling is different. 

masses-and-springs:

![screenshot_678](https://user-images.githubusercontent.com/3046552/41627229-ab3e699a-73dc-11e8-8180-b338bf1835db.png)

pendulum-lab:

![screenshot_679](https://user-images.githubusercontent.com/3046552/41627232-b09d7f16-73dc-11e8-811e-4882053d9dce.png)

Consider making the title larger and the font of the symbols bold in masses-and-springs.

**Comment by Denz1994** [comment]
Can you double check the fixes in master @arouinfar?

**Comment by arouinfar** [comment]
Looks great, thanks @Denz1994!

**Comment by arouinfar** [comment]
While this was not technically for https://github.com/phetsims/QA/issues/129, I'm going to go ahead and tag it so it shows up in the RC issue. That way, it'll be easier to keep track of the changes made.
