### ISSUE TITLE
Total energy incorrectly negative

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#298]
For https://github.com/phetsims/QA/issues/129

A mass oscillating off-screen will at times have negative gravitational potential energy.
![image](https://user-images.githubusercontent.com/8419308/41683620-653b5716-7498-11e8-8219-c8f10c468e2c.png)

However, when stopping this mass, the total energy becomes negative, which would only be correct if mgh > 1/2*k*x^2.

In this situation, k = 6 N/m, x = 1.5 m, h = -0.53 m. 
Gravitational Potential Energy = mgh = (0.3)(30)(-0.53) = -4.77 J
Elastic Potential Energy = 0.5*kx^2 = (0.5)(6)(1.5^2) = 6.75 J
Total Energy = 6.75 - 4.77 = 1.98 J

![image](https://user-images.githubusercontent.com/8419308/41684713-8d15368c-749b-11e8-86a7-1183649dc709.png)

**Comment by arouinfar** [comment]
Accidentally opened too soon, please disregard.

**Comment by Denz1994** [comment]
I can replicate this by setting up the spring constant, gravity and mass with the same values as described above. Then as the mass is oscillating, press the stop button. Now toggle the spring constant to a low value and you should be able to make the total energy negative. It may help to zoom out on the energy graph.

I don't know if this is a bug though. We can create a situation where we have a large negative GPE and a small EPE. This would make a negative total energy. I thought the negative sign is only relevant to direction in this scenario.

**Comment by arouinfar** [comment]
@Denz1994 negative total energy is fine, so long as |GPE| > EPE. However, in this case, EPE > GPE, so total energy should be positive.

**Comment by Denz1994** [comment]
Height is measured from the bottom of the mass to the "height = zero" line. Is this correct?
Displacement is measured from the spring natural length to the end of the spring after displacement.

**Comment by arouinfar** [comment]
> Height is measured from the bottom of the mass to the "height = zero" line. Is this correct?

Yes, that's completely correct, and why the height is closer to -77 cm, making |GPE| > EPE. My bad!

**Comment by Denz1994** [comment]
At least it wasn't a model error. Whew!
