### ISSUE TITLE
Thoughts for a Basics version

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#299]
For several reasons it would be good to consider a basics version for this simulation. 

1. The current simulation includes a number of advanced features that would not be appropriate for a younger audience, but the topic would still be interesting to explore for student below early high school.

2. Our collaborators at Go-Lab were interested in a version of this simulation for younger audiences

We should first consider what learning goals we want to address, but I am going to include some of the discussion with Go-Lab in this issue. We think it would be best to present them with some mockups and go from there as they appear to have some fairly ambitious thoughts about the capabilities of elementary students.

**Comment by ariel-phet** [comment]
From Go-Lab:

> In our cooperation we (from our perspective) like to achieve two goals:
> 
> - Extend the coverage of topics from our European primary education curriculum, and/or
> - Bring existing sims in terms of interface closer to primary education
> 
> And of course this needs to be done within the technical possibilities (and in relation to that the available budget).
> 
> It is hard for us to estimate how (technically) difficult some of our suggestions are to be realized or how expensive it is to extend/simplify an existing sim.  Maybe we can try to reverse the order of working. In the attachment you see part of the curriculum analysis we made with indicated if a topic is covered by (a) lab(s) in Golabz. A brief summary in words I given at the end of this mail.
> 
> Is it maybe an idea that you have a quick look and let us know where you see any possibilities?
> 
> Thanks and regards,
> 
> Ton
> 
> Mathematics
> The topics within the category numbers and calculation that could be used for new labs are using number with more than two digits, comparing and ordering numbers, rounding up numbers, counting in multiples, the concept of decimals numbers and percentages, the method of long division, dividing and multiplying fractions, and numerical powers. 
> With reference to measurement, three dimensional shapes, using measurements for money, time, length/height, mass/weight, temperature, capacity, and comparing, ordering, and converting them are relevant.
> Geometry topics that could be used in new labs are triangles and calculating their angles, perimeters, and volumes, and identifying locations.
> With respect to algebra, the concept of equality and inequality, how to classify events as certain, possible, and impossible to happen, how to recognise numerical patterns, how to express powers, and the priorities in performing the various calculations are not part of a lab yet.
> 
> Science
> With regard to materials, processes, and states of matter, there are numerous labs available. Topics that could be added to the Go-Lab sharing platform are identify objects and the material they are made from, identify and compare the suitability of everyday objects, energy and the human body, properties of daily materials, compare and group rocks and fossils, properties of air, evaporation and condensation in the water cycle, mixtures and solutions, magnetic forces, how sounds are made, waste management, energy saving techniques, describe electricity related phenomena by using molecules, acids, current energy sources and conscious use, and ardency.
> Space and time labs could be added about two topics: weather, and volcanoes and earthquakes.
> With respect to plants and nature, labs about the topics classification of plants, identification of their parts, biodiversity, food chains, and cells could be added.
> With reference to animals and humans, no labs are currently available on the Go-Lab sharing platform for primary education.

[list_of_topics_and_labs.pdf](https://github.com/phetsims/masses-and-springs/files/2128924/list_of_topics_and_labs.pdf)

**Comment by ariel-phet** [comment]
Go-lab initial thoughts on a basics version here:

[Masses and springs.pdf](https://github.com/phetsims/masses-and-springs/files/2128935/Masses.and.springs.pdf)

To these suggestions I replied the following (and to note the above github comment with a list of topics and such happened after our exchange about a basics version and my concerns with the design suggestions):

> Before we delve to deeply into your suggestions for Masses and Springs, a few notes.
> 
> 1. It would be good if you could list out the specific learning goals you want to address with the basics version. It seems you are wanting to compare to identical cases (like two of the same masses on the same length springs), but for our process it is important to start with the learning goals. For instance, do you want students to see that natural length is a property of the spring? Do you want them to focus on how wire thickness affects spring constant?
> 
> 2. It will be MUCH more expensive and time consuming to add new features to the sim, its model, or the interaction. So for instance, your suggestion of a zoom-in view on the wire would be very difficult, as there is currently no support for this kind of feature and it would require a fair bit of design and coding. We usually think of "basics" 
> versions as a subset of features with potentially different scaffolding. 
> So for instance, having certain features on by default (like Natural
> Length) is no problem at all, but adding entirely new features is a very different endeavor.
> 
> 3. Once we have your specific learning goals, we should discuss the potential design changes in more depth. We had very specific reasons for not allowing certain variable changes on certain screens. Since the spring constant is related to the length of the spring, the number of coils, and the thickness of the wire, we chose to isolate some of those variables. Having all of those simulaneously adjustable leads to some difficult situations and interpretations.
> 
> 4. It sounds like you are envisioning the basics version to be a single screen, but from the design pieces you are suggesting, we would probably split it up into several screens, again, knowing your learning goals will be key to making these decisions. Likely it would be best to scaffold the learning by splitting up the learning goals over several screens.

**Comment by arouinfar** [comment]
We've now had a few brainstorming meetings, and have discussed our preliminary design with our collaborators at Go-Lab.  There are a few small design concerns to discuss (e.g. extra 250 g mass, gravity controls in accordion menu) but the overall design is largely mapped out. 

I've Slacked @Denz1994 to set up a time to discuss the design/goals.

I think we've fulfilled the original intensions for this issue, so I'm going to go ahead and close.
