### ISSUE TITLE
masses-and-springs_en.html is stale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/masses-and-springs#3]
`masses-and-springs/js/masses-and-springs_en.html` looks like it's out of date. The .html files for requirejs mode testing were updated for all sims awhile back, probably while this sim was removed from active-repos.  I think that running `grunt generate-development-html` will do the trick, but you might want to confirm with @jonathanolson (author of that grunt task).

**Comment by mattpen** [comment]
@jonathanolson @pixelzoom - It looks like @samreid made some updates to this file for phet-io.  When I ran `grunt generate-development-html` it just deleted some of his changes.  Is the file correct in its current state in master?

**Comment by pixelzoom** [comment]
There shouldn't be anything specific to PhET-iO in any sim's development html file.  The development html file (repoName_en.html, at the top level of the repo) is for testing non-PhET-iO sims in requirejs mode.  But you'll need to check with @samreid about why that file contained anything related to PhET-iO; perhaps it was some quick test that was inadvertently pushed.

**Comment by samreid** [comment]
I may have forgot to update a template, I'll look into this when back to work.

Sam

On Feb 13, 2016, at 12:13 PM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:

There shouldn't be anything specific to PhET-iO in any sims' development html file. The development html file (repoName_en.html, at the top level of the repo) is for testing non-PhET-iO sims in requirejs mode. But you'll need to check with @samreidhttps://github.com/samreid about why that file contained anything related to PhET-iO; perhaps it was some quick test that was inadvertently pushed.

##

**Comment by mattpen** [comment]
I pulled the most recent changes to chipper, added a `$HOME/.phet/build-local.json` file with the brand value, then ran `grunt generate-development-html`.  Afterwards there were no differences from the current state of master so the html file appears to no longer be stale.
