### ISSUE TITLE
string behind mass

### ISSUE THREAD

**Issue by ghost** [phetsims/masses-and-springs#300]
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 10.13.5

<b>Browser</b>

All browsers

<b>Problem Description</b>

For phetsims/QA/issues/129.

With `?stringTest=double`, this...

![screen shot 2018-06-27 at 1 41 57 pm](https://user-images.githubusercontent.com/31285590/41995901-73387286-7a10-11e8-9daf-533ab3622e02.png)

...occurs in the Energy screen and the Lab screen.

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Masses and Springs‬:‪Masses and Springs‬
URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-rc.1/phet/masses-and-springs_all_phet.html?stringTest=double
Version: 1.0.0-rc.1 2018-06-08 18:47:28 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1920x983
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"37d5839c","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bc1f66fe","branch":"HEAD"},"dot":{"sha":"bd4d7035","branch":"HEAD"},"griddle":{"sha":"7be25724","branch":"HEAD"},"joist":{"sha":"85b10c15","branch":"HEAD"},"kite":{"sha":"3b76b24a","branch":"HEAD"},"masses-and-springs":{"sha":"e8678c16","branch":"HEAD"},"phet-core":{"sha":"e0cec207","branch":"HEAD"},"phet-io":{"sha":"e5c7148f","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"HEAD"},"phet-io-wrappers":{"sha":"f3701e8d","branch":"HEAD"},"phetcommon":{"sha":"80414edb","branch":"HEAD"},"query-string-machine":{"sha":"1f2322e4","branch":"HEAD"},"scenery":{"sha":"3b05db54","branch":"HEAD"},"scenery-phet":{"sha":"f37bff38","branch":"HEAD"},"sherpa":{"sha":"ded365aa","branch":"HEAD"},"sun":{"sha":"00b9c74c","branch":"HEAD"},"tandem":{"sha":"3e1c8fd3","branch":"HEAD"},"twixt":{"sha":"050e8f19","branch":"HEAD"}}

</details>

**Comment by arouinfar** [comment]
Good catch @lmulhall-phet! This was addressed in #294 and has been fixed in master.

**Comment by ghost** [comment]
Wow, I can't believe I didn't see that issue. Thanks, @arouinfar.

**Comment by arouinfar** [comment]
No problem! I logged a few i18n issues last week (all of them linked the RC issue), and @Denz1994 has addressed most of them.
