### ISSUE TITLE
Adding M&S to "Reading List" on iPad 2 doesn't work

### ISSUE THREAD

**Issue by ghost** [phetsims/masses-and-springs#301]
For phetsims/QA/issues/129.

On iOS 9.3.5 + Safari 9.0, adding M&S to "Reading List" (HTML download) doesn't work.

When I try to interact with the simulation, this happens:

![img_0201](https://user-images.githubusercontent.com/31285590/42542656-1d7461fc-8465-11e8-9042-86f4abaf9d9e.JPG)

The sim is stuck like this and is otherwise unresponsive.

I will tether the iPad tomorrow morning and look into this further...

**Comment by ghost** [comment]
I'd like to make a retraction: the "Reading List" feature does work as expected with two caveats...

Caveat 1:

![img_0203](https://user-images.githubusercontent.com/31285590/42601174-f470cbc0-8521-11e8-9609-3273c9fb68d3.JPG)

For some reason there are numbers before the description of the simulation. I am seeing the same thing with Area Model Algebra 1.0.0-rc.3.

Caveat 2: The splash screen sometimes looks a bit odd, i.e. not centered. But this resolves itself.

What I was seeing in my first comment was simply abysmal performance. Performance is similar for other multi-screen sims.

I tethered the iPad, and there aren't any errors other than those related to not being connected to the internet.

I can look into this further, but I want a go-ahead. (It's such a small and obscure thing; I'm not sure it warrants further investigation.)

**Comment by phet-steele** [comment]
> For some reason there are numbers before the description of the simulation.

Those numbers are related to a11y and are expected to be there (pretty sure), albeit it's ugly and unfortunate that they have to be seen. I don't think the work to remove those numbers is worth the benefit.

**Comment by arouinfar** [comment]
> Those numbers are related to a11y and are expected to be there (pretty sure), albeit it's ugly and unfortunate that they have to be seen. I don't think the work to remove those numbers is worth the benefit. 

Agreed. I don't think it's worth the effort to remove the numbers.

> Caveat 2: The splash screen sometimes looks a bit odd, i.e. not centered. But this resolves itself.

@lmulhall-phet does this happen for other multi-screen sims, or is it specific to MAS?

**Comment by ghost** [comment]
The splash screen weirdness seems to be a problem with other multi-screen sims as well.

**Comment by arouinfar** [comment]
Thanks @lmulhall-phet!  In that case, I don't think @Denz1994 needs to do anything specific for MAS. 

That said, there should probably be some general issue in one of the common repos documenting the non-centered splash screen. Not sure what the best fit would be, so leaving that to @Denz1994 and/or @lmulhall-phet to decide.

**Comment by ghost** [comment]
Will do @arouinfar.

(EDIT: Note to self: I can't reproduce this consistently. The behavior is different each time a load a sim.)

**Comment by jessegreenberg** [comment]
Regarding the numbers, I don't think they are for a11y, but maybe they are related to Heartbeat.js.

**Comment by samreid** [comment]
In https://github.com/phetsims/joist/issues/382 and https://github.com/phetsims/joist/issues/470 we determined that "Save to Reading List" automatically saves a "snapshot" of the current DOM which is not automatically cleared when the page is loaded from the reading list.  That is most likely what is causing the duplicate rendering and interference.

**Comment by samreid** [comment]
> Regarding the numbers, I don't think they are for a11y,

Guessing here: maybe related to the cache buster?

**Comment by jessegreenberg** [comment]
Also guessing, but Heartbeat.js adds a div to the document that looks like
```html
<div>0.32540102738293863</div>
```
When a11y is enabled the PDOM comes before the heartbeat div in the document, which is probably why there are no numbers for RIAW in https://github.com/phetsims/masses-and-springs/issues/301#issuecomment-404328188.

**Comment by samreid** [comment]
I agree that looks suspicious, and iOS may just be scraping the DOM to generate the preview text.

**Comment by samreid** [comment]
From today's discussion, the iOS app supercedes Reading Mode, and it would be good if clients can use the app instead.

@ariel-phet requested @samreid to take an hour and look into this.

**Comment by samreid** [comment]
On second thought, @ariel-phet wants to investigate and discuss further with QA.

**Comment by ariel-phet** [comment]
Discussed with @lmulhall-phet - he is going to make a more general issue (since this is not sim specific). He will link that issue to this one, and close this M&S issue.

In the new issue @lmulhall-phet will try to layout more specific steps and issues to the reading list problems.

**Comment by ariel-phet** [comment]
General issue made, closing this one.
