### ISSUE TITLE
Long string shrunk too much

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs#302]
**Test device:**
Dell Laptop and iPad 2
**Operating System:**
Windows 10 and iOS 9
**Browser:**
Chrome and Safari
**Problem description:**
When using stringTest=long the movable line string on the intro screen becomes very small.
For phetsims/QA/issues/153
May be related to phetsims/masses-and-springs/issues/296
**Steps to reproduce:**
1. Use stringTest=long
2. Go to the intro screen
3. Look at the the three strings next to the check boxes.  The third one (movable line) is very small

**Screenshots:**
![longstrings](https://user-images.githubusercontent.com/41024075/43215603-d0362d9e-8ff9-11e8-8a90-a0bbee51a385.PNG)

Troubleshooting information (do not edit):
<details>
Name: ‪Masses and Springs‬
URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-rc.2/phet/masses-and-springs_all_phet.html
Version: 1.0.0-rc.2 2018-07-25 04:03:02 UTC
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36
Language: en-US
Window: 1536x737
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"37d5839c","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bc1f66fe","branch":"HEAD"},"dot":{"sha":"bd4d7035","branch":"HEAD"},"griddle":{"sha":"7be25724","branch":"HEAD"},"joist":{"sha":"85b10c15","branch":"HEAD"},"kite":{"sha":"3b76b24a","branch":"HEAD"},"masses-and-springs":{"sha":"7d16369b","branch":"HEAD"},"phet-core":{"sha":"e0cec207","branch":"HEAD"},"phet-io":{"sha":"e5c7148f","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"HEAD"},"phet-io-wrappers":{"sha":"f3701e8d","branch":"HEAD"},"phetcommon":{"sha":"80414edb","branch":"HEAD"},"query-string-machine":{"sha":"1f2322e4","branch":"HEAD"},"scenery":{"sha":"3b05db54","branch":"HEAD"},"scenery-phet":{"sha":"f37bff38","branch":"HEAD"},"sherpa":{"sha":"ded365aa","branch":"HEAD"},"sun":{"sha":"00b9c74c","branch":"HEAD"},"tandem":{"sha":"3e1c8fd3","branch":"HEAD"},"twixt":{"sha":"050e8f19","branch":"HEAD"}}
</details>

**Comment by Denz1994** [comment]
Good catch. I changed the maxWidths these texts in this panel. Can you confirm in master @KatieWoe?

**Comment by KatieWoe** [comment]
Looks good in master.

**Comment by Denz1994** [comment]
Closing this issue.
