### ISSUE TITLE
HTML Download on Chromebook does not work

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs#304]
**Test Device**
Acer Chromebook
**Operating System**
Chrome OS
**Browser**
Chrome
**Description**
When attempting an html download on a chromebook the simulation opens to the home screen and freezes.
For phetsims/QA/issues/153
**Steps to Reproduce**
1. On the simulation, right click and save as.  Make sure you are on a chromebook.
2. Turn off the wifi
3. Open the saved html download

**Comment by KatieWoe** [comment]
Upon further examination, this seems to be covered in https://github.com/phetsims/resistance-in-a-wire/issues/151
We do not seem to support this on ChromeOS.  Disregard. Closing

**Comment by Denz1994** [comment]
Good to know. Thanks for the explanation.
