### ISSUE TITLE
stringTest=long makes lines not aligned with associated strings

### ISSUE THREAD

**Issue by ghost** [phetsims/masses-and-springs#305]
Noticed this while looking at #303...

The natural length, mass equilibrium, and movable lines become slightly misaligned when stringTest=long is used:

![screen shot 2018-07-25 at 1 53 43 pm](https://user-images.githubusercontent.com/31285590/43225486-674ca58e-9016-11e8-86a1-2529c986f7c6.png)

Default for contrast:

![screen shot 2018-07-25 at 1 53 23 pm](https://user-images.githubusercontent.com/31285590/43225502-73e62068-9016-11e8-90f5-4896ea45280b.png)

This does not, however, occur with stringTest=double, so I don't know if we care about this... Are there languages where two words can be about 50 characters long?

For phetsims/QA/issues/153.

**Comment by arouinfar** [comment]
Good catch @lmulhall-phet. I think the purpose of `?stringTest=long` is to reveal layout issues when strings are pushed to/beyond their limit, and this certainly looks like a layout issue to me.

**Comment by ghost** [comment]
Ah, I see. That makes much more sense. Thanks, @arouinfar.

**Comment by ghost** [comment]
Also, on the Energy screen, a slider thumb can overlap with a string:

![image](https://user-images.githubusercontent.com/31285590/43225952-ba58374c-9017-11e8-973f-ed12330490da.png)

**Comment by Denz1994** [comment]
@arouinfar Can you review master? I added some alignBBox/alignGroup refactors.

**Comment by arouinfar** [comment]
@Denz1994 the strings and icons now remained aligned under i18n, which is great.

However, it looks like the Displacement and Natural Length icons are missing from the Lab screen, but they're correctly appearing on the Energy screen.

![image](https://user-images.githubusercontent.com/8419308/43539502-49db6d3e-9582-11e8-8d57-d43bba9aa5d1.png)

![image](https://user-images.githubusercontent.com/8419308/43539472-336fa696-9582-11e8-83fa-abc57d63a89d.png)

It also looks like https://github.com/phetsims/masses-and-springs/issues/305#issuecomment-407886769 hasn't been addressed.

**Comment by Denz1994** [comment]
You are right @arouinfar, what about master now?

**Comment by arouinfar** [comment]
Looks good, thanks @Denz1994!

**Comment by KatieWoe** [comment]
This issue seems to be appearing in RC 3 phetsims/QA/issues/165
![rc3](https://user-images.githubusercontent.com/41024075/43867305-02f32c78-9b26-11e8-8fe4-945994243e98.PNG)

**Comment by KatieWoe** [comment]
Taking a second look at this, I'm no longer sure.  It looks better than it used to, but still seems a bit misaligned to me.

**Comment by arouinfar** [comment]
@KatieWoe I think the Displacement and Natural Length icons are grouped as a single icon, which is then centered with respect to the checkbox.

![image](https://user-images.githubusercontent.com/8419308/43869060-defa0eba-9b2d-11e8-8e7d-86a539d54a55.png)

It looks a bit misaligned for `?stringTest=long` but less so for `?stringTest=double` (which is more realistic for a sim translation).
![image](https://user-images.githubusercontent.com/8419308/43869131-3c43c70a-9b2e-11e8-8209-df26e7e0279f.png)

@Denz1994 if the icons are indeed grouped, I think we can close this issue. Otherwise, please investigate.
