### ISSUE TITLE
Unused strings?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/masses-and-springs#306]
While patching the joist fix into the 1.0 branch, I saw this during the build:

```
>> Unused string: key=MASSES_AND_SPRINGS/normal, value=Normal
>> Unused string: key=MASSES_AND_SPRINGS/slow, value=Slow
```

Are these strings used, or can they be removed? (Probably want to do that, if needed, before release)

**Comment by Denz1994** [comment]
These strings are being used in the sim in the radio buttons of the play speed selection. I don't know why we are getting a build error here. Any thoughts @jonathanolson?

**Comment by Denz1994** [comment]
Okay this makes sense after further investigation. I forgot I enumerated the options for the sim speed. We don't need the strings in the .json file anymore. Thanks for the catch @jonathanolson.

**Comment by Denz1994** [comment]
Unused strings were removed. Closing.
