### ISSUE TITLE
home screen icons still moving up and down with stringTest=double

### ISSUE THREAD

**Issue by ghost** [phetsims/masses-and-springs#307]
The problem described in this comment https://github.com/phetsims/joist/issues/470#issuecomment-405336702 still seems to be a problem in https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-rc.2/phet/masses-and-springs_all_phet.html?stringTest=double.

For phetsims/QA/issues/153.

**Comment by KatieWoe** [comment]
Can confirm presence in RC2.  However, I can't find it in master.

**Comment by ghost** [comment]
@KatieWoe says she's not seeing this in master, so possibly related to build error?

**Comment by jonathanolson** [comment]
Hmm, ~15 minutes ago I applied this patch to the release branch, so it would definitely still be broken in rc.2.

Any production deploy or rc.3 should have it fixed however?

**Comment by jonathanolson** [comment]
See https://github.com/phetsims/joist/issues/470#issuecomment-407890807 and https://github.com/phetsims/joist/issues/470#issuecomment-406371217

**Comment by ghost** [comment]
I didn't see the timestamp, sorry @jonathanolson and @Denz1994. 😳
