### ISSUE TITLE
Use new screenshot procedure for Masses and Springs

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/masses-and-springs#310]
We should take the sim screenshot for Masses and Springs using the new procedure in:
https://github.com/phetsims/tasks/issues/947#issuecomment-408920853

**Comment by Denz1994** [comment]
Becuase #288 is assigned to the QA team I'm going to assign this issue to @KatieWoe and @lmulhall-phet so it isn't left hanging in this repo.

**Comment by arouinfar** [comment]
@oliver-phet do you know what the new process is? If so, can you let @KatieWoe know? @amanda-phet's currently out, and https://github.com/phetsims/tasks/issues/947 doesn't yet include the new procedure.

**Comment by oliver-phet** [comment]
Yes, I'll link up with @KatieWoe tomorrow. We don't have a specific resolution picked out for the new procedure, but we can take this one at the current 2048x1344.

**Comment by arouinfar** [comment]
Screenshots have been committed, so we can close this issue.
