### ISSUE TITLE
Gravity readout rounding errors when using tweakers

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#311]
This happens for Earth, the Moon, and Jupiter, but I will use Jupiter as the example.

Since the internal value of Jupiter's gravity (24.79 m/s<sup>2</sup>) has more sig figs than the sim's readout (the sim shows that value of gravity to be 24.8 m/s<sup>2</sup>), we have rounding errors.

1. On Lab, set the gravity to that of Jupiter (using the combo box).
2. Press either tweaker arrow for this slider, ONCE.

The value will either not change at all, or will move in the wrong direction (ie. the value decreases when you want to increase). Likely under-the-hood the sim is behaving correctly, yet the difference of sig figs does not make it obvious why the readout does not change in that first step.

Seen on Win 10 Chrome. For phetsims/QA/issues/165.

<details>
<summary>Troubleshooting Information</summary>

URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-rc.3/phet/masses-and-springs_all_phet.html
Version: 1.0.0-rc.3 2018-08-08 21:38:04 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1920x947
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"37d5839c","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bc1f66fe","branch":"HEAD"},"dot":{"sha":"bd4d7035","branch":"HEAD"},"griddle":{"sha":"7be25724","branch":"HEAD"},"joist":{"sha":"8da47b06","branch":"HEAD"},"kite":{"sha":"3b76b24a","branch":"HEAD"},"masses-and-springs":{"sha":"b0f63e4a","branch":"HEAD"},"phet-core":{"sha":"e0cec207","branch":"HEAD"},"phet-io":{"sha":"e5c7148f","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"HEAD"},"phet-io-wrappers":{"sha":"f3701e8d","branch":"HEAD"},"phetcommon":{"sha":"80414edb","branch":"HEAD"},"query-string-machine":{"sha":"1f2322e4","branch":"HEAD"},"scenery":{"sha":"3b05db54","branch":"HEAD"},"scenery-phet":{"sha":"f37bff38","branch":"HEAD"},"sherpa":{"sha":"ded365aa","branch":"HEAD"},"sun":{"sha":"00b9c74c","branch":"HEAD"},"tandem":{"sha":"3e1c8fd3","branch":"HEAD"},"twixt":{"sha":"050e8f19","branch":"HEAD"}}
</details>

**Comment by phet-steele** [comment]
An additional note, this breaks right away from the Lab screen startup (while Earth is selected). I don't know why I made you all go through that extra step of switching to Jupiter first. I guess I am just sadistic or something.

**Comment by Denz1994** [comment]
@arouinfar Would you be opposed to having 2 sig figs present in the readout and a the tweakers changing the value by .01? This is also done in pendulum lab. Maybe to prevent these rounding errors.

**Comment by arouinfar** [comment]
I will open the relevant issue in the PL repo. While PL was published not too long ago, it started off as a early port. At that time, the design team did not explicitly think about precision, as we do now.

**Comment by Denz1994** [comment]
This issue is present for any value of gravity that is adjusted with the tweaker. I'll investigate more, but regardless of the gravity, pressing the tweaker once doesn't change the readout.

**Comment by Denz1994** [comment]
I made some refactors that fixed the tweaker button bug in my comment directly above. The gravity values for each planet were also changed. Can you review master @arouinfar?

**Comment by arouinfar** [comment]
Everything looks good in master. Thanks @Denz1994.
