### ISSUE TITLE
Increase Toolbox Height by 10%

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#315]
For https://github.com/phetsims/QA/issues/165

This was originally requested in https://github.com/phetsims/masses-and-springs/issues/292. However, comparing the toolbox heights in rc.1 and rc.3 reveals that the increased height was somehow reverted.

![image](https://user-images.githubusercontent.com/8419308/43973056-942090a0-9c93-11e8-8471-2d8da9299797.png)

**Comment by Denz1994** [comment]
Just checking, do you mean width @arouinfar?

**Comment by arouinfar** [comment]
Thanks for checking @Denz1994. I do indeed mean height. I understand why the toolboxes have different widths, and I'm not requesting a change there, but in https://github.com/phetsims/masses-and-springs/commit/946225874bc35375046647c83f55fc6834e1c34d you increased the height, which was post-rc.1. Not sure why rc.3 has the same height as rc.1.

**Comment by Denz1994** [comment]
I understand now. Thanks for the clarity.

**Comment by Denz1994** [comment]
The heights of the toolboxes have been adjusted @arouinfar can you check master for a comparison?

**Comment by arouinfar** [comment]
@Denz1994 rc.3 and master appear to have the same vertical height. (Horizontal offset is there so it's easier to see that they have the same height.)

![image](https://user-images.githubusercontent.com/8419308/44042168-d4360c24-9edc-11e8-8fe2-eb94070f62c2.png)

**Comment by Denz1994** [comment]
Sorry I didn't push my stashed commit.

**Comment by arouinfar** [comment]
Toolbox height is looking good now. Can you also increase the size of the rulerNode and timerNode icons by 10% so that they have the same relative padding as before?

**Comment by Denz1994** [comment]
Ahh good point. Work in progress.

**Comment by arouinfar** [comment]
👍
