### ISSUE TITLE
Inconsistent gray used for energy graph & panels

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#316]
All credit goes to @phet-steele for spotting this one.

While not technically found during https://github.com/phetsims/QA/issues/165, I'm going to go ahead and tag it because it's a change that needs to be made before the next RC.

The Energy Graph and Panel/Toolbox on the right are using different shades of gray. According to Illustrator's color dropper, the Energy Graph is `#EEEEEE` and the other panels are `#E6E6E6`.

![image](https://user-images.githubusercontent.com/8419308/44051379-ed158746-9ef6-11e8-9d89-54e324801b63.png)

I prefer the somewhat lighter shade used in the Energy Graph, so @Denz1994 please update the right panel/toolbox backgrounds to match.

**Comment by Denz1994** [comment]
Wow, what a catch @phet-steele. @arouinfar Can you check master? The color does make the screen feel a bit lighter.

**Comment by arouinfar** [comment]
Love it!
