### ISSUE TITLE
Why are there some values of thermal energy that cannot be cleared?

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#322]
I'm seeing this limit in `EnergyGraphNode.js` that decides whether the user can clear thermal energy:

```js
  model.firstSpring.thermalEnergyProperty.link( function( value ) {
      clearThermalButton.enabled = ( value > 0.001 );
      clearThermalButton.pickable = ( value > 0.001 );
    }
```

I can't find documentation about why the limit of `0.001` was chosen. This coupled with the ability to zoom in makes the sim look buggy; thermal energy is shown but cannot be cleared:

![image](https://user-images.githubusercontent.com/5863899/44506731-f3154d00-a664-11e8-84a7-132a16a07071.png)

The value of energy in the screenshot must be less than or equal to 0.001. @arouinfar @Denz1994 why is this limit in place? Would js just not work if the check was `value > 0`?

**Comment by Denz1994** [comment]
I don't think there was a specific reason for this. This may have been introduced prior to the refactors to the energyGraphNode. I don't see a good reason to keep it around and it has been replaced with the above suggestion by @phet-steele. Leaving to @arouinfar to close if all seems good.

**Comment by arouinfar** [comment]
I see no reason to have such a limit. Good find @phet-steele.
