### ISSUE TITLE
Toolbox width should match the panel above it

### ISSUE THREAD

**Issue by phet-steele** [phetsims/masses-and-springs#323]
@Denz1994 @arouinfar generally we like to keep stacked panels at the same width, so if one scales, both will scale. Currently the options panel scales for i18n, but the toolbox underneath stays the same (or at least does not scale to the same width):

![image](https://user-images.githubusercontent.com/5863899/44679844-4850b600-a9f9-11e8-88ae-cf56287b88e3.png)

The toolbox should always match the width of the panel above it.

Seen on Win 10 Chrome. For phetsims/QA/issues/180.

<details>
<summary>Troubleshooting Information</summary>

URL: https://bayes.colorado.edu/dev/html/masses-and-springs/1.0.0-rc.4/phet/masses-and-springs_all_phet.html?stringTest=double
Version: 1.0.0-rc.4 2018-08-24 22:56:24 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Language: en-US
Window: 1920x943
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"37d5839c","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"bc1f66fe","branch":"HEAD"},"dot":{"sha":"bd4d7035","branch":"HEAD"},"griddle":{"sha":"7be25724","branch":"HEAD"},"joist":{"sha":"8da47b06","branch":"HEAD"},"kite":{"sha":"3b76b24a","branch":"HEAD"},"masses-and-springs":{"sha":"0cd2d603","branch":"HEAD"},"phet-core":{"sha":"e0cec207","branch":"HEAD"},"phet-io":{"sha":"e5c7148f","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"HEAD"},"phet-io-wrappers":{"sha":"f3701e8d","branch":"HEAD"},"phetcommon":{"sha":"80414edb","branch":"HEAD"},"query-string-machine":{"sha":"1f2322e4","branch":"HEAD"},"scenery":{"sha":"3b05db54","branch":"HEAD"},"scenery-phet":{"sha":"f37bff38","branch":"HEAD"},"sherpa":{"sha":"ded365aa","branch":"HEAD"},"sun":{"sha":"00b9c74c","branch":"HEAD"},"tandem":{"sha":"3e1c8fd3","branch":"HEAD"},"twixt":{"sha":"050e8f19","branch":"HEAD"}}
</details>

**Comment by Denz1994** [comment]
The right-hand panels have been refactored to use an alignGroup for formatting the width of the panels and position. The committed fixes can be tested in this link https://phet-dev.colorado.edu/html/masses-and-springs/1.0.0-rc.5/phet/masses-and-springs_en_phet.html @KatieWoe.

If the bug is fixed please assign to me so I can cherry pick commits into master.

**Comment by KatieWoe** [comment]
Looks fixed to me.
