### ISSUE TITLE
Legends of Learning: spring unpauses in a different location

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs#324]
**Devices**
Dell and HP laptop
**OS**
Win 10 and Win 7
**Browser**
Chrome and Firefox
**Problem Description**
For phetsims/QA/issues/180
When pausing the sim with LoL when the spring is moving, the spring will unpause in a new location.  This causes a "jump."
**Steps to Reproduce**
1. Enter the sim into the Legends of Learning harness
2. Go to any of the screens
3. If damping is non-zero on the screen, turn it down to zero so that this effect can be better seen.
4. Start the harness.
5. Attach a mass and pull it all the way down so you have a large amplitude of motion
6. Press pause on the harness (not the sim).  Attempt to do this when it is at the top of the screen.
7. Unpause the harness

**Screenshots**
![jump](https://user-images.githubusercontent.com/41024075/44747148-abaa1900-aac9-11e8-89f5-de58fad33ec6.gif)

**Comment by KatieWoe** [comment]
Update: It seems that opening the "message logs" when paused further changes the state of the sim.
Screenshot:
![jumpmenu](https://user-images.githubusercontent.com/41024075/44753424-43643300-aadb-11e8-8cf6-f52d85fcd77c.gif)

**Comment by phet-steele** [comment]
@KatieWoe your first comment is a trade-off that was discussed in https://github.com/phetsims/pendulum-lab/issues/187, and as long as the physics of the simulation remains intact, is fine.

However your second comment is concerning, and may warrant its own issue (in joist) for maybe @jonathanolson and/or @samreid to look into.

**Comment by Denz1994** [comment]
> @KatieWoe your first comment is a trade-off that was discussed in phetsims/pendulum-lab#187, and as long as the physics of the simulation remains intact, is fine.

Based on @phet-steele's comment above and since an issue has been logged in joist for the second point made. Is there anything left to do with this issue? It seems like any further work should be handled in https://github.com/phetsims/joist/issues/515.
