### ISSUE TITLE
Version on master 1.1.0-dev.0

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs#330]
For https://github.com/phetsims/QA/issues/184
I've been checking the versions on master on sims for the above issue.  There seems to some confusion surrounding this here.  Specifically, I am seeing .rc versions listed on master.  My understanding was that only .dev version should be listed here.  I believe that the version should say 1.1.0-dev.0.  If you have questions, I suggest talking with @jonathanolson to make sure everything is consistent.

**Comment by pixelzoom** [comment]
Looking at commit history for package.json master, it looks like RC deploys have been done out of master, in a very odd order.  Here are the past several commits, in reverse chronological order:

Bumping version to 1.0.0-rc.3 denz1994 8/21/18, 10:15 AM
Bumping version to 1.0.0-rc.4 denz1994 8/21/18, 10:14 AM
Bumping version to 1.0.0-rc.3 denz1994 8/21/18, 8:21 AM
Bumping version to 1.0.0-rc.4 denz1994 8/21/18, 8:20 AM
Bumping version to 1.0.0-rc.3 denz1994 8/21/18, 8:16 AM
Bumping version to 1.0.0-rc.4 denz1994 8/21/18, 8:12 AM
Bumping version to 1.0.0-rc.3 denz1994 8/8/18, 3:36 PM

@Denz1994 can you explain what happened here?  Why are RC versions deployed out of master? Why is does the same version id appear multiple times? Why are the version ids not in increasing numerical order?

@jonathanolson Does `grunt rc` allow you to deploy an RC version out of master? (It shouldn't.)

**Comment by pixelzoom** [comment]
And back to the issue at hand... Because there is a 1.0 release branch, master's package.json should have been set to `"version": "1.1.0-dev.0"`.   I can see that that was done in a commit on 6/8/18, but was then changed to 1.0.0-rc.1 just 2 minutes later.

**Comment by jonathanolson** [comment]
> @jonathanolson Does grunt rc allow you to deploy an RC version out of master? (It shouldn't.)

Nope, I think merges happened between master and the release branch that won't happen in the future. That's how things were a bit weird, and it caused some troubles with rc.3 and rc.4 which is why there were a lot of commits for those.

Basically, the package.json in master should be fixed up, and things should be good for the future.

**Comment by pixelzoom** [comment]
I fixed package.json. @Denz1994 please verify.

**Comment by Denz1994** [comment]
Looks good @pixelzoom Thank you.
