### ISSUE TITLE
Retake screenshots

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#332]
It appears there are some kerning issues associated currently with Win 10 chrome, the current screenshots should be retaken on a platform not exhibiting the kerning issues. Although the screenshots on the website or such are fine currently, if we wanted to use these assets on a poster or such the kerning issues would become noticeable.

**Comment by KatieWoe** [comment]
This should be done.  See https://github.com/phetsims/masses-and-springs/issues/288 for commits. @ariel-phet

**Comment by ariel-phet** [comment]
Excellent, closing
