### ISSUE TITLE
Inconsistent Z-ordering of Equilibrium Position/Mass Equilibrium

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#335]
Discovered during https://github.com/phetsims/masses-and-springs-basics/issues/17

In general, the reference lines should be layered above the springNode, but behind the mass. 

On Intro, the Equilibrium Position is behind the springNode.
![image](https://user-images.githubusercontent.com/8419308/46760933-8136a880-cc90-11e8-9322-b48d6037ed64.png)

On Vectors, the Mass Equilibrium is behind the springNode.
![image](https://user-images.githubusercontent.com/8419308/46761005-ba6f1880-cc90-11e8-8237-f31b3877fc7a.png)

However, everything is looking good on Energy & Lab.
<img src="https://user-images.githubusercontent.com/8419308/46761088-eab6b700-cc90-11e8-80e2-0f6573347c3e.png" width=250> <img src="https://user-images.githubusercontent.com/8419308/46761127-face9680-cc90-11e8-99e2-b01b40712137.png" width=250>

<img src="https://user-images.githubusercontent.com/8419308/46761207-281b4480-cc91-11e8-907a-d555fc932552.png" width=250> <img src="https://user-images.githubusercontent.com/8419308/46761222-323d4300-cc91-11e8-8727-d866346b4281.png" width=250>

**Comment by Denz1994** [comment]
The order of adding view components to the scene graph has changed. Please review @arouinfar for the above correction. 

All lines should be behind the mass and in front of the spring.

**Comment by arouinfar** [comment]
Everything's looking good @Denz1994.

**Comment by Denz1994** [comment]
This issue has been lingering for a while but seems to have been fixed. This isn't awaiting any deploys since publication and we aren't doing any qa cycles any time soon. Closing this issue.
