### ISSUE TITLE
Range mismatch in Spring

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#340]
During https://github.com/phetsims/dot/issues/79 I noticed this code:

```js
    // @public {Property.<number>} spring constant of spring
    this.springConstantProperty = new NumberProperty( MassesAndSpringsConstants.SPRING_CONSTANT_RANGE.defaultValue, {
      tandem: tandem.createTandem( 'springConstantProperty' ),
      units: 'newtons/meters',
      range: new Range( Number.NEGATIVE_INFINITY, Number.POSITIVE_INFINITY )
    } );
```

Is it intentional that the springConstant specifies a different Range than `SPRING_CONSTANT_RANGE`?  If not, we should use `range: MassesAndSpringsConstants.SPRING_CONSTANT_RANGE`.  If so, the discrepancy should be documented.

**Comment by Denz1994** [comment]
I have updated the range. Using the constant value is will suffice. Good catch. Closing.
