### ISSUE TITLE
User suggestion: ability to zoom

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/masses-and-springs#345]
> With the 2.03 version, I could right click to zoom in on the ruler.  That's not possible now.  I use a screen at the front of the class.  Having the zooming capability would help the class read off displacements via the ruler.  Any suggestions?

**Comment by Denz1994** [comment]
@oliver-phet Was there any info on platform or browser?

**Comment by Denz1994** [comment]
Just brainstorming: My initial thought for a workaround is to take a snapshot of the screen using the phet menu in the nav bar and zoom from the snapshot.

It seems like right-clicking to zoom as described isn't a phet specific function that was intended for the sim, but more of convenience based on the browser in use. Alternatively, a 3rd party plugin for a magnification would work.

Toggling the zoom controls in the browser (Chrome, Firefox) didn't work for me.

Thoughts @ariel-phet?

**Comment by oliver-phet** [comment]
More info from user:

> I downloaded the 2.03 .jar (java file), one for mac and another for windows back in fall 2017.  On a windows computer, when I click on the java file, a Chrome browser opens with the application masses and springs.  Right clicking, I have the option of zooming in.  My concern is that in the future, I may not be able to run it since a compatibility issue may arise.  I can no longer open the 2.03 mac version on my mac computer.
> 
> When opening the most recent masses and springs application, right clicking on the ruler doesn’t allow for zooming.
> 
> I like the activity…so if I can keep using it, it would be great.  So, would a magnifying glass be possible?

The original sim was Flash and I verified that it allows native zoom in the browser.

**Comment by ariel-phet** [comment]
@oliver-phet there are plans in the future to allow "pinch to zoom" and the like for accessiblity, but this will be a project wide feature. We should not try to make some sort of workaround for this sim. Also let the user know about Hooke's law if they are wanting a sim with help verifying Hooke's Law, since that sim has a quantitative readout of displacement.
