### ISSUE TITLE
Usability on small screens review

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/masses-and-springs#348]
Per @kathy-phet's request in https://github.com/phetsims/QA/issues/295 I am making issues in each published sim repo detailing the pointer areas and usability of sims on phone sized screens.  Done on an iPhone 7 iOS 12 device.

Potential Difficulties Noticed:
* Arrows at end of sliders could have larger pointer areas

Screenshots:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56249290-722e1a00-6068-11e9-854d-27a5f8e35ba4.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/41024075/56249291-722e1a00-6068-11e9-8517-a677d3d6baaf.png)
![Image from iOS (3)](https://user-images.githubusercontent.com/41024075/56249292-722e1a00-6068-11e9-9349-c4188bbef1c8.png)
![Image from iOS (4)](https://user-images.githubusercontent.com/41024075/56249293-722e1a00-6068-11e9-8017-fe63dfd6e76f.png)
![Image from iOS (5)](https://user-images.githubusercontent.com/41024075/56249294-722e1a00-6068-11e9-9932-f0ea34ce1990.png)
![Image from iOS (6)](https://user-images.githubusercontent.com/41024075/56249295-722e1a00-6068-11e9-978a-4835440f517c.png)
![Image from iOS](https://user-images.githubusercontent.com/41024075/56249296-72c6b080-6068-11e9-9d60-c7e032bfe624.png)

**Comment by arouinfar** [comment]
@Denz1994 asymmetric dilation of NumberControl tweakers was added in https://github.com/phetsims/scenery-phet/issues/489. Here's a mockup of updated touch areas in green.
![image](https://user-images.githubusercontent.com/8419308/56304186-d00b4200-60fa-11e9-9492-b0d37615969e.png)

**Comment by Denz1994** [comment]
I've updated the arrow's at the end of the NumberControls to have dilated touch areas. @arouinfar Please check master for MAS and MASB for the changes.

**Comment by arouinfar** [comment]
Thanks @Denz1994. The Gravity tweakers are looking good, but I think the Mass tweakers are still feeling a bit small. Can you add some extra vertical padding to the Mass tweakers? 

![image](https://user-images.githubusercontent.com/8419308/57004045-a6392d00-6b88-11e9-825e-66a355f1af84.png)

I know it looks a bit exaggerated, but the Mass NumberControl is somewhat on the smaller side, so the exaggerated touch area would be helpful.

**Comment by Denz1994** [comment]
This makes sense. The touch areas have been expanded along the Y-axis. Please review master @arouinfar?

**Comment by arouinfar** [comment]
Looks great, thanks @Denz1994!
