### ISSUE TITLE
Enumeration should not be a member variable

### ISSUE THREAD

**Issue by zepumph** [phetsims/masses-and-springs#349]
From https://github.com/phetsims/phet-core/issues/61#issuecomment-505661338, 

@Denz1994, would you mind converting these Enumeration usages to more idiomatic phet usages. Likely they should be constants. @samreid made a recommendation in the above link. See also 

https://github.com/phetsims/phet-info/commit/a48a28780db3bdae04742e7780cba3c658b7d339
https://github.com/phetsims/phet-core/blob/master/js/Enumeration.js#L46

for more examples. Thanks!

**Comment by Denz1994** [comment]
Enumerations should be fixed along with their usages in the intro screen. I added the Enumerations to MAS Constants.js. I'll watch CT for bug reports and close if CT is clean.

**Comment by zepumph** [comment]
This looks to be incomplete, after poking around in https://github.com/phetsims/masses-and-springs/issues/354, I see that in `MassesAndSpringsModel` there are still two that have different Enumeration instances based on which model instance it is. Can these be moved to the constants too?

I bet this will solve that CT issue.

**Comment by Denz1994** [comment]
Correct @zepumph thanks for catching that. I pushed a fix to move those two cases to the constants file. This has the sim working again while testing locally, but I'll monitor CT.

Note: https://github.com/phetsims/masses-and-springs/commit/9461544b8b74f845c985a1a48697d58c029e8175 has a corrected commit message at the bottom of the commit.

**Comment by Denz1994** [comment]
This seems to have been fixed after adjusting those last two `Enumeration` instances. Closing.
