### ISSUE TITLE
Duplicated code in OneSpringScreenView and TwoSpringScreenView

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#351]
While working on https://github.com/phetsims/gas-properties/issues/170, I noticed around 20 lines of duplicated code between OneSpringScreenView and TwoSpringScreenView.

![image](https://user-images.githubusercontent.com/679486/71014244-df3df780-20ae-11ea-9b28-a0e079ab8d3c.png)

Assigning to the responsible dev.  Also note, I have some commits coming to these files shortly for https://github.com/phetsims/gas-properties/issues/170

**Comment by Denz1994** [comment]
The code duplication essentially adjusts relevant view components when the visible bounds of the sim change.`SpringScreenView.adjustViewComponents( )` was added to remove the code duplication in the two spring views. I'll let CT run a cycle before closing.
