### ISSUE TITLE
Use Stopwatch and StopwatchNode

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#352]
From https://github.com/phetsims/gas-properties/issues/170: DraggableTimerNode.js and a few properties in MassesAndSpringsModel should be replaced with Stopwatch and StopwatchNode.  I'll implement this shortly, and assign to the responsible dev for review.

**Comment by samreid** [comment]
Before the commit, there was code like:

```js
Masses and springs needs:
    // Readout value that is used for the timerNode. We are rounding the value in the view component.
    const timerReadoutProperty = new DynamicProperty( new Property( timerSecondsProperty ), {
      bidirectional: true,
      map: function( seconds ) {
        return Util.roundSymmetric( seconds * 1e5 ) / 1e5;
      }
    } );
```

But it was unclear to me what the rounding was doing for the stopwatch node.  This should be discussed and/or addressed before this issue can be closed.

**Comment by samreid** [comment]
@Denz1994 can you please take a look?

**Comment by Denz1994** [comment]
This was introduced as a fix to https://github.com/phetsims/masses-and-springs/issues/156. However it was found (a few months later) that there was still an erroneous edge case where the centisecond readout would overlap the bounds of the timer. This was later corrected in https://github.com/phetsims/scenery-phet/commit/5701df8ee2e173ced810002476e5345f6f938733, but the code responsible for the rounding above was not omitted and should be safe to remove.
