### ISSUE TITLE
Should the pointer area for the StopwatchNode be dilated?

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#353]
From https://github.com/phetsims/gas-properties/issues/170#issuecomment-566840809

The StopwatchNode in Masses and Springs has a dilated pointer area, like so:

![image](https://user-images.githubusercontent.com/679486/71317905-efa2f900-2445-11ea-8f95-b6139667c7ed.png)

@pixelzoom said:

> The stopwatch is huge in Masses and Spring, and I don't know why it would need a dilated touchArea. But assuming it does (and you don't want to consult the designer) it should be set in MASSES_AND_SPRINGS/SpringScreenView (and other call sites?), not in StopwatchNode:

I'll add the pointer area as it was before, but wanted to double check with a designer why this pointer area is here and whether it is necessary.  Also, there was another sim that had a 5px pointer dilation for the StopwatchNode, but I can't remember which it was.  It would be good to know if that can be omitted across the board, or if I need to track it down, since moving to the new common code won't have any dilation by default.

@arouinfar can you please take a look?

**Comment by arouinfar** [comment]
I see no reason why the StopwatchNode needs dilated touch areas, as its footprint is already quite large. @samreid I would agree the common component should not have any dilation by default.

@Denz1994 can you remove the dilation in MAS & MASB?

**Comment by Denz1994** [comment]
![image](https://user-images.githubusercontent.com/13894380/71641945-99b62880-2c71-11ea-8c3d-54d837c2ae55.png)

The dilated touch areas for the stopwatch has been removed from both MAS and MASB. If this looks good @arouinfar, I think we can close this issue.

**Comment by arouinfar** [comment]
@Denz1994 looks good in master. Since this hasn't been deployed, I'll leave this open with `status:fixed-awaiting-deploy`.

**Comment by Nancy-Salpepi** [comment]
In 1.1.0-dev.2 the touch area for the stopwatch is no longer there. 

The touch and pointer areas for the buttons on the stopwatch look good. They are the same as in other sims on master (Gas Properties, ESP):
<img width="171" alt="Screenshot 2023-06-02 at 7 14 22 AM" src="https://github.com/phetsims/masses-and-springs/assets/87318828/5c1c0bbb-396b-46a8-8b28-dfcb293d3d7c">

**Comment by jbphet** [comment]
@Nancy-Salpepi - Based on the discussion above, I don't think the stopwatch is supposed to have an extended touch area.  In fact, it sounds like it was intentionally removed.  So, I'm not quite sure what you're saying is a problem here.  Can you please re-review and either close or assign back to me with more info?

**Comment by Nancy-Salpepi** [comment]
@jbphet sorry I was not clear. There is no problem here. I just didn't close the issue and assigned back to you as per the instructions in the QA issue.

Closing now.
