### ISSUE TITLE
Initial review

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#36]
As @Denz1994 and I have been working on PhET-iO we realized it would be good to start some brief review process early on.  I'll make some notes here or commit changes as part of this review, mostly in collaboration with @Denz1994.

**Comment by samreid** [comment]
In the preceding commits, I updated some styles and added TODOs.  I recommend @Denz1994 to review the preceding commits and let me know if you have any questions about them.

**Comment by samreid** [comment]
This review still needs to be done, but I'm no longer sure who/when.  @ariel-phet can you please comment?

**Comment by ariel-phet** [comment]
@jbphet should be working on the review this week or next, once ExEx has gone to RC testing

**Comment by jbphet** [comment]
It took a while, but Expression Exchange is now in RC testing, so I'm going to take some time now to do some reviewing of this code.  I will create issues for the larger, multi-file things that I see, and will embed review comments in the code for the smaller things that can be handled more quickly and easily.

**Comment by jbphet** [comment]
Initial review is complete, assigning to @Denz1994 to address the `// REVIEW` comments.  In general, the code looks pretty good and is coming along very nicely.  

Just to be clear, this is a sort of 'mid-term' code review since @Denz1994 is a fairly new developer, and we will still need to perform a final review before publication.

**Comment by Denz1994** [comment]
@jbphet Thanks for the review and input, I will work to make the appropriate changes.

**Comment by Denz1994** [comment]
Removing the high priority tag because the review is complete and we have significantly reduced the number of REVIEW comments.

**Comment by Denz1994** [comment]
All of the review comments added by @jbphet have been addressed. All further review comments should have their own issue. Thanks, @jbphet for your time!
