### ISSUE TITLE
model is reset twice when ResetAllButton is pressed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/masses-and-springs#361]
In base class SpringScreenView:

```js
 this.resetAllButton = new ResetAllButton( {
    listener: function() {
      model.reset();
```

In subclass OneSpringScreenView:

```js
    this.resetAllButton.addListener( function() {
      self.model.reset();
```

**Comment by Denz1994** [comment]
Good catch. I removed the `reset()` in the subclass. To check for any other duplicate calls, I tested by logging a message in `reset()` and making sure there aren't any duplicate messages. Closing this one.
