### ISSUE TITLE
buggy EnergyGraphNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/masses-and-springs#365]
Problems noted while converting EnergyGraphNode to ES6 class for https://github.com/phetsims/tasks/issues/1044.

(1) EnergyGraphNode should be named EnergyGraphAccordionBox.  It's a subclass of AccordionBox, and PhET convention is name these with "AccordionBox" suffix.  This also is important for consistent PhET-iO element naming.

(1) Reset All does not restore the expanded state of the accordion box. You can demonstrate that it's broken in the published version, prior to ES6 conversion:  https://phet-dev.colorado.edu/html/masses-and-springs/1.0.10/phet/masses-and-springs_en_phet.html.  You need to either pass your own `expandedProperty` to AccordionBox via options and reset it, or call AccordionBox `reset` to reset the default `expandedProperty`.

**Comment by Denz1994** [comment]
Thanks for creating the issue. I've refactored EnergyGraphNode to EnergyGraphAccordionBox and adjusted its use cases. Also, reset is now calling AccordionBox.reset(). Assigning to @pixelzoom for review and closing if this looks good.

**Comment by pixelzoom** [comment]
Changes look good, and verified that it's fixed in master.

Since this is a problem in the published version, do you want to do a maintenance release?  If not, feel free to close.

**Comment by Denz1994** [comment]
Closing this issue, as it isn't problematic to the user's experience when operating the sim.
