### ISSUE TITLE
OneScreenSpringView calls MassesAndSpringsModel.reset

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/masses-and-springs#366]
Noted while converting ScreenView subclasses to ES6 `class` for https://github.com/phetsims/tasks/issues/1044.

In OneScreenSpringView.js:

```js
  /**
   * @public
   */
  reset() {
    MassesAndSpringsModel.prototype.reset.call( this );
    this.energyGraphAccordionBox.reset();
  }
```

Why are you calling `MassesAndSpringsModel` reset?   This looks like a bug, and I commented it out during the ES6 class conversion.

**Comment by Denz1994** [comment]
Right. We actually don't need the`OneSpringView.reset()` because the resetAllButton listener is handling this same functionality. Closing this one.
