### ISSUE TITLE
LabScreenView step duplicates implementation of super type

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/masses-and-springs#367]
Noted while converting ScreenView subclasses to ES6 class for phetsims/tasks#1044.

class LabScreenView extends OneSpringScreenView, and defines `step` like this:

```js
  /**
   * @param {number} dt
   * @public
   * @overrides
   */
  step( dt ) {
    this.energyGraphAccordionBox.update();
    this.periodTraceNode.step( dt, this.model.playingProperty );
  }
```

OneSpringScreenView already defines `step`, like this:

```js
  step() {
    this.energyGraphAccordionBox.update();
  }
```

So instead of calling `super.step`, LabScreenView is duplicating the implementation of  OneSpringScreenView `step`.  This is a future bug waiting to happen.

The implementation of LabScreenView `step` should be:

```js
  /*
   * @param {number} dt
   * @public
   * @overrides
   */
  step( dt ) {
    super.step( dt );
    this.periodTraceNode.step( dt, this.model.playingProperty );
  }
```

**Comment by Denz1994** [comment]
Agreed, we should just be calling the reset method in the parent class. That change has been made above. I checked the other screen views in MAS and MASB and didn't find another duplication like this. Reassigning back over the @pixelzoom to close.

**Comment by pixelzoom** [comment]
👍🏻 closing
