### ISSUE TITLE
Spring behavior is different than published

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/masses-and-springs#380]
**Test device**
MacBook Air M1 chip

**Operating System**
13.4

**Browser**
Safari 16.4

**Problem description**
For https://github.com/phetsims/qa/issues/936 and https://github.com/phetsims/qa/issues/937, the length the spring stretches is different between published, master and the current dev version. 

**Steps to reproduce**
Here is an example to compare between Basics versions:
1. On the Bounce Screen, add the Green Mass to Spring 2
2. Move the slider for Spring Strength 2 all the way to the right
3. You can use the Ruler or Movable Line to compare the length of the spring. 

https://github.com/phetsims/masses-and-springs/assets/87318828/8b017037-b77d-4531-8e92-d96b07f0a9ca

Here is an example to compare between Masses and Springs versions:
1. On the Intro Screen, add the Blue Mass to Spring 2
2. Move the slider of Spring Constant 2 all the way to the right
3. You can use the Ruler or Movable Line to compare the length of the spring. 

https://github.com/phetsims/masses-and-springs/assets/87318828/04b55f19-2914-4fc5-83e0-dbb7009f62c8

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Masses and Springs‬
URL: https://phet-dev.colorado.edu/html/masses-and-springs/1.1.0-dev.2/phet/masses-and-springs_all_phet.html
Version: 1.1.0-dev.2 2023-05-02 23:06:13 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language: en-US
Window: 1528x780
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by arouinfar** [comment]
@Nancy-Salpepi the length the spring stretches to when it oscillates depends on how far it was stretched or compressed when you "let go" of the mass. Looking at these videos, I think you may have hooked the mass on the spring without setting any specific displacement. Also, if you make any changes to the spring constant while it is already in motion, the sim will use the instantaneous displacement and velocity as the new initial conditions so the behavior from tab to tab will differ.

Can you try this experiment and tell me if it makes a difference? 

1. Pause the sim.
2. Attach the mass to the spring.
3. Move the mass to some easily repeatable location (e.g. drag the mass as far up as you can to compress fully, stretch it so the bottom touches the navbar, or use the moveable line to decide on some other location).
4. Press play. When the mass oscillates, its maximum displacement should match the location where you let it go (assuming damping = 0, which is true of the Bounce and Intro screens).

**Comment by Nancy-Salpepi** [comment]
Well it is pretty obvious I know nothing about springs 😂 @arouinfar! 
I compared master with published and they look the same. Closing.
