### ISSUE TITLE
Delete this repo

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#4]
@pixelzoom @jonathanolson @jbphet can I delete this repo?  Assigned to @pixelzoom since he has the most recent commits.

**Comment by pixelzoom** [comment]
All of my commits were general refactors. I have no idea who is responsible for this sim or what its status is.

**Comment by samreid** [comment]
Looks like this was a Q1 2013 prototype by @samreid before we went with scenery.  No simulation-specific code was ported here, looks safe to delete.  I backed up the repo on my laptop (no issues need to be saved), will hold onto it for 30 days or so in case anyone wants to change their mind.  Will delete shortly.

**Comment by samreid** [comment]
Closing issue now since delete is imminent.
