### ISSUE TITLE
Suggestion for using analytic solution for model

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#4]
@dubson suggested that in the original sim he used a fancy model that was unnecessary, since the damped harmonic oscillator with linear drag is an exactly solved problem with a solution that consists of simple functions.

As we build the model for this sim lets try using the more straightforward model @dubson suggests

**Comment by mattpen** [comment]
The analytic solution was implemented in collaboration with @jonathanolson in spring '16.
