### ISSUE TITLE
Layer dashed reference line above ruler

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/masses-and-springs#5]
From unfuddle: https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2339

@arouinfar please consider the comments below as you refine the redesign, should be easy to address

> I just put together an exercise using the Masses&  Springs PhET and a
> couple of little things popped up, probably trivial to change, if anyone
> has a free moment:
> - There are not big tick marks on 10, 30, 50 cm on the ruler (but there
>   are big ticks on 20, 40) Makes it harder to measure amplitudes (for no
>   good reason)
> - It would help if the dashed measurement line was on top of the ruler,
>   not hidden behind. Sure, it's not hard to look the point where the dotted
>   line disappears, but if you happen to be at a space between the dashes,
>   you have to slide the line a bit and...On top would remove that tiny, yet
>   cognitive power consuming, bug.

**Comment by arouinfar** [comment]
@ariel-phet I think we can easily address these issues. In fact, it looks the first one was addressed in the latest version of Masses and Springs, which is dated after the Unfuddle ticket.

@mattpen can you please layer the dashed reference line above the ruler?

**Comment by mattpen** [comment]
This was completed in february.
