### ISSUE TITLE
Check that Tandem IDs don't correspond with a specific color.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#52]
In cooperation with the idea that Phet Sims should be color-blind accessible, Tandem IDs should not be specific to a certain color.

Issue #49:

> With further discussion on this topic, we came to the conclusion that Phet-IO instrumentation should be careful to consider color blindness with instrumenting tandem IDs. Tandem IDs should not specify color, as users may have different interpretations for colors.

Check to assure Tandem IDs are not restrained by a specific color.

**Comment by Denz1994** [comment]
Is this something that should be considered for all Phet-IO Tandem IDs implementations? 
I didn't find any references to color-blindness in the PhET-IO instruction doc in #27.

[https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md](url)

@samreid

**Comment by samreid** [comment]
@Denz1994 and I discussed it and decided it would be more convenient to refer to the "red-orangish" mass as "the red one" for its tandem name.  We are not planning to make the mass colors settable over the PhET-iO API, but if one day a client requests that feature, we may need to revisit this discussion.

**Comment by Denz1994** [comment]
Closing this issue until needed based on client requests.
