### ISSUE TITLE
Each scene should have its own model

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#56]
During #36 I saw code for stashing and unstashing model values for scene switching.  For instance:
```js
      if ( mode === 'same-length' ) {
        // Manages stashing and applying parameters to each scene
        scene2Parameters = model.stashSceneParameters();
        model.applySceneParameters( scene1Parameters );
        self.springLengthControlPanel.visible = false;
      }

      else if ( mode === 'adjustable-length' ) {
        // Manages stashing and applying parameters to each scene
        scene1Parameters = model.stashSceneParameters();
        model.applySceneParameters( scene2Parameters );
```

It will probably be much simpler to give each scene its own model and view rather than trying to stash and unstash values.  This is typically what is done in other sims and it works very well.

**Comment by Denz1994** [comment]
True. This feature is specific to the intro screen and should be in an intro screen model.

**Comment by Denz1994** [comment]
Check all TODO statements in the intro directory for the removal of properties and links.

**Comment by Denz1994** [comment]
The IntroModel has been added. The intro model is still being updated as the sim is being developed so this issue will be closed.

**Comment by Denz1994** [comment]
The energy model has also been added in commit 7f20a3e0d0f9609d38e93667b7592191634bd25a.
