### ISSUE TITLE
Some places missing @public/@private and (read-only)

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#57]
From #36:

All attribute assignments should include visibility annotations.   For example, in MassesAndSpringsModel.js
```js
    this.gravityRange = new RangeWithValue( 0, 30, 9.8 );
```

**Comment by Denz1994** [comment]
Assigning to @samreid for review.

**Comment by samreid** [comment]
Searching for the regex `this.\w+ = ` I'm still seeing many places without annotations.  I stopped my search at Mass.js

**Comment by Denz1994** [comment]
I have to go throughout the code base again as there have been many edits since April.

**Comment by Denz1994** [comment]
This was reviewed in early November and I will leave it up to the Code Review Checklist to catch anything that was added or missed.
