### ISSUE TITLE
Eliminate startDrag functions

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#60]
A few of the files have code like this:

```js
    /**
     * Responsible for handling drag event for timer node using event forwarding from timer icon in toolbox
     * @public
     *
     * @param {Event} event - Drag event that is forwarded from timer icon in toolbox node
     */
    startDrag: function( event ) {
      this.timerNodeMovableDragHandler.startDrag( event );
    }
```

In discussion, @Denz1994 and I preferred just calling the startDrag on the *movableDragHandler directly, without this adapter method.  In each case, this will clean up 9 lines and remove an unnecessary method.

Discovered in #36

**Comment by Denz1994** [comment]
Reassigning to @samreid for review.

**Comment by samreid** [comment]
This seems much better, thanks!  Closing.
