### ISSUE TITLE
IndicatorVisibilityControlPanel should extend Panel

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#61]
During #36 I saw that IndicatorVisibilityControlPanel extends Node and contains one child which is a Panel.  It would be simpler if IndicatorVisibilityControlPanel extended Panel instead.

**Comment by Denz1994** [comment]
There were several places where inheritance could have been refactored, such as the ruler, timer, line, and panel. The suggestion above was considered for these objects as well. Assigning @samreid for review.

**Comment by samreid** [comment]
IndicatorVisibilityControlPanel looks good.  It looks like this same pattern should be applied to SpringHangerNode, which is a Node that has only one child.

**Comment by Denz1994** [comment]
Also changed inheritance of springHnagerNode.js

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
