### ISSUE TITLE
Factor out duplicated code in line creation

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#62]
During #36 I saw this code in IndicatorVisibilityControlPanel:

```js
    // Lines added for reference in panel
    var greenLine = new Line( 0, 0, LINE_LENGTH, 0, {
      stroke: 'rgb(93, 191, 142)',
      lineDash: [ 6, 2.5 ],
      lineWidth: 2.0,
      cursor: 'pointer',
      tandem: tandem.createTandem( 'greenLine' )
    } );

    var blueLine = new Line( 0, 0, LINE_LENGTH, 0, {
      stroke: 'rgb(65,66,232)',
      lineDash: [ 6, 2.5 ],
      lineWidth: 2.0,
      cursor: 'pointer',
      tandem: tandem.createTandem( 'blueLine' )
    } );

    var redLine = new Line( 0, 0, LINE_LENGTH, 0, {
      stroke: 'red',
      lineDash: [ 6, 2.5 ],
      lineWidth: 2.0,
      cursor: 'pointer',
      tandem: tandem.createTandem( 'redLine' )
    } );
```

I recommend factoring out a function so the lines can be created like this:

```js
var greenLine = createLine('rgb(93, 191, 142)',tandem.createTandem('greenLine'));
```

**Comment by Denz1994** [comment]
The two commits above work to remove this duplicated code as suggested with a passed in a tandem argument into the createLine function.

**Comment by Denz1994** [comment]
Assigning to @samreid for review.

**Comment by samreid** [comment]
Looks good, it would be even better if `createLine` was a local var declared in the constructor, since it does not need to be used elsewhere.  Also, please add JSDoc for the `createLine` function.

Also, only use `self` inside closures.  Use `this` where possible.

**Comment by Denz1994** [comment]
Above suggestions where implemented.

**Comment by samreid** [comment]
Everything is looking good so far, the only thing I noticed is that:

masses-and-springs/js/common/model/MassesAndSpringsModel.js
masses-and-springs/js/common/model/Spring.js
masses-and-springs/js/common/view/DraggableRulerNode.js

and other files still use `self` where `this` should be used.

**Comment by Denz1994** [comment]
Reviewed all the current instances of self and adjusted some implementations in several files. Reassigning for review.

**Comment by samreid** [comment]
MassesAndSpringsModel.js and DraggableRulerNode.js still each have places in the constructor where `self` is incorrectly used instead of `this`.

**Comment by Denz1994** [comment]
After reviewing MassesAndSpringsModel.js with @jonathanolson there weren't any misuses of ```self```. Also, the DraggableRulerNode.js doesn't have any more invalid uses. Closing this because both files have been refactored.
