### ISSUE TITLE
Eliminate unnecessary node

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#63]
Similar to #61 I saw that NaturalLineLengthNode extends Node and has only one child.  Generally if a node extends Node and has only 1 child it may be unnecessary (unless there are coordinate transformations or something else that warrants the extra Node in the hierarchy).

Discovered during #36

**Comment by Denz1994** [comment]
I believe this was fixed in commit 424ff07. Re-assigning for review.

**Comment by samreid** [comment]
Looks great, thanks! Closing.
