### ISSUE TITLE
Mass radius inconsistent with actual cylinder radius derivation. 

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#65]
Considering the comment from @samreid. The ``` this.radius``` attribute should be a square root and not a cube root.
```js
// TODO: This does not look like the volume of a cylinder.  I expected to see
    // density = mass/volume
    // volume = pi*r*r*h
    // therefore radius = Math.sqrt(volume/pi/h) = Math.sqrt(mass/density/pi/h).
    this.radius = Math.pow( this.mass / (DENSITY * HEIGHT_RATIO * Math.PI ), 1 / 3 );
    this.cylinderHeight = this.radius * HEIGHT_RATIO;
    this.height = this.cylinderHeight + this.hookHeight;
```

**Comment by Denz1994** [comment]
After double-checking this suggestion and changing the root the masses are too small in radius.

Using the above suggestion we get this:
_Square root_
![image](https://cloud.githubusercontent.com/assets/13894380/24262074/8bd17364-0fbe-11e7-9562-09f155d37450.png)

_Cubed root_
![image](https://cloud.githubusercontent.com/assets/13894380/24262118/b53a68dc-0fbe-11e7-91f7-79d8aaab8210.png)

Note: Looking at the revision history of this file shows that there is no specific reason as to why the root goes against the mathematical derivation. We can only assume this was changed to meet design standards and this is directly ported from the original flash version.

Closing.

**Comment by samreid** [comment]
@Denz1994 would it be possible to use the square root and change the radii (so that they match the cube root version)?

**Comment by Denz1994** [comment]
A scaling factor has been added for the radius to keep proper derivation using square root.

**Comment by samreid** [comment]
The code change seems great, thanks, closing.
