### ISSUE TITLE
Structure for masses and parameters should be refactored.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#66]
The current methods for stashing and applying scene parameters in the intro screen need cleaning. The parameters should be of an object type and referenced as such. 
0
This may also be handled similarly for the creation of the masses. Currently, the masses are created and referenced in an array. It would be better managed in an object as to not confuse indexes and order of creation.

These are all model elements and will need refactoring in the intro and common model.

**Comment by Denz1994** [comment]
Consider this suggestion by @samreid. Should be able to remove referencedMass()
Keep masses local and array of masses global so they can be referenced by index.

```js
    // REVIEW: Remove referenceMass()
    // var largeLabeledMass = new Mass( .250, new Vector2( .12, .5 ), true, 'grey', tandem.createTandem( 'largeLabeledMass' ) )
    // this.masses =[largeLabeledMass,...];
```

**Comment by Denz1994** [comment]
The suggestion proposed above is useful and I would imagine will be implemented at some point in this sims lifespan. I don't want these masses as an array type because referencing will require index management for stashing and applying scene parameters.

**Comment by samreid** [comment]
>  I don't want these masses as an array type because referencing will require index management for stashing and applying scene parameters.

I thought the code was refactored into separate states so there is no more stashing and applying?

**Comment by Denz1994** [comment]
This issue has been deferred to #70. A different approach towards state restoration has been implemented and is awaiting review. Closing this issue because it is addressed elsewhere.
