### ISSUE TITLE
Unexpected link callbacks?

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#68]
While reviewing #62 I noticed this code in Spring.js

```js
    //  Restart animation if it was squelched
    this.gravityProperty.link( function() {
      if ( self.massProperty.get() ) {
        self.animatingProperty.set( true );
      }
    } );
    this.springConstantProperty.link( function() {
      if ( self.massProperty.get ) {
        self.animatingProperty.set( true );
      }
    } );
```

I am not sure how to read this.  Normally the only vars referenced in a link function should be the variables that were linked (or constants).  But in this case, It looks like when gravity or spring constant changes, it starts animating, but only if a mass was attached.

Also, if this listener turns out to be correct, it looks like it should be factored out.

**Comment by Denz1994** [comment]
You interpreted this correctly. We want to animate the spring only when a mass is attached and if the spring constant and gravity changes.

I factored out the body of the function in a multilink. I know this goes against the conventional use of multilink, but I think I used it because at the time it worked. I don't like going against the convention due to inconsistency, but the multilink architecture is useful for what I'm trying to do.

 Is there another approach I should consider?

**Comment by samreid** [comment]
Should it start animating when the massProperty value changes?

**Comment by Denz1994** [comment]
Linking only the massProperty doesn't give the desired results.

_Consider this scenario:_
A spring with an attached mass should animate when the gravity of the system changes. The weight increases and the spring should match this phenomenon by animating an elongated spring. The same can be considered for spring constant.

**Comment by samreid** [comment]
This line is buggy:

```js
      if ( self.massProperty.get ) {
        self.animatingProperty.set( true );
      }
```

`self.massProperty.get` will always be true.  It should be written as `self.massProperty.get()` to get the correct value.

I'm just wondering: if a mass is attached to a spring (keeping gravity constant), should animated get set to true?  If not, why not?

**Comment by Denz1994** [comment]
> I'm just wondering: if a mass is attached to a spring (keeping gravity constant), should animated get set to true? If not, why not?

- Yes, when the mass is initially attached.
- No, once the mass is at rest but still attached to the spring.
- Yes, when the spring constant of the spring changes. 

```this.animatedProperty``` acts only as a flag for the ```stepOscillate()``` function to be called.
```stepOscillate()``` is responsible for the oscillation of the spring

**Comment by samreid** [comment]
Where is the code that starts animation when the mass is initially attached?

**Comment by Denz1994** [comment]
```MassesAndSpringModel.js``` line 393-395 is always calling the stepOscillate() function whether the mass is attached or not. Once we are in stepOscillate()  in ```Spring.js``` line 325, we first check if the mass is attached and continue from there with how the spring should oscillate.

**Comment by Denz1994** [comment]
We can significantly reduce the number of calls to  ```stepOscillate()``` in the step function if we check if the mass is attached before we call it in ```step()``` in the ```MassesAndSpringModel.js```. Previously the function was always being fired, but now we only fire it when a mass is attached.

This should help with performance.

**Comment by samreid** [comment]
@Denz1994 can you comment on next steps after the above commit?

**Comment by Denz1994** [comment]
The commit 0030b66039571654cb9f2840f3b5e237f737e4d4 factored out the body of the link. We were also able to multilink the referenced properties in the link's function in commit 0526612 and significantly reduce the amount of stepOscillate() calls. After testing the changes, I am ready to close this issue.
