### ISSUE TITLE
design of scene switching on the first screen is inconsistent with other sims

### ISSUE THREAD

**Issue by jbphet** [phetsims/masses-and-springs#69]
I'm doing some code review on Masses and Springs, and I'm troubled by the current behavior of the radio buttons that select between equal length springs and different length springs on the "Intro" screen.  The behavior described can be seen in version http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.1/masses-and-springs_en.html.  The selection buttons look like this:

![ms](https://cloud.githubusercontent.com/assets/3082831/25291967/67e0f0d0-2691-11e7-8ac4-bcc0da9ea9ac.png)

When switching between the equal and unequal spring length settings, an entirely new set of masses is used.  I feel like this could be confusing to users.  Generally, for a change of state this significant, we would use a different screen.  

For the sake of comparison, please take a look at Energy Skate Park: Basics.  There are set of radio buttons that allow the user to select different tracks for the skater.  When the user changes the track, the skater is moved to the default position.  It's always the same skater on a given screen.

I've discussed this with @ariel-phet and @arouinfar and both agreed that we should examine this aspect of the design and possibly make some changes.

**Comment by jbphet** [comment]
I'm going to mark this as high priority, since I'm doing some code review on this sim, and one of the areas that may need some attention is related to this feature, so it would be good to know whether it's going to change and, if so, how, before investing a lot of effort in it.

**Comment by arouinfar** [comment]
@jbphet I'm still leaning towards ESPB-style scene selection -- one set of masses, masses return to their "home" location when the scene is changed. That said, I do not think that the sliders controlling spring properties such as length or spring constant should reset when switching between the scenes. The same goes for checkboxes -- switching scenes should not affect checkbox selection.

I think it will be problematic if the masses to remain on the springs when switching between the two scenes. The motion of the masses will likely look a bit odd due to the potentially different spring properties. Students may not also realize what's different between the two scenes. 

Alternatively, if there are two sets of masses, the students can set up two different experiments and compare the two scenes. I don't think this is a likely use case, as the comparisons that would support the learning goals are self-contained within a scene.

@ariel-phet what do you think?

**Comment by Denz1994** [comment]
Referencing #41, it was discussed that varying the color of the masses would help in providing a better indication that each scene has a different set of masses.

**Comment by arouinfar** [comment]
Thanks @Denz1994, though after discussing the scene selection options with @jbphet, I think we'll instead want to keep the same set of masses across both screens.

**Comment by ariel-phet** [comment]
@arouinfar @Denz1994 I agree that the ESPB-style paradigm seems best to follow if we are going to go with scene selection.

**Comment by Denz1994** [comment]
>  ESPB-style scene selection -- one set of masses, masses return to their "home" location when the scene is changed

I will begin working on these adjustments. Due to the agreed upon nature of mass behavior during scene selection, I will also close #41.

**Comment by Denz1994** [comment]
I was able to make the desired changes to the scene selection behavior. However, there is a side effect.

The masses have this slight dropping animation that resembles the masses behavior when you initialize the sim. However, when you switch the scenes you get this dropping animation as well. This is also mimicked by pressing the reset button quickly as well. 

**Thoughts:**

_Pros:_
- Gives more clarity that these are a new set of masses that is in line with how new masses are visually signified (i.e. dropping animation at sim initialization or pressing the reset button quickly).

- The dropping animation at the screen's initialization looks like a signal that tells the user "I have loaded" or "Sim is ready to be used".

- I also like some initial motion on screen to show that this system is responsive to gravity and motion.

_Cons:_
- Has side effect of what looks like levitating masses if the screen is paused when scenes are switched. IMO it looks like a bug (seen in the photo below).

![image](https://cloud.githubusercontent.com/assets/13894380/25455819/4e011842-2a8e-11e7-8332-73e9732ae9bd.png)

**Question**
Should the mass dropping animation be removed from the scene switching or should it be left as is, similar to how the sim creates new masses?

Also try starting the sim, then switching screens. The masses have the dropping animation, but only when each screen is loaded the first time.

Thoughts @arouinfar?

**Comment by arouinfar** [comment]
@Denz1994 I agree with <i>Pros</i> you've outlined, though I think the dropping animation on startup is enough to convey the information. When switching scenes, I find the animation a bit distracting, and I agree that it could definitely look like a bug when paused. I would recommend that we remove the dropping animation from the scene selection.

**Comment by Denz1994** [comment]
Thanks for the feedback, I will work on removing the dropping animation from the scene selection.
