### ISSUE TITLE
Will we allow springs systems to be critically damped or over-damped?

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/masses-and-springs#8]
If we want to use the analytic solution AND support both under-damped (oscillating) and over-damped (so much friction that position just "decays" towards equilibrium), it would make sense to write the model using complex numbers for intermediate results.

If we just want to support under-damped motion (ensuring c^2 < 4km), the model can be written without having to use intermediate complex numbers.

Thoughts?

**Comment by jonathanolson** [comment]
I'd note that I'm leaning towards the complex-number implementation, so that we aren't constrained by the "weakest possible spring with the smallest possible mass", since that would effectively determine our maximum friction coefficient.

**Comment by ariel-phet** [comment]
@jonathanolson is there any downside to using the complex number implementation?

**Comment by jonathanolson** [comment]
Potentially a bit slower, and will be a bit less clear to read (though can be clear in documentation). Also would need custom code for handling the critically-damped case.

I could mock-up both the complex number one (possibly also with critical damping) and compare it to a Runge-Kutta implementation for accuracy.

**Comment by ariel-phet** [comment]
You and I should discuss a bit on Monday. I will get in touch

**Comment by ariel-phet** [comment]
Discussed with JO over skype 2/22/2016, sounds like the complex number implementation is worth a go since it will give use some more flexibility, should allow us to choose a range of friction that gives a non-negligible effect over a wide dynamic range of spring constants/masses.

**Comment by Denz1994** [comment]
The approach described above has been implemented and is in use in the sim. The only other concern regarding this issue is a matter of documentation which was noted in #98. This issue also hasn't been touched in about a year so I think this is a good time to close and refer any further comments to #98.
