### ISSUE TITLE
Use StringUtils.fillIn instead of StringUtils.format

### ISSUE THREAD

**Issue by samreid** [phetsims/masses-and-springs#84]
From https://github.com/phetsims/circuit-construction-kit-common/issues/350 StringUtils.fillIn is a better way to internationalize and recommended for future production simulations.

**Comment by Denz1994** [comment]
I have implemented stringUtils.fillIn() without the use of stringUtils.format(). I also changed how some of the strings were being used and unnecessary stringUtils.format() calls. The placeholders in the  `masses-and-springs-strings_en.json` have been updated to accommodate stringUtils.fillIn(). 

Assigning to @samreid for review.

**Comment by Denz1994** [comment]
Follow-up: Does this mean that in all sims, usages of stringUtils.format() should be replaced by stringUtils.fillIn()? I would imagine similar treatment of sims would follow the pattern of https://github.com/phetsims/axon/issues/102, where we are constantly chipping away at usages of stringUtils.format()

**Comment by samreid** [comment]
Yes, `fillIn` is preferable, though we don't want to have to force translators to re-translate everything so we may stick with `format` for a long while.

**Comment by samreid** [comment]
What is the `Length 1` string for?  I can't see it in context?

**Comment by Denz1994** [comment]
Okay, that makes sense. It may be a headache for translators.

The Length 1 string is used on the Intro screen in the second scene.

![image](https://user-images.githubusercontent.com/13894380/27047101-186e5a64-4f64-11e7-92f2-c218975c2baf.png)

**Comment by Denz1994** [comment]
The "Length 1" title seems a bit odd to me in its current state. Maybe "Natural Resting Length" or "Spring Length".

I assume "Length 1" is minimalist, like "Constant" or "Gravity".

**Comment by samreid** [comment]
Perhaps "Spring 1 Length" if it is important that it refer to spring 1?  The rest of the change set looks good.

**Comment by Denz1994** [comment]
Sounds good. I will close this issue and make a new design issue related to the title of this panel. Thanks!
