### ISSUE TITLE
Legend for energy graph modal or non-modal.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#85]
As of right now, the legend for the energy graph uses a modal dialog box. Following the design doc the legend mimics a dialog box similar to the "About" dialog in the nav bar.

> Energy legend is a dialog like the About menu. 
-Design Doc 2017

We had some discussion in dev meeting about dialog boxes and apparently, there are other sims that use a similar dialog box but in a non-modal method. It was suggested by several devs to ask if this was the intent.

I published a recent dev version:
 http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.3/masses-and-springs_en.html

Any thoughts @arouinfar?

**Comment by Denz1994** [comment]
More of my two cents:

Would it be ideal to allow users to change screens, while the dialog box is open? As of right now, you can't.

**Comment by arouinfar** [comment]
@Denz1994 thanks for publishing a new dev. The energy dialog behaves exactly as I had imagined. I don't think it would be particularly helpful for the students to interact with the sim while the dialog is open, so I'd rather stick with a modal dialog.

**Comment by Denz1994** [comment]
Okay sounds good. Thanks for the feedback!
