### ISSUE TITLE
Limits on zooming in/out.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#86]
Is there a specific scope that the bars should remain in when zooming in or out? Using the current implementation of Pendulum-Lab, you can zoom in and out indefinitely. Is this something that should be limited? 

http://www.colorado.edu/physics/phet/dev/html/pendulum-lab/1.0.0-dev.11/pendulum-lab_en.html
compared to 
http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.3/masses-and-springs_en.html

Should we allow users to zoom in/out maybe 3 times?
Thoughts @arouinfar?

**Comment by Denz1994** [comment]
I forgot to mention that using the zoom in button on the latest dev version will cause to bars to exceed the panel. This is a bug.

**Comment by arouinfar** [comment]
> Should we allow users to zoom in/out maybe 3 times?

I really like this idea @Denz1994. Given the pretty big range in possible values, I'm not sure how many steps will be necessary to make this possible, but I have a feeling it may be more than 3.

When maxing out m, k, g, and x (mass dragged down to navbar), the total energy bar should completely fill the most zoomed out setting. On the flip side, a reasonable "minimum" scenario (min m, min k, g=moon, x=5cm) should have small, but perceptible bars when zoomed all the way in.

**Comment by Denz1994** [comment]
Okay, that gives me something to work with. I will play around with some values and post a dev version for review. Thanks!

**Comment by Denz1994** [comment]
I was able to fully implement the zoom in/out feature for the energy graph and posted a dev version for testing.

deployed: http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.4/masses-and-springs_en.html

I recommend using the mass value control panel to adjust the green bar. The other sliders such as friction, spring constant, and gravity sliders control the other bars. These are currently wired up this way for testing purposes, but we are at the point where I can use any adjustable model element to be represented in the graph. 

@arouinfar I put a limit of 4 zoom states on the graph (i.e. 1x, 2x, 4x, 8x zoom). Once I implement energy values we get a better idea of how much we need to zoom in/out.

**Question:**
 Do you think it is worth having an indication of how far we have zoomed in (maybe a text reading "1x", "2x", "4x", "8x")? As of right now, the zoom buttons become disabled.

**Question:**
 Assuming we continue with this system of zoom levels with 1x, 2x, 4x, 8x zoom, do you want the zoom to start at 1x? Alternatively, we can start at a middle ground and allow the user to zoom in/out. I thought to start at 1x would be best because the initial state of the graph should be able to give the full context of the initial values of the graph without needing to zoom in/out. 

**Question:**
Typically cameras use a 2^n  zoom factor, where the zoom increases by squares of 2 (ie. 1x,2x,4x,8x). This is the current implementation of the zoom function. Is this okay? Alternatively, we can use zoom states of [1,x, 2x, 3x ,4x, 5x, 6x, 7x, 8x ] or [1x, 3x, 6x, 9x]. When I asked Chris, he said there is no PhET standard, so we have a lot of freedom.

**Comment by arouinfar** [comment]
@Denz1994 I really like the idea of using a 2^n zoom level. The default zoom level will probably need to be somewhere in the middle to optimize the for the default parameters. We might want to consider labelling the zoom level with respect to the default, so 1/4, 1/2, 1, 2, 4 rather than 1, 2, 4, 8, 16 -- but that's something we can consider more once the energy values are implemented.

I'd like to add an arrow to indicate when a bar is off-scale. We've done something similar in Capacitor Lab: Basics which has worked well.
![image](https://user-images.githubusercontent.com/8419308/27190737-b6d38724-51b2-11e7-87b3-4a3c6a25bd83.png)

I've added off-scale arrows and a zoom-level readout to the graph.
![image](https://user-images.githubusercontent.com/8419308/27191421-f5478b20-51b4-11e7-938a-d950c32c9fbe.png)

What do you think @Denz1994?

**Comment by Denz1994** [comment]
I like these changes. I am working on adding the arrows into the common code file. I also like the readout for the zoom (2x).

Should the (2x) zoom readout be internationalized @arouinfar?

**Comment by arouinfar** [comment]
> Should the (2x) zoom readout be internationalized @arouinfar?

Great question. I would think that "x" for multiplication is pretty universal mathematical symbol, and we don't support i18n of numbers, so my guess is that it may not be necessary. @Denz1994 can you hold off on i18n until the design team can review the changes?

**Comment by Denz1994** [comment]
Adding a new dev version to test in the interim before the correct energy values are added.

http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.6/masses-and-springs_en.html

Additions: 

- Zoom readout (still needs 1/4, 1/2, 1, 2, 4 values)
- Continuous arrows added to the top of the bar nodes.
- Info button Icon
- Energy title position changed on graph area, not just the accordion box title.

**Comment by Denz1994** [comment]
This new dev version may be worth discussing at the design meeting for the values of the zoom readout. [1.0.0-dev.17](http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.17/masses-and-springs_en.html)


Do we still want still want 1/4, 1/2, 1, 2, 4 values for the zoom readout?

**Comment by arouinfar** [comment]
Let's discuss at design meeting.

**Comment by arouinfar** [comment]
@Denz1994 last week we decided to remove the zoom-level label (e.g. "2x"). It looks like the zoom level was removed in dev.20. Can this issue be closed?

**Comment by Denz1994** [comment]
Yes, it can. Thanks for the notice.

Zoom label removed in commit 00958ca0b70b8ebac947811573f6604cf388b7d3
