### ISSUE TITLE
Change Spring Length Title "Length 1"?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#87]
![image](https://user-images.githubusercontent.com/13894380/27047624-fa4af82e-4f65-11e7-8196-e38134398c5f.png)

"Length 1" is the current title of the panel that changes the natural resting length of a spring. My thought was that this could be worded better. Perhaps, "Spring 1 Length" or "Natural Resting Length"?

Just a thought, but if "Length 1" works, then let it be.

**Comment by arouinfar** [comment]
@Denz1994 good point. I like "Spring Length 1".  I put the number at the end to be more in line with other sims (like Hooke's Law) were the label reads as "variableName #". What do you think?

**Comment by Denz1994** [comment]
I don't mind "Spring Length 1". I think it sounds better than "Length 1". I will implement this. Thanks for the input.
