### ISSUE TITLE
Info Icon needs to be added to legend button.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#89]
![image](https://user-images.githubusercontent.com/13894380/27191235-6b644e98-51b4-11e7-90d9-1c87a316cba1.png)
Make this happen.

**Comment by Denz1994** [comment]
This may need to be drawn programmatically. I don't think there is a common code shape for it.

**Comment by Denz1994** [comment]
There is a common code shape for this... FontAwesomeNode.js

I imported the svg data for a new 'info_circle' for font awesome. This was then imported as the content option for my info button. Thanks, @pixelzoom for the suggestion assigning for review of common code changes.

Re-assigning for review of common code changes.

**Comment by pixelzoom** [comment]
FontAwesomeNode change was in https://github.com/phetsims/sun/commit/c97ad88d7865e4efa2a4a630c793c67447a060f8.

Looks great 👍.  Back to @Denz1994 in case there's other work to be done here.

**Comment by Denz1994** [comment]
Thanks for the quick response. Closing this issue.
