### ISSUE TITLE
Design screen icons

### ISSUE THREAD

**Issue by arouinfar** [phetsims/masses-and-springs#90]
We need screen icons!

**Comment by arouinfar** [comment]
I'd like to mirror the icons used in Pendulum Lab, where possible.
![image](https://user-images.githubusercontent.com/8419308/28796389-980aad88-75fa-11e7-9524-d515ad23991d.png)

Once challenge is that there are two screens which have vectors (Vectors & Lab). I've mocked up some pretty rough screen icons. I'm pretty happy with Vectors and Energy, but would love to hear ideas from @ariel-phet and/or @Denz1994.

![image](https://user-images.githubusercontent.com/8419308/28796444-c48afa02-75fa-11e7-9d56-1fd8a1a8b1b1.png)

**Comment by Denz1994** [comment]
Can we add a colored mass to the left most icon (intro tab)? It seems like the image is in grayscale while the others are a bit more vibrant.

Or perhaps, for the intro screen, we can have a two spring system shown with one gray mass hanging from a spring (as shown) and a colored mass hanging from second slightly compressed spring.

**Comment by ariel-phet** [comment]
@arouinfar I think I would zoom in on the masses quite a bit more on vectors and lab.

If not too busy, maybe put all 4 vectors on the vectors icon, and then just acceleration and velocity on the lab icon (since only velocity and acceleration are available on lab)

Or perhaps lab could be some iconic sliders suggesting you can adjust lots of parameters?

**Comment by Denz1994** [comment]
Place holders have been committed for the nav-bar and home screen icons.

**Comment by arouinfar** [comment]
@ariel-phet @Denz1994 here are some updated options for screen icons. For the most part, I think we'll need to modify the navbar icons, with my personal preference being the right-most option for each screen.

* For Intro, I decided to go with a two-spring comparison. One of the masses could instead be a mystery mass for a bit more color. 
* Showing all vectors for the Vectors screen icon seems ok to me, but I think it can look a bit too busy in the navbar.
* For Lab, I thought it would be nice to show a measurement. The ruler makes the Lab icon a bit more distinct from the others, as well.
<img width="895" alt="screen shot 2017-10-13 at 3 30 46 pm" src="https://user-images.githubusercontent.com/8419308/31567200-8e8e0082-b02b-11e7-9b40-ebb5ed19e25d.png">

**Comment by ariel-phet** [comment]
@arouinfar Those all look good to me. I am fine with modifying the icons for the navbar, although I think they could work as is.

The "?" mark should probably be removed on the lab icon, as this is a symbol that can be translated (and would be too small to see on the navbar anyhow).

**Comment by ariel-phet** [comment]
@arouinfar also agreed that maybe using another color the second mass for the intro icon would be nice to make it a bit more inviting on the homescreen.

**Comment by arouinfar** [comment]
Thanks @ariel-phet! 

I've cleaned up the icons a bit and have sent the assets to @Denz1994 for implementation.

**Comment by Denz1994** [comment]
I've added the images to the home screen and nav bar. I will release a new dev version sometime today, but you can view the changes in master. Thanks @arouinfar. Please close this issue if you feel the images work. I like them personally.

**Comment by arouinfar** [comment]
Thanks @Denz1994! 

There appears to be a white outline around the inactive screen options, which looks a bit too bright and distracting.
![screen shot 2017-10-26 at 11 07 08 am](https://user-images.githubusercontent.com/8419308/32066704-e3320c0c-ba3d-11e7-8808-016e41e5e5bc.png)

Other sims with white screen icons do not have this outline.
![image](https://user-images.githubusercontent.com/8419308/32066779-2895eba6-ba3e-11e7-8001-77163b01b886.png)

Would it be possible to remove the outline @Denz1994?

**Comment by Denz1994** [comment]
Good catch. I'm on it!

**Comment by arouinfar** [comment]
Thanks @Denz1994! The icons are looking good otherwise.
