### ISSUE TITLE
Hooks for masses.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#91]
According to design doc and a design meeting from earlier this year.
> Mass appearance.
> Hook cues that the mass can be hung.
> Add hook.

Is there artwork for the mass hooks? If not I can use the Java version as a mockup and see how that looks.
![image](https://user-images.githubusercontent.com/13894380/27289819-8a108dae-54c8-11e7-918d-5aae9c04dc79.png)

**Comment by arouinfar** [comment]
@Denz1994 I haven't mocked up the hooks, but they should look similar to the Flash version. After you add the hooks, you'll need to shift the equilibrium position down so it remains even with the top of the mass.

**Comment by Denz1994** [comment]
I just added a prototype for the hooks. Let me know if you like them. Also, it was mentioned during a status meeting some time ago and in the design doc that the sizes of the masses were too big. These masses are smaller but aren't exactly how the design doc specified.

I would add as well, ignore the lab screen mass labels. It is still a work in progress.

Test here:http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.5/masses-and-springs_en.html

Feedback @arouinfar?

**Comment by arouinfar** [comment]
@Denz1994 the hooks look good! As for the dimensions, I believe the decision was to use the aspect ratio and scaling from Pendulum Lab. 

Also, please ignore my previous request to shift the equilibrium position. For some reason I thought the equilibrium position referenced the top of the masses (which would require a shift) but they in fact are aligned to the bottom-most coil, which is the physically correct location.

**Comment by Denz1994** [comment]
> @Denz1994 the hooks look good! As for the dimensions, I believe the decision was to use the aspect ratio and scaling from Pendulum Lab.

@arouinfar When you mentioned the aspect ratio, are you referring to the hook or mass?
The pendulum in pendulum lab doesn't have hooks to compare so I'm assuming you mean the mass.

**Comment by arouinfar** [comment]
Great question @Denz1994. I was referring to the mass itself. Sorry about that!

**Comment by Denz1994** [comment]
Okay sounds good, then I will close this issue. I have created a new issue for the mass aspect ratio.Thanks for the feedback.
