### ISSUE TITLE
Scaling of masses should resemble  the masses in pendulum lab.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#93]
The MassNodes should be represented based on their volume. Check the ratio used in pendulum lab and replicate.

**Comment by Denz1994** [comment]
The mass heights have been adjusted and they are now more elongated matching the design doc.  Do you want the adjustable mass on the energy/lab screen to scale in size based on its mass?

Personal intake: It may have the unintended effect of relaying to users that a larger mass may mean more volume. 

Check the latest dev [version](http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.13/masses-and-springs_en.html) to review the sizes of the masses compared to the previous [version](http://www.colorado.edu/physics/phet/dev/html/masses-and-springs/1.0.0-dev.12/masses-and-springs_en.html)

Thoughts @arouinfar?

**Comment by arouinfar** [comment]
Looking good @Denz1994. The masses in the mockups were intended to match the aspect ratio of the masses in Pendulum Lab. It looks pretty close, but can you confirm that it's the same?

> It may have the unintended effect of relaying to users that a larger mass may mean more volume.

I get what you're saying, but assuming the material of the mass doesn't change, the natural consequence of increased mass would mean increased volume. We haven't done anything to cue that the mass has a non-constant density, and we've also depicted larger masses as taking up more volume, so I think it would make the most sense if the size of the adjustable mass scaled with its mass.

**Comment by Denz1994** [comment]
Closing this issue because the bounds of the massNodes have been updated a while ago, along with the addition of the mass hooks.
