### ISSUE TITLE
Update documentation of spring.step() with complex number implementation.

### ISSUE THREAD

**Issue by Denz1994** [phetsims/masses-and-springs#98]
It is time to bring some clarity to this method, particularly in its documentation

- [x] Document what algorithm/mathematical model is being used
- [ ] Refactor variable names where possible.
- [ ] Factor out code where needed.

**Comment by Denz1994** [comment]
This feed was useful.

https://www.quora.com/What-are-over-damped-critically-and-under-damped-systems

**Comment by Denz1994** [comment]
After collaborating with @jonathanolson, the core mathematical model was once detailed and would require an independent review to refactor. The model does work but may be able to be replaced by Twixt/DampedAnimation.js. Deferring for now.

**Comment by Denz1994** [comment]
Can @jonathanolson review this mathematical model and update the documentation as you see fit?

**Comment by jonathanolson** [comment]
Added my mathematica notes used to generate the model code in `assets/`, along with a PDF conversion.

I'll be looking through those to come up with the more detailed documentation for model.md and for in the code itself.

**Comment by jonathanolson** [comment]
Whoops, didn't see this issue. Should be done in https://github.com/phetsims/masses-and-springs/commit/14bb0b4acc171e7aa5563892518831f70f61528a.

There's not really a great way of cleaning up any of the formula bits, and it appears to be working well.
